Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('luat_lcd', src, depend = ['PKG_USING_LUATOS_SOC_LCD'], CPPPATH = CPPPATH)

Return('group')
