
#ifndef LUAT_LVGL_SYMBOL
#define LUAT_LVGL_SYMBOL

#include "luat_base.h"
#include "rotable2.h"

#define LUAT_LV_SYMBOL_RLT \
{"SYMBOL_AUDIO",        ROREG_STR(LV_SYMBOL_AUDIO           )},\
{"SYMBOL_VIDEO",        ROREG_STR(LV_SYMBOL_VIDEO           )},\
{"SYMBOL_LIST",         ROREG_STR(LV_SYMBOL_LIST            )},\
{"SYMBOL_OK",           ROREG_STR(LV_SYMBOL_OK              )},\
{"SYMBOL_CLOSE",        ROREG_STR(LV_SYMBOL_CLOSE           )},\
{"SYMBOL_POWER",        ROREG_STR(LV_SYMBOL_POWER           )},\
{"SYMBOL_SETTINGS",     ROREG_STR(LV_SYMBOL_SETTINGS        )},\
{"SYMBOL_HOME",         ROREG_STR(LV_SYMBOL_HOME            )},\
{"SYMBOL_DOWNLOAD",     ROREG_STR(LV_SYMBOL_DOWNLOAD        )},\
{"SYMBOL_DRIVE",        ROREG_STR(LV_SYMBOL_DRIVE           )},\
{"SYMBOL_REFRESH",      ROREG_STR(LV_SYMBOL_REFRESH         )},\
{"SYMBOL_MUTE",         ROREG_STR(LV_SYMBOL_MUTE            )},\
{"SYMBOL_VOLUME_MID",   ROREG_STR(LV_SYMBOL_VOLUME_MID      )},\
{"SYMBOL_VOLUME_MAX",   ROREG_STR(LV_SYMBOL_VOLUME_MAX      )},\
{"SYMBOL_IMAGE",        ROREG_STR(LV_SYMBOL_IMAGE           )},\
{"SYMBOL_EDIT",         ROREG_STR(LV_SYMBOL_EDIT            )},\
{"SYMBOL_PREV",         ROREG_STR(LV_SYMBOL_PREV            )},\
{"SYMBOL_PLAY",         ROREG_STR(LV_SYMBOL_PLAY            )},\
{"SYMBOL_PAUSE",        ROREG_STR(LV_SYMBOL_PAUSE           )},\
{"SYMBOL_STOP",         ROREG_STR(LV_SYMBOL_STOP            )},\
{"SYMBOL_NEXT",         ROREG_STR(LV_SYMBOL_NEXT            )},\
{"SYMBOL_EJECT",        ROREG_STR(LV_SYMBOL_EJECT           )},\
{"SYMBOL_LEFT",         ROREG_STR(LV_SYMBOL_LEFT            )},\
{"SYMBOL_RIGHT",        ROREG_STR(LV_SYMBOL_RIGHT           )},\
{"SYMBOL_PLUS",         ROREG_STR(LV_SYMBOL_PLUS            )},\
{"SYMBOL_MINUS",        ROREG_STR(LV_SYMBOL_MINUS           )},\
{"SYMBOL_EYE_OPEN",     ROREG_STR(LV_SYMBOL_EYE_OPEN        )},\
{"SYMBOL_EYE_CLOSE",    ROREG_STR(LV_SYMBOL_EYE_CLOSE       )},\
{"SYMBOL_WARNING",      ROREG_STR(LV_SYMBOL_WARNING         )},\
{"SYMBOL_SHUFFLE",      ROREG_STR(LV_SYMBOL_SHUFFLE         )},\
{"SYMBOL_UP",           ROREG_STR(LV_SYMBOL_UP              )},\
{"SYMBOL_DOWN",         ROREG_STR(LV_SYMBOL_DOWN            )},\
{"SYMBOL_LOOP",         ROREG_STR(LV_SYMBOL_LOOP            )},\
{"SYMBOL_DIRECTORY",    ROREG_STR(LV_SYMBOL_DIRECTORY       )},\
{"SYMBOL_UPLOAD",       ROREG_STR(LV_SYMBOL_UPLOAD          )},\
{"SYMBOL_CALL",         ROREG_STR(LV_SYMBOL_CALL            )},\
{"SYMBOL_CUT",          ROREG_STR(LV_SYMBOL_CUT             )},\
{"SYMBOL_COPY",         ROREG_STR(LV_SYMBOL_COPY            )},\
{"SYMBOL_SAVE",         ROREG_STR(LV_SYMBOL_SAVE            )},\
{"SYMBOL_CHARGE",       ROREG_STR(LV_SYMBOL_CHARGE          )},\
{"SYMBOL_PASTE",        ROREG_STR(LV_SYMBOL_PASTE           )},\
{"SYMBOL_BELL",         ROREG_STR(LV_SYMBOL_BELL            )},\
{"SYMBOL_KEYBOARD",     ROREG_STR(LV_SYMBOL_KEYBOARD        )},\
{"SYMBOL_GPS",          ROREG_STR(LV_SYMBOL_GPS             )},\
{"SYMBOL_FILE",         ROREG_STR(LV_SYMBOL_FILE            )},\
{"SYMBOL_WIFI",         ROREG_STR(LV_SYMBOL_WIFI            )},\
{"SYMBOL_BATTERY_FULL", ROREG_STR(LV_SYMBOL_BATTERY_FULL    )},\
{"SYMBOL_BATTERY_3",    ROREG_STR(LV_SYMBOL_BATTERY_3       )},\
{"SYMBOL_BATTERY_2",    ROREG_STR(LV_SYMBOL_BATTERY_2       )},\
{"SYMBOL_BATTERY_1",    ROREG_STR(LV_SYMBOL_BATTERY_1       )},\
{"SYMBOL_BATTERY_EMPTY",ROREG_STR(LV_SYMBOL_BATTERY_EMPTY   )},\
{"SYMBOL_USB",          ROREG_STR(LV_SYMBOL_USB             )},\
{"SYMBOL_BLUETOOTH",    ROREG_STR(LV_SYMBOL_BLUETOOTH       )},\
{"SYMBOL_TRASH",        ROREG_STR(LV_SYMBOL_TRASH           )},\
{"SYMBOL_BACKSPACE",    ROREG_STR(LV_SYMBOL_BACKSPACE       )},\
{"SYMBOL_SD_CARD",      ROREG_STR(LV_SYMBOL_SD_CARD         )},\
{"SYMBOL_NEW_LINE",     ROREG_STR(LV_SYMBOL_NEW_LINE        )},\
{"SYMBOL_DUMMY",        ROREG_STR(   "\xEF\xA3\xBF"         )},\
{"SYMBOL_BULLET",       ROREG_STR(LV_SYMBOL_BULLET)},

#endif
