from building import *

cwd = GetCurrentDir()
# src = Glob('*.c')
src = Split("""
luat_fs_weak.c
luat_log_weak.c
luat_malloc_weak.c
""")

if GetDepend(['RT_USING_PWM']):
    src += ['luat_pwm_weak.c']

if GetDepend(['RT_USING_SPI']):
    src += ['luat_spi_device.c']

CPPPATH = [cwd]

group = DefineGroup('luat_weak', src, depend = [], CPPPATH = CPPPATH)

Return('group')