# for module compiling
import os
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = str(Dir('#'))
#print(">>>" + cwd)
objs = SConscript(os.path.join(cwd, '../../rtt/SConscript'))
objs = objs + SConscript(os.path.join(cwd, '../../../lua/SConscript'))
objs = objs + SConscript(os.path.join(cwd, '../../../luat/SConscript'))

src = Glob('*.c')
include_path = [cwd]

objs = objs + DefineGroup('Applications', src, depend = [''], CPPPATH = include_path)

Return('objs')
