from building import *

cwd = GetCurrentDir()
src	= []
for p in os.listdir(cwd) :
    if p.endswith(".c"):
        src += [p]

#src.remove('GUI_Paint.c')

CPPPATH = [cwd]

group = DefineGroup('epaper', src, depend = ['PKG_USING_LUATOS_SOC_EINK'], CPPPATH = CPPPATH)

Return('group')
