

includes("coremark")
includes("dbg")
includes("i2c-tools")
includes("iconv")
includes("iotauth")
includes("libcoap")
includes("minmea")
includes("mqttcore")
includes("pack")
includes("vmx")
includes("ymodem")
includes("zbuff")

target("tools")
    set_kind("static")
    add_deps("coremark")
    add_deps("dbg")
    add_deps("i2c-tools")
    add_deps("iconv")
    add_deps("iotauth")
    add_deps("libcoap")
    add_deps("minmea")
    add_deps("mqttcore")
    add_deps("pack")
    add_deps("vmx")
    add_deps("ymodem")
    add_deps("zbuff")
target_end()