Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src	= Glob('src/*.c')
CPPPATH = [cwd + "/include"]

group = DefineGroup('Lua', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
