
#ifndef LUAT_LVGL_EX
#define LUAT_LVGL_EX

#include "luat_base.h"
#include "lvgl.h"

void luat_lvgl_ex_libs(lua_State *L);

#define LUAT_LV_EX_RLT {"DPI", ROREG_INT(LV_DPI)},\
{"IMG_ZOOM_NONE", ROREG_INT(LV_IMG_ZOOM_NONE)},\
{"COLOR_WHITE", ROREG_INT(0xFFFFFFFF)},\
{"COLOR_SILVER", ROREG_INT(0xFFC0C0C0)},\
{"COLOR_GRAY", ROREG_INT(0xFF808080)},\
{"COLOR_BLACK", ROREG_INT(0xFF000000)},\
{"COLOR_RED ", ROREG_INT(0xFFFF0000)},\
{"COLOR_MAROON", ROREG_INT(0xFF800000)},\
{"COLOR_YELLOW", ROREG_INT(0xFFFFFF00)},\
{"COLOR_OLIVE", ROREG_INT(0xFF808000)},\
{"COLOR_LIME", ROREG_INT(0xFF00FF00)},\
{"COLOR_GREEN", ROREG_INT(0xFF008000)},\
{"COLOR_CYAN", ROREG_INT(0xFF00FFFF)},\
{"COLOR_AQUA", ROREG_INT(0xFF00FFFF)},\
{"COLOR_TEAL", ROREG_INT(0xFF008080)},\
{"COLOR_BLUE", ROREG_INT(0xFF0000FF)},\
{"COLOR_NAVY", ROREG_INT(0xFF000080)},\
{"COLOR_MAGENTA", ROREG_INT(0xFFFF00FF)},\
{"COLOR_PURPLE", ROREG_INT(0xFF800080)},\
{"COLOR_ORANGE", ROREG_INT(0xFFFFA500)},\

#endif
