#include "luat_base.h"
#include "luat_msgbus.h"
#include "luat_lvgl.h"
#include "lvgl.h"

#define font_regular_12                 0
#define font_regular_14                 1
#define font_regular_16                 2
#define font_simsun_12                  3
#define font_simsun_48                  4

int luat_lv_style_set_radius(lua_State *L);
int luat_lv_style_get_radius(lua_State *L);
int luat_lv_style_set_clip_corner(lua_State *L);
int luat_lv_style_get_clip_corner(lua_State *L);
int luat_lv_style_set_size(lua_State *L);
int luat_lv_style_get_size(lua_State *L);
int luat_lv_style_set_transform_width(lua_State *L);
int luat_lv_style_get_transform_width(lua_State *L);
int luat_lv_style_set_transform_height(lua_State *L);
int luat_lv_style_get_transform_height(lua_State *L);
int luat_lv_style_set_transform_angle(lua_State *L);
int luat_lv_style_get_transform_angle(lua_State *L);
int luat_lv_style_set_transform_zoom(lua_State *L);
int luat_lv_style_get_transform_zoom(lua_State *L);
int luat_lv_style_set_opa_scale(lua_State *L);
int luat_lv_style_get_opa_scale(lua_State *L);
int luat_lv_style_set_pad_top(lua_State *L);
int luat_lv_style_get_pad_top(lua_State *L);
int luat_lv_style_set_pad_bottom(lua_State *L);
int luat_lv_style_get_pad_bottom(lua_State *L);
int luat_lv_style_set_pad_left(lua_State *L);
int luat_lv_style_get_pad_left(lua_State *L);
int luat_lv_style_set_pad_right(lua_State *L);
int luat_lv_style_get_pad_right(lua_State *L);
int luat_lv_style_set_pad_inner(lua_State *L);
int luat_lv_style_get_pad_inner(lua_State *L);
int luat_lv_style_set_margin_top(lua_State *L);
int luat_lv_style_get_margin_top(lua_State *L);
int luat_lv_style_set_margin_bottom(lua_State *L);
int luat_lv_style_get_margin_bottom(lua_State *L);
int luat_lv_style_set_margin_left(lua_State *L);
int luat_lv_style_get_margin_left(lua_State *L);
int luat_lv_style_set_margin_right(lua_State *L);
int luat_lv_style_get_margin_right(lua_State *L);
int luat_lv_style_set_bg_blend_mode(lua_State *L);
int luat_lv_style_get_bg_blend_mode(lua_State *L);
int luat_lv_style_set_bg_main_stop(lua_State *L);
int luat_lv_style_get_bg_main_stop(lua_State *L);
int luat_lv_style_set_bg_grad_stop(lua_State *L);
int luat_lv_style_get_bg_grad_stop(lua_State *L);
int luat_lv_style_set_bg_grad_dir(lua_State *L);
int luat_lv_style_get_bg_grad_dir(lua_State *L);
int luat_lv_style_set_bg_color(lua_State *L);
int luat_lv_style_get_bg_color(lua_State *L);
int luat_lv_style_set_bg_grad_color(lua_State *L);
int luat_lv_style_get_bg_grad_color(lua_State *L);
int luat_lv_style_set_bg_opa(lua_State *L);
int luat_lv_style_get_bg_opa(lua_State *L);
int luat_lv_style_set_border_width(lua_State *L);
int luat_lv_style_get_border_width(lua_State *L);
int luat_lv_style_set_border_side(lua_State *L);
int luat_lv_style_get_border_side(lua_State *L);
int luat_lv_style_set_border_blend_mode(lua_State *L);
int luat_lv_style_get_border_blend_mode(lua_State *L);
int luat_lv_style_set_border_post(lua_State *L);
int luat_lv_style_get_border_post(lua_State *L);
int luat_lv_style_set_border_color(lua_State *L);
int luat_lv_style_get_border_color(lua_State *L);
int luat_lv_style_set_border_opa(lua_State *L);
int luat_lv_style_get_border_opa(lua_State *L);
int luat_lv_style_set_outline_width(lua_State *L);
int luat_lv_style_get_outline_width(lua_State *L);
int luat_lv_style_set_outline_pad(lua_State *L);
int luat_lv_style_get_outline_pad(lua_State *L);
int luat_lv_style_set_outline_blend_mode(lua_State *L);
int luat_lv_style_get_outline_blend_mode(lua_State *L);
int luat_lv_style_set_outline_color(lua_State *L);
int luat_lv_style_get_outline_color(lua_State *L);
int luat_lv_style_set_outline_opa(lua_State *L);
int luat_lv_style_get_outline_opa(lua_State *L);
int luat_lv_style_set_shadow_width(lua_State *L);
int luat_lv_style_get_shadow_width(lua_State *L);
int luat_lv_style_set_shadow_ofs_x(lua_State *L);
int luat_lv_style_get_shadow_ofs_x(lua_State *L);
int luat_lv_style_set_shadow_ofs_y(lua_State *L);
int luat_lv_style_get_shadow_ofs_y(lua_State *L);
int luat_lv_style_set_shadow_spread(lua_State *L);
int luat_lv_style_get_shadow_spread(lua_State *L);
int luat_lv_style_set_shadow_blend_mode(lua_State *L);
int luat_lv_style_get_shadow_blend_mode(lua_State *L);
int luat_lv_style_set_shadow_color(lua_State *L);
int luat_lv_style_get_shadow_color(lua_State *L);
int luat_lv_style_set_shadow_opa(lua_State *L);
int luat_lv_style_get_shadow_opa(lua_State *L);
int luat_lv_style_set_pattern_repeat(lua_State *L);
int luat_lv_style_get_pattern_repeat(lua_State *L);
int luat_lv_style_set_pattern_blend_mode(lua_State *L);
int luat_lv_style_get_pattern_blend_mode(lua_State *L);
int luat_lv_style_set_pattern_recolor(lua_State *L);
int luat_lv_style_get_pattern_recolor(lua_State *L);
int luat_lv_style_set_pattern_opa(lua_State *L);
int luat_lv_style_get_pattern_opa(lua_State *L);
int luat_lv_style_set_pattern_recolor_opa(lua_State *L);
int luat_lv_style_get_pattern_recolor_opa(lua_State *L);
int luat_lv_style_set_pattern_image(lua_State *L);
int luat_lv_style_get_pattern_image(lua_State *L);
int luat_lv_style_set_value_letter_space(lua_State *L);
int luat_lv_style_get_value_letter_space(lua_State *L);
int luat_lv_style_set_value_line_space(lua_State *L);
int luat_lv_style_get_value_line_space(lua_State *L);
int luat_lv_style_set_value_blend_mode(lua_State *L);
int luat_lv_style_get_value_blend_mode(lua_State *L);
int luat_lv_style_set_value_ofs_x(lua_State *L);
int luat_lv_style_get_value_ofs_x(lua_State *L);
int luat_lv_style_set_value_ofs_y(lua_State *L);
int luat_lv_style_get_value_ofs_y(lua_State *L);
int luat_lv_style_set_value_align(lua_State *L);
int luat_lv_style_get_value_align(lua_State *L);
int luat_lv_style_set_value_color(lua_State *L);
int luat_lv_style_get_value_color(lua_State *L);
int luat_lv_style_set_value_opa(lua_State *L);
int luat_lv_style_get_value_opa(lua_State *L);
int luat_lv_style_set_value_font(lua_State *L);
int luat_lv_style_get_value_font(lua_State *L);
int luat_lv_style_set_value_str(lua_State *L);
int luat_lv_style_get_value_str(lua_State *L);
int luat_lv_style_set_text_letter_space(lua_State *L);
int luat_lv_style_get_text_letter_space(lua_State *L);
int luat_lv_style_set_text_line_space(lua_State *L);
int luat_lv_style_get_text_line_space(lua_State *L);
int luat_lv_style_set_text_decor(lua_State *L);
int luat_lv_style_get_text_decor(lua_State *L);
int luat_lv_style_set_text_blend_mode(lua_State *L);
int luat_lv_style_get_text_blend_mode(lua_State *L);
int luat_lv_style_set_text_color(lua_State *L);
int luat_lv_style_get_text_color(lua_State *L);
int luat_lv_style_set_text_sel_color(lua_State *L);
int luat_lv_style_get_text_sel_color(lua_State *L);
int luat_lv_style_set_text_sel_bg_color(lua_State *L);
int luat_lv_style_get_text_sel_bg_color(lua_State *L);
int luat_lv_style_set_text_opa(lua_State *L);
int luat_lv_style_get_text_opa(lua_State *L);
int luat_lv_style_set_text_font(lua_State *L);
int luat_lv_style_get_text_font(lua_State *L);
int luat_lv_style_set_line_width(lua_State *L);
int luat_lv_style_get_line_width(lua_State *L);
int luat_lv_style_set_line_blend_mode(lua_State *L);
int luat_lv_style_get_line_blend_mode(lua_State *L);
int luat_lv_style_set_line_dash_width(lua_State *L);
int luat_lv_style_get_line_dash_width(lua_State *L);
int luat_lv_style_set_line_dash_gap(lua_State *L);
int luat_lv_style_get_line_dash_gap(lua_State *L);
int luat_lv_style_set_line_rounded(lua_State *L);
int luat_lv_style_get_line_rounded(lua_State *L);
int luat_lv_style_set_line_color(lua_State *L);
int luat_lv_style_get_line_color(lua_State *L);
int luat_lv_style_set_line_opa(lua_State *L);
int luat_lv_style_get_line_opa(lua_State *L);
int luat_lv_style_set_image_blend_mode(lua_State *L);
int luat_lv_style_get_image_blend_mode(lua_State *L);
int luat_lv_style_set_image_recolor(lua_State *L);
int luat_lv_style_get_image_recolor(lua_State *L);
int luat_lv_style_set_image_opa(lua_State *L);
int luat_lv_style_get_image_opa(lua_State *L);
int luat_lv_style_set_image_recolor_opa(lua_State *L);
int luat_lv_style_get_image_recolor_opa(lua_State *L);
int luat_lv_style_set_transition_time(lua_State *L);
int luat_lv_style_get_transition_time(lua_State *L);
int luat_lv_style_set_transition_delay(lua_State *L);
int luat_lv_style_get_transition_delay(lua_State *L);
int luat_lv_style_set_transition_prop_1(lua_State *L);
int luat_lv_style_get_transition_prop_1(lua_State *L);
int luat_lv_style_set_transition_prop_2(lua_State *L);
int luat_lv_style_get_transition_prop_2(lua_State *L);
int luat_lv_style_set_transition_prop_3(lua_State *L);
int luat_lv_style_get_transition_prop_3(lua_State *L);
int luat_lv_style_set_transition_prop_4(lua_State *L);
int luat_lv_style_get_transition_prop_4(lua_State *L);
int luat_lv_style_set_transition_prop_5(lua_State *L);
int luat_lv_style_get_transition_prop_5(lua_State *L);
int luat_lv_style_set_transition_prop_6(lua_State *L);
int luat_lv_style_get_transition_prop_6(lua_State *L);
int luat_lv_style_set_scale_width(lua_State *L);
int luat_lv_style_get_scale_width(lua_State *L);
int luat_lv_style_set_scale_border_width(lua_State *L);
int luat_lv_style_get_scale_border_width(lua_State *L);
int luat_lv_style_set_scale_end_border_width(lua_State *L);
int luat_lv_style_get_scale_end_border_width(lua_State *L);
int luat_lv_style_set_scale_end_line_width(lua_State *L);
int luat_lv_style_get_scale_end_line_width(lua_State *L);
int luat_lv_style_set_scale_grad_color(lua_State *L);
int luat_lv_style_get_scale_grad_color(lua_State *L);
int luat_lv_style_set_scale_end_color(lua_State *L);
int luat_lv_style_get_scale_end_color(lua_State *L);

#define LUAT_LV_STYLE_DEC_RLT {"style_set_radius", luat_lv_style_set_radius, 0},\
{"style_set_clip_corner", luat_lv_style_set_clip_corner, 0},\
{"style_set_size", luat_lv_style_set_size, 0},\
{"style_set_transform_width", luat_lv_style_set_transform_width, 0},\
{"style_set_transform_height", luat_lv_style_set_transform_height, 0},\
{"style_set_transform_angle", luat_lv_style_set_transform_angle, 0},\
{"style_set_transform_zoom", luat_lv_style_set_transform_zoom, 0},\
{"style_set_opa_scale", luat_lv_style_set_opa_scale, 0},\
{"style_set_pad_top", luat_lv_style_set_pad_top, 0},\
{"style_set_pad_bottom", luat_lv_style_set_pad_bottom, 0},\
{"style_set_pad_left", luat_lv_style_set_pad_left, 0},\
{"style_set_pad_right", luat_lv_style_set_pad_right, 0},\
{"style_set_pad_inner", luat_lv_style_set_pad_inner, 0},\
{"style_set_margin_top", luat_lv_style_set_margin_top, 0},\
{"style_set_margin_bottom", luat_lv_style_set_margin_bottom, 0},\
{"style_set_margin_left", luat_lv_style_set_margin_left, 0},\
{"style_set_margin_right", luat_lv_style_set_margin_right, 0},\
{"style_set_bg_blend_mode", luat_lv_style_set_bg_blend_mode, 0},\
{"style_set_bg_main_stop", luat_lv_style_set_bg_main_stop, 0},\
{"style_set_bg_grad_stop", luat_lv_style_set_bg_grad_stop, 0},\
{"style_set_bg_grad_dir", luat_lv_style_set_bg_grad_dir, 0},\
{"style_set_bg_color", luat_lv_style_set_bg_color, 0},\
{"style_set_bg_grad_color", luat_lv_style_set_bg_grad_color, 0},\
{"style_set_bg_opa", luat_lv_style_set_bg_opa, 0},\
{"style_set_border_width", luat_lv_style_set_border_width, 0},\
{"style_set_border_side", luat_lv_style_set_border_side, 0},\
{"style_set_border_blend_mode", luat_lv_style_set_border_blend_mode, 0},\
{"style_set_border_post", luat_lv_style_set_border_post, 0},\
{"style_set_border_color", luat_lv_style_set_border_color, 0},\
{"style_set_border_opa", luat_lv_style_set_border_opa, 0},\
{"style_set_outline_width", luat_lv_style_set_outline_width, 0},\
{"style_set_outline_pad", luat_lv_style_set_outline_pad, 0},\
{"style_set_outline_blend_mode", luat_lv_style_set_outline_blend_mode, 0},\
{"style_set_outline_color", luat_lv_style_set_outline_color, 0},\
{"style_set_outline_opa", luat_lv_style_set_outline_opa, 0},\
{"style_set_shadow_width", luat_lv_style_set_shadow_width, 0},\
{"style_set_shadow_ofs_x", luat_lv_style_set_shadow_ofs_x, 0},\
{"style_set_shadow_ofs_y", luat_lv_style_set_shadow_ofs_y, 0},\
{"style_set_shadow_spread", luat_lv_style_set_shadow_spread, 0},\
{"style_set_shadow_blend_mode", luat_lv_style_set_shadow_blend_mode, 0},\
{"style_set_shadow_color", luat_lv_style_set_shadow_color, 0},\
{"style_set_shadow_opa", luat_lv_style_set_shadow_opa, 0},\
{"style_set_pattern_repeat", luat_lv_style_set_pattern_repeat, 0},\
{"style_set_pattern_blend_mode", luat_lv_style_set_pattern_blend_mode, 0},\
{"style_set_pattern_recolor", luat_lv_style_set_pattern_recolor, 0},\
{"style_set_pattern_opa", luat_lv_style_set_pattern_opa, 0},\
{"style_set_pattern_recolor_opa", luat_lv_style_set_pattern_recolor_opa, 0},\
{"style_set_pattern_image", luat_lv_style_set_pattern_image, 0},\
{"style_set_value_letter_space", luat_lv_style_set_value_letter_space, 0},\
{"style_set_value_line_space", luat_lv_style_set_value_line_space, 0},\
{"style_set_value_blend_mode", luat_lv_style_set_value_blend_mode, 0},\
{"style_set_value_ofs_x", luat_lv_style_set_value_ofs_x, 0},\
{"style_set_value_ofs_y", luat_lv_style_set_value_ofs_y, 0},\
{"style_set_value_align", luat_lv_style_set_value_align, 0},\
{"style_set_value_color", luat_lv_style_set_value_color, 0},\
{"style_set_value_opa", luat_lv_style_set_value_opa, 0},\
{"style_set_value_font", luat_lv_style_set_value_font, 0},\
{"style_set_value_str", luat_lv_style_set_value_str, 0},\
{"style_set_text_letter_space", luat_lv_style_set_text_letter_space, 0},\
{"style_set_text_line_space", luat_lv_style_set_text_line_space, 0},\
{"style_set_text_decor", luat_lv_style_set_text_decor, 0},\
{"style_set_text_blend_mode", luat_lv_style_set_text_blend_mode, 0},\
{"style_set_text_color", luat_lv_style_set_text_color, 0},\
{"style_set_text_sel_color", luat_lv_style_set_text_sel_color, 0},\
{"style_set_text_sel_bg_color", luat_lv_style_set_text_sel_bg_color, 0},\
{"style_set_text_opa", luat_lv_style_set_text_opa, 0},\
{"style_set_text_font", luat_lv_style_set_text_font, 0},\
{"style_set_line_width", luat_lv_style_set_line_width, 0},\
{"style_set_line_blend_mode", luat_lv_style_set_line_blend_mode, 0},\
{"style_set_line_dash_width", luat_lv_style_set_line_dash_width, 0},\
{"style_set_line_dash_gap", luat_lv_style_set_line_dash_gap, 0},\
{"style_set_line_rounded", luat_lv_style_set_line_rounded, 0},\
{"style_set_line_color", luat_lv_style_set_line_color, 0},\
{"style_set_line_opa", luat_lv_style_set_line_opa, 0},\
{"style_set_image_blend_mode", luat_lv_style_set_image_blend_mode, 0},\
{"style_set_image_recolor", luat_lv_style_set_image_recolor, 0},\
{"style_set_image_opa", luat_lv_style_set_image_opa, 0},\
{"style_set_image_recolor_opa", luat_lv_style_set_image_recolor_opa, 0},\
{"style_set_transition_time", luat_lv_style_set_transition_time, 0},\
{"style_set_transition_delay", luat_lv_style_set_transition_delay, 0},\
{"style_set_transition_prop_1", luat_lv_style_set_transition_prop_1, 0},\
{"style_set_transition_prop_2", luat_lv_style_set_transition_prop_2, 0},\
{"style_set_transition_prop_3", luat_lv_style_set_transition_prop_3, 0},\
{"style_set_transition_prop_4", luat_lv_style_set_transition_prop_4, 0},\
{"style_set_transition_prop_5", luat_lv_style_set_transition_prop_5, 0},\
{"style_set_transition_prop_6", luat_lv_style_set_transition_prop_6, 0},\
{"style_set_scale_width", luat_lv_style_set_scale_width, 0},\
{"style_set_scale_border_width", luat_lv_style_set_scale_border_width, 0},\
{"style_set_scale_end_border_width", luat_lv_style_set_scale_end_border_width, 0},\
{"style_set_scale_end_line_width", luat_lv_style_set_scale_end_line_width, 0},\
{"style_set_scale_grad_color", luat_lv_style_set_scale_grad_color, 0},\
{"style_set_scale_end_color", luat_lv_style_set_scale_end_color, 0},\
{ "font_regular_12", NULL,       font_regular_12},\
{ "font_regular_14", NULL,       font_regular_14},\
{ "font_regular_16", NULL,       font_regular_16},\
{ "font_simsun_12", NULL,       font_simsun_12},\
{ "font_simsun_48", NULL,       font_simsun_48},
