local Config = {
    SCREEN_W = 480,
    SCREEN_H = 800,
    FRAME_MS = 100,
    BOARD_ROWS = 5,
    BOARD_COLS = 6,
    TILE_W = 44,
    TILE_H = 44,
    TILE_GAP = 4,
    BOARD_PADDING = 14,
    HUD_X = 24,
    HUD_Y = 24,
    HUD_W = 432,
    HUD_H = 100,
    BOARD_X = 38,
    BOARD_Y = 132,
    BOARD_W = 410,
    BOARD_H = 524,
    FOOTER_X = 24,
    FOOTER_Y = 668,
    FOOTER_W = 432,
    FOOTER_H = 112,
    DIALOG_X = 48,
    DIALOG_Y = 180,
    DIALOG_W = 384,
    DIALOG_H = 300,
    PATH_THICKNESS = 6,
    PATH_SHOW_MS = 280,
    HINT_SHOW_MS = 900,
    STATUS_FLASH_MS = 1300,
    MATCH_SCORE = 30,
    LEVEL_CLEAR_BONUS = 100,
    MATCH_TIME_BONUS_MS = 1800,
    MAX_SHUFFLE_RETRY = 80,
    MAX_GENERATE_RETRY = 100,
    TILE_IDS = {
        "lantern",
        "fan",
        "jade",
        "sachet",
        "coin",
        "teapot",
        "ruyi",
        "roundfan",
        "scroll",
        "seal",
        "umbrella",
        "stone",
    },
    TILE_NAMES = {
        lantern = "灯笼",
        fan = "折扇",
        jade = "玉佩",
        sachet = "香囊",
        coin = "铜钱",
        teapot = "茶壶",
        ruyi = "如意",
        roundfan = "团扇",
        scroll = "书卷",
        seal = "印章",
        umbrella = "纸伞",
        stone = "棋子",
    },
    LEVELS = {
        {
            title = "初入庭院",
            rows = 5,
            cols = 6,
            total_time_ms = 150000,
            kinds = 8,
            hints = 5,
            reshuffles = 4,
        },
        {
            title = "灯影游廊",
            rows = 6,
            cols = 6,
            total_time_ms = 156000,
            kinds = 9,
            hints = 4,
            reshuffles = 4,
        },
        {
            title = "茶席雅集",
            rows = 6,
            cols = 8,
            total_time_ms = 168000,
            kinds = 10,
            hints = 4,
            reshuffles = 3,
        },
        {
            title = "锦匣藏珍",
            rows = 8,
            cols = 8,
            total_time_ms = 180000,
            kinds = 11,
            hints = 3,
            reshuffles = 2,
        },
        {
            title = "月下满堂",
            rows = 10,
            cols = 8,
            total_time_ms = 192000,
            kinds = 12,
            hints = 2,
            reshuffles = 2,
        },
    },
}

Config.CELL_STRIDE_X = Config.TILE_W + Config.TILE_GAP
Config.CELL_STRIDE_Y = Config.TILE_H + Config.TILE_GAP

return Config