local idiomData = {
    ["怒发冲冠"] = { pinyin = "nù fà chōng guān", explain = "愤怒得头发直竖，把帽子都顶起来了，形容极端愤怒。", sentence = "他听到这个坏消息后，怒发冲冠。" },
    ["烈日炎炎"] = { pinyin = "liè rì yán yán", explain = "形容夏天阳光强烈，天气非常炎热。", sentence = "烈日炎炎的午后，大家都躲在屋里乘凉。" },
    ["自言自语"] = { pinyin = "zì yán zì yǔ", explain = "自己跟自己说话，独自低声言语。", sentence = "他一边走路，一边自言自语。" },
    ["春暖花开"] = { pinyin = "chūn nuǎn huā kāi", explain = "春天气候温暖，百花盛开，景色优美。", sentence = "春暖花开的季节，我们去公园踏青。" },
    ["笑逐颜开"] = { pinyin = "xiào zhú yán kāi", explain = "满脸笑容，十分高兴的样子。", sentence = "听到好消息，全家人都笑逐颜开。" },
    ["冰天雪地"] = { pinyin = "bīng tiān xuě dì", explain = "形容冰雪漫天盖地，非常寒冷。", sentence = "北方的冬天到处是冰天雪地。" },
    ["自由自在"] = { pinyin = "zì yóu zì zài", explain = "形容没有约束，十分安闲随意。", sentence = "小鸟在天空中自由自在地飞翔。" },
    ["惊慌失措"] = { pinyin = "jīng huāng shī cuò", explain = "由于惊慌，一下子不知怎么办才好。", sentence = "遇到危险不要惊慌失措，要冷静。" },
    ["明明白白"] = { pinyin = "míng míng bái bái", explain = "清清楚楚，明确无误。", sentence = "老师把道理讲得明明白白。" },
    ["阳春三月"] = { pinyin = "yáng chūn sān yuè", explain = "指农历三月，春天温暖的时候。", sentence = "阳春三月，万物复苏，生机勃勃。" },
    ["一心一意"] = { pinyin = "yī xīn yī yì", explain = "心思、意念专一，没有别的想法。", sentence = "学习要一心一意，不能三心二意。" },
    ["骄阳似火"] = { pinyin = "jiāo yáng sì huǒ", explain = "强烈的阳光像火一样，形容天气酷热。", sentence = "夏日骄阳似火，农民伯伯还在田里劳作。" },
    ["津津有味"] = { pinyin = "jīn jīn yǒu wèi", explain = "形容兴味特别浓厚。", sentence = "他看书看得津津有味，忘记了吃饭。" },
    ["马到成功"] = { pinyin = "mǎ dào chéng gōng", explain = "形容工作刚开始就取得成功。", sentence = "祝你考试顺利，马到成功！" },
    ["喜气洋洋"] = { pinyin = "xǐ qì yáng yáng", explain = "充满了欢喜的神色或气氛。", sentence = "过年了，家家户户喜气洋洋。" },
    ["大同小异"] = { pinyin = "dà tóng xiǎo yì", explain = "大体相同，略有差异。", sentence = "这两本书的内容大同小异。" },
    ["欢天喜地"] = { pinyin = "huān tiān xǐ dì", explain = "形容非常高兴。", sentence = "孩子们欢天喜地地过新年。" },
    ["兴高采烈"] = { pinyin = "xìng gāo cǎi liè", explain = "兴致高，精神饱满。", sentence = "大家兴高采烈地去郊游。" },
    ["心花怒放"] = { pinyin = "xīn huā nù fàng", explain = "心里高兴得像花儿盛开一样。", sentence = "拿到奖状，他心花怒放。" },
    ["草长莺飞"] = { pinyin = "cǎo zhǎng yīng fēi", explain = "形容江南暮春的景色。", sentence = "春天来了，草长莺飞。" },
    ["万物复苏"] = { pinyin = "wàn wù fù sū", explain = "世间万物都恢复了生机。", sentence = "春天到了，万物复苏。" },
    ["开开心心"] = { pinyin = "kāi kāi xīn xīn", explain = "心情愉快舒畅。", sentence = "希望大家每天都开开心心。" },
    ["干干净净"] = { pinyin = "gān gān jìng jìng", explain = "没有污垢、尘土、杂质。", sentence = "他把房间打扫得干干净净。" },
    ["狐假虎威"] = { pinyin = "hú jiǎ hǔ wēi", explain = "比喻依仗别人的势力欺压人。", sentence = "他总是狐假虎威欺负同学。" },
    ["守株待兔"] = { pinyin = "shǒu zhū dài tù", explain = "比喻死守狭隘经验，不知变通。", sentence = "我们不能守株待兔等机会。" },
    ["火冒三丈"] = { pinyin = "huǒ mào sān zhàng", explain = "形容愤怒到极点。", sentence = "看到他犯错，爸爸火冒三丈。" },
    ["秋高气爽"] = { pinyin = "qiū gāo qì shuǎng", explain = "形容秋季晴空万里，天气清爽。", sentence = "秋高气爽，适合爬山。" },
    ["三心二意"] = { pinyin = "sān xīn èr yì", explain = "又想这样又想那样，犹豫不定。", sentence = "做事不能三心二意。" },
    ["井底之蛙"] = { pinyin = "jǐng dǐ zhī wā", explain = "比喻见识狭窄的人。", sentence = "我们要多学习，不做井底之蛙。" },
    ["从容不迫"] = { pinyin = "cóng róng bù pò", explain = "不慌不忙，沉着镇定。", sentence = "他上台演讲从容不迫。" },
    ["半信半疑"] = { pinyin = "bàn xìn bàn yí", explain = "有点相信，又有点怀疑。", sentence = "他对这个消息半信半疑。" },
    ["怒气冲冲"] = { pinyin = "nù qì chōng chōng", explain = "形容人盛怒的样子。", sentence = "他怒气冲冲地走进了房间。" },
    ["暴跳如雷"] = { pinyin = "bào tiào rú léi", explain = "形容大怒的样子。", sentence = "听到结果，他暴跳如雷。" },
    ["汗流浃背"] = { pinyin = "hàn liú jiā bèi", explain = "形容出汗很多，非常劳累。", sentence = "运动过后，大家汗流浃背。" },
    ["刻舟求剑"] = { pinyin = "kè zhōu qiú jiàn", explain = "比喻办事死板，不懂变通。", sentence = "做事不能刻舟求剑，要灵活应对。" },
    ["天高云淡"] = { pinyin = "tiān gāo yún dàn", explain = "天气晴朗，天空云少而淡。", sentence = "秋日天高云淡，非常舒适。" },
    ["硕果累累"] = { pinyin = "shuò guǒ léi léi", explain = "秋天丰收，果实很多。", sentence = "果园里硕果累累，一片丰收。" },
    ["七上八下"] = { pinyin = "qī shàng bā xià", explain = "形容心里慌乱不安。", sentence = "等待结果时，他心里七上八下。" },
    ["寒风刺骨"] = { pinyin = "hán fēng cì gǔ", explain = "天气寒冷，寒风像刺进骨头。", sentence = "冬日寒风刺骨，出门要多穿衣。" },
    ["大雪纷飞"] = { pinyin = "dà xuě fēn fēi", explain = "雪花大量飘落，雪很大。", sentence = "窗外大雪纷飞，屋内温暖舒适。" },
    ["手忙脚乱"] = { pinyin = "shǒu máng jiǎo luàn", explain = "形容做事慌张，没有条理。", sentence = "快迟到了，他手忙脚乱收拾东西。" },
    ["心平气和"] = { pinyin = "xīn píng qì hé", explain = "心里平静，态度温和。", sentence = "遇到问题要心平气和解决。" },
    ["泰然自若"] = { pinyin = "tài rán zì ruò", explain = "在紧急情况下仍镇定如常。", sentence = "面对困难，他泰然自若。" },
    ["专心致志"] = { pinyin = "zhuān xīn zhì zhì", explain = "一心一意，集中精神。", sentence = "上课时要专心致志听讲。" },
    ["全神贯注"] = { pinyin = "quán shén guàn zhù", explain = "全部精神集中在一点。", sentence = "他全神贯注地思考问题。" },
    ["一尘不染"] = { pinyin = "yī chén bù rǎn", explain = "环境非常清洁，一点灰尘都没有。", sentence = "妈妈把房间打扫得一尘不染。" },
    ["凯旋而归"] = { pinyin = "kǎi xuán ér guī", explain = "打仗胜利后归来。", sentence = "战士们凯旋而归，受到欢迎。" },
    ["滔滔不绝"] = { pinyin = "tāo tāo bù jué", explain = "说话连续不断，非常流利。", sentence = "他讲起故事来滔滔不绝。" },
    ["窃窃私语"] = { pinyin = "qiè qiè sī yǔ", explain = "背着人小声说话。", sentence = "上课时不要窃窃私语。" },
    ["一目了然"] = { pinyin = "yī mù liǎo rán", explain = "一眼就看得很清楚。", sentence = "图表内容一目了然，非常清晰。" },
    ["无拘无束"] = { pinyin = "wú jū wú shù", explain = "自由自在，没有约束。", sentence = "孩子们在草地上无拘无束地奔跑。" },
    ["随心所欲"] = { pinyin = "suí xīn suǒ yù", explain = "一切都由着自己的心意。", sentence = "在规则内可以随心所欲。" },
    ["清清楚楚"] = { pinyin = "qīng qīng chǔ chǔ", explain = "清晰明白，不模糊。", sentence = "老师的话我听得清清楚楚。" },
    ["整洁干净"] = { pinyin = "zhěng jié gān jìng", explain = "整齐清洁，干净卫生。", sentence = "桌面保持整洁干净。" },
    ["酷暑难当"] = { pinyin = "kù shǔ nán dāng", explain = "夏天酷热，难以忍受。", sentence = "盛夏酷暑难当，大家都不想出门。" },
    ["忐忑不安"] = { pinyin = "tǎn tè bù ān", explain = "心神不定，心神不安。", sentence = "等待成绩时，他忐忑不安。" }
}

local findQuestions = {
    -- 答案 = 1 共 25 题
    { category = "哪项不是形容高兴的？", idioms = {"怒发冲冠","兴高采烈","欢天喜地","心花怒放"}, answer = 1, reason = "怒发冲冠形容生气", wrong = "怒发冲冠" },
    { category = "哪项不是描写春天的？", idioms = {"烈日炎炎","春暖花开","草长莺飞","万物复苏"}, answer = 1, reason = "烈日炎炎描写夏天", wrong = "烈日炎炎" },
    { category = "哪项不是AABB结构？", idioms = {"自言自语","开开心心","明明白白","干干净净"}, answer = 1, reason = "自言自语是ABAC结构", wrong = "自言自语" },
    { category = "哪项不含动物？", idioms = {"春暖花开","狐假虎威","马到成功","守株待兔"}, answer = 1, reason = "春暖花开不含动物", wrong = "春暖花开" },
    { category = "哪项不是形容生气？", idioms = {"笑逐颜开","火冒三丈","怒发冲冠","暴跳如雷"}, answer = 1, reason = "笑逐颜开形容开心", wrong = "笑逐颜开" },
    { category = "哪项不是描写秋天？", idioms = {"冰天雪地","秋高气爽","天高云淡","硕果累累"}, answer = 1, reason = "冰天雪地描写冬天", wrong = "冰天雪地" },
    { category = "哪项不含数字？", idioms = {"自由自在","一心一意","三心二意","七上八下"}, answer = 1, reason = "自由自在不含数字", wrong = "自由自在" },
    { category = "哪项不是寓言成语？", idioms = {"春暖花开","守株待兔","井底之蛙","刻舟求剑"}, answer = 1, reason = "春暖花开非寓言", wrong = "春暖花开" },
    { category = "哪项不是形容淡定？", idioms = {"惊慌失措","从容不迫","心平气和","泰然自若"}, answer = 1, reason = "惊慌失措形容慌张", wrong = "惊慌失措" },
    { category = "哪项不是描写夏天？", idioms = {"春暖花开","骄阳似火","烈日炎炎","酷暑难当"}, answer = 1, reason = "春暖花开描写春天", wrong = "春暖花开" },
    { category = "哪项不是形容开心？", idioms = {"火冒三丈","喜气洋洋","兴高采烈","心花怒放"}, answer = 1, reason = "火冒三丈形容生气", wrong = "火冒三丈" },
    { category = "哪项不是描写冬天？", idioms = {"阳春三月","冰天雪地","寒风刺骨","大雪纷飞"}, answer = 1, reason = "阳春三月描写春天", wrong = "阳春三月" },
    { category = "哪项不是ABAC结构？", idioms = {"明明白白","自言自语","一心一意","自由自在"}, answer = 1, reason = "明明白白是AABB结构", wrong = "明明白白" },
    { category = "哪项不含天气含义？", idioms = {"守株待兔","烈日炎炎","秋高气爽","冰天雪地"}, answer = 1, reason = "守株待兔是寓言成语", wrong = "守株待兔" },
    { category = "哪项不是形容慌张？", idioms = {"从容不迫","惊慌失措","手忙脚乱","忐忑不安"}, answer = 1, reason = "从容不迫形容淡定", wrong = "从容不迫" },
    { category = "哪项不是形容专注？", idioms = {"三心二意","一心一意","专心致志","全神贯注"}, answer = 1, reason = "三心二意形容不专心", wrong = "三心二意" },
    { category = "哪项不是描写景色？", idioms = {"津津有味","草长莺飞","春暖花开","秋高气爽"}, answer = 1, reason = "津津有味形容兴趣", wrong = "津津有味" },
    { category = "哪项不是AABB式？", idioms = {"兴高采烈","开开心心","明明白白","干干净净"}, answer = 1, reason = "兴高采烈非AABB结构", wrong = "兴高采烈" },
    { category = "哪项不是寓言成语？", idioms = {"喜气洋洋","井底之蛙","狐假虎威","刻舟求剑"}, answer = 1, reason = "喜气洋洋形容心情", wrong = "喜气洋洋" },
    { category = "哪项不是形容炎热？", idioms = {"冰天雪地","骄阳似火","烈日炎炎","酷暑难当"}, answer = 1, reason = "冰天雪地形容寒冷", wrong = "冰天雪地" },
    { category = "哪项不是形容情绪？", idioms = {"春暖花开","心花怒放","怒发冲冠","喜气洋洋"}, answer = 1, reason = "春暖花开描写季节", wrong = "春暖花开" },
    { category = "哪项不是形容说话？", idioms = {"冰天雪地","自言自语","滔滔不绝","窃窃私语"}, answer = 1, reason = "冰天雪地描写冬天", wrong = "冰天雪地" },
    { category = "哪项不是形容干净？", idioms = {"明明白白","干干净净","一尘不染","整洁干净"}, answer = 1, reason = "明明白白形容清晰", wrong = "明明白白" },
    { category = "哪项不含季节？", idioms = {"一心一意","春暖花开","秋高气爽","冰天雪地"}, answer = 1, reason = "一心一意不含季节", wrong = "一心一意" },
    { category = "哪项不是形容成功？", idioms = {"惊慌失措","马到成功","凯旋而归","旗开得胜"}, answer = 1, reason = "惊慌失措形容慌张", wrong = "惊慌失措" },

    -- 答案 = 2 共 25 题
    { category = "哪项不是形容高兴的？", idioms = {"兴高采烈","怒发冲冠","欢天喜地","心花怒放"}, answer = 2, reason = "怒发冲冠形容生气", wrong = "怒发冲冠" },
    { category = "哪项不是描写春天的？", idioms = {"春暖花开","草长莺飞","烈日炎炎","万物复苏"}, answer = 3, reason = "烈日炎炎描写夏天", wrong = "烈日炎炎" },
    { category = "哪项不是AABB结构？", idioms = {"开开心心","自言自语","明明白白","干干净净"}, answer = 2, reason = "自言自语是ABAC结构", wrong = "自言自语" },
    { category = "哪项不含动物？", idioms = {"狐假虎威","春暖花开","马到成功","守株待兔"}, answer = 2, reason = "春暖花开不含动物", wrong = "春暖花开" },
    { category = "哪项不是形容生气？", idioms = {"火冒三丈","笑逐颜开","怒发冲冠","暴跳如雷"}, answer = 2, reason = "笑逐颜开形容开心", wrong = "笑逐颜开" },
    { category = "哪项不是描写秋天？", idioms = {"秋高气爽","天高云淡","冰天雪地","硕果累累"}, answer = 3, reason = "冰天雪地描写冬天", wrong = "冰天雪地" },
    { category = "哪项不含数字？", idioms = {"一心一意","自由自在","三心二意","七上八下"}, answer = 2, reason = "自由自在不含数字", wrong = "自由自在" },
    { category = "哪项不是寓言成语？", idioms = {"守株待兔","春暖花开","井底之蛙","刻舟求剑"}, answer = 2, reason = "春暖花开非寓言", wrong = "春暖花开" },
    { category = "哪项不是形容淡定？", idioms = {"从容不迫","惊慌失措","心平气和","泰然自若"}, answer = 2, reason = "惊慌失措形容慌张", wrong = "惊慌失措" },
    { category = "哪项不是描写夏天？", idioms = {"骄阳似火","春暖花开","烈日炎炎","酷暑难当"}, answer = 2, reason = "春暖花开描写春天", wrong = "春暖花开" },
    { category = "哪项不是形容开心？", idioms = {"喜气洋洋","火冒三丈","兴高采烈","心花怒放"}, answer = 2, reason = "火冒三丈形容生气", wrong = "火冒三丈" },
    { category = "哪项不是描写冬天？", idioms = {"冰天雪地","阳春三月","寒风刺骨","大雪纷飞"}, answer = 2, reason = "阳春三月描写春天", wrong = "阳春三月" },
    { category = "哪项不是ABAC结构？", idioms = {"自言自语","明明白白","一心一意","自由自在"}, answer = 2, reason = "明明白白是AABB结构", wrong = "明明白白" },
    { category = "哪项不含天气含义？", idioms = {"烈日炎炎","守株待兔","秋高气爽","冰天雪地"}, answer = 2, reason = "守株待兔是寓言成语", wrong = "守株待兔" },
    { category = "哪项不是形容慌张？", idioms = {"惊慌失措","从容不迫","手忙脚乱","忐忑不安"}, answer = 2, reason = "从容不迫形容淡定", wrong = "从容不迫" },
    { category = "哪项不是形容专注？", idioms = {"一心一意","三心二意","专心致志","全神贯注"}, answer = 2, reason = "三心二意形容不专心", wrong = "三心二意" },
    { category = "哪项不是描写景色？", idioms = {"草长莺飞","津津有味","春暖花开","秋高气爽"}, answer = 2, reason = "津津有味形容兴趣", wrong = "津津有味" },
    { category = "哪项不是AABB式？", idioms = {"开开心心","兴高采烈","明明白白","干干净净"}, answer = 2, reason = "兴高采烈非AABB结构", wrong = "兴高采烈" },
    { category = "哪项不是寓言成语？", idioms = {"井底之蛙","喜气洋洋","狐假虎威","刻舟求剑"}, answer = 2, reason = "喜气洋洋形容心情", wrong = "喜气洋洋" },
    { category = "哪项不是形容炎热？", idioms = {"骄阳似火","冰天雪地","烈日炎炎","酷暑难当"}, answer = 2, reason = "冰天雪地形容寒冷", wrong = "冰天雪地" },
    { category = "哪项不是形容情绪？", idioms = {"心花怒放","春暖花开","怒发冲冠","喜气洋洋"}, answer = 2, reason = "春暖花开描写季节", wrong = "春暖花开" },
    { category = "哪项不是形容说话？", idioms = {"自言自语","冰天雪地","滔滔不绝","窃窃私语"}, answer = 2, reason = "冰天雪地描写冬天", wrong = "冰天雪地" },
    { category = "哪项不是形容干净？", idioms = {"干干净净","明明白白","一尘不染","整洁干净"}, answer = 2, reason = "明明白白形容清晰", wrong = "明明白白" },
    { category = "哪项不含季节？", idioms = {"春暖花开","一心一意","秋高气爽","冰天雪地"}, answer = 2, reason = "一心一意不含季节", wrong = "一心一意" },
    { category = "哪项不是形容成功？", idioms = {"马到成功","惊慌失措","凯旋而归","旗开得胜"}, answer = 2, reason = "惊慌失措形容慌张", wrong = "惊慌失措" },

    -- 答案 = 3 共 25 题
    { category = "哪项不是形容高兴的？", idioms = {"欢天喜地","兴高采烈","怒发冲冠","心花怒放"}, answer = 3, reason = "怒发冲冠形容生气", wrong = "怒发冲冠" },
    { category = "哪项不是描写春天的？", idioms = {"春暖花开","烈日炎炎","草长莺飞","万物复苏"}, answer = 2, reason = "烈日炎炎描写夏天", wrong = "烈日炎炎" },
    { category = "哪项不是AABB结构？", idioms = {"开开心心","明明白白","自言自语","干干净净"}, answer = 3, reason = "自言自语是ABAC结构", wrong = "自言自语" },
    { category = "哪项不含动物？", idioms = {"狐假虎威","马到成功","守株待兔","春暖花开"}, answer = 4, reason = "春暖花开不含动物", wrong = "春暖花开" },
    { category = "哪项不是形容生气？", idioms = {"火冒三丈","怒气冲冲","笑逐颜开","暴跳如雷"}, answer = 3, reason = "笑逐颜开形容开心", wrong = "笑逐颜开" },
    { category = "哪项不是描写秋天？", idioms = {"秋高气爽","冰天雪地","天高云淡","硕果累累"}, answer = 2, reason = "冰天雪地描写冬天", wrong = "冰天雪地" },
    { category = "哪项不含数字？", idioms = {"一心一意","三心二意","自由自在","七上八下"}, answer = 3, reason = "自由自在不含数字", wrong = "自由自在" },
    { category = "哪项不是寓言成语？", idioms = {"刻舟求剑","守株待兔","井底之蛙","春暖花开"}, answer = 4, reason = "春暖花开非寓言", wrong = "春暖花开" },
    { category = "哪项不是形容淡定？", idioms = {"心平气和","从容不迫","惊慌失措","泰然自若"}, answer = 3, reason = "惊慌失措形容慌张", wrong = "惊慌失措" },
    { category = "哪项不是描写夏天？", idioms = {"骄阳似火","烈日炎炎","春暖花开","汗流浃背"}, answer = 3, reason = "春暖花开描写春天", wrong = "春暖花开" },
    { category = "哪项不是形容开心？", idioms = {"兴高采烈","喜气洋洋","火冒三丈","心花怒放"}, answer = 3, reason = "火冒三丈形容生气", wrong = "火冒三丈" },
    { category = "哪项不是描写冬天？", idioms = {"冰天雪地","寒风刺骨","阳春三月","大雪纷飞"}, answer = 3, reason = "阳春三月描写春天", wrong = "阳春三月" },
    { category = "哪项不是ABAC结构？", idioms = {"开开心心","一心一意","明明白白","自由自在"}, answer = 3, reason = "明明白白是AABB结构", wrong = "明明白白" },
    { category = "哪项不含天气含义？", idioms = {"秋高气爽","烈日炎炎","守株待兔","冰天雪地"}, answer = 3, reason = "守株待兔是寓言成语", wrong = "守株待兔" },
    { category = "哪项不是形容慌张？", idioms = {"手忙脚乱","惊慌失措","从容不迫","忐忑不安"}, answer = 3, reason = "从容不迫形容淡定", wrong = "从容不迫" },
    { category = "哪项不是形容专注？", idioms = {"专心致志","一心一意","三心二意","全神贯注"}, answer = 3, reason = "三心二意形容不专心", wrong = "三心二意" },
    { category = "哪项不是描写景色？", idioms = {"春暖花开","草长莺飞","津津有味","秋高气爽"}, answer = 3, reason = "津津有味形容兴趣", wrong = "津津有味" },
    { category = "哪项不是AABB式？", idioms = {"明明白白","开开心心","兴高采烈","干干净净"}, answer = 3, reason = "兴高采烈非AABB结构", wrong = "兴高采烈" },
    { category = "哪项不是寓言成语？", idioms = {"狐假虎威","井底之蛙","喜气洋洋","刻舟求剑"}, answer = 3, reason = "喜气洋洋形容心情", wrong = "喜气洋洋" },
    { category = "哪项不是形容炎热？", idioms = {"烈日炎炎","骄阳似火","冰天雪地","酷暑难当"}, answer = 3, reason = "冰天雪地形容寒冷", wrong = "冰天雪地" },
    { category = "哪项不是形容情绪？", idioms = {"怒发冲冠","心花怒放","春暖花开","喜气洋洋"}, answer = 3, reason = "春暖花开描写季节", wrong = "春暖花开" },
    { category = "哪项不是形容说话？", idioms = {"滔滔不绝","自言自语","冰天雪地","窃窃私语"}, answer = 3, reason = "冰天雪地描写冬天", wrong = "冰天雪地" },
    { category = "哪项不是形容干净？", idioms = {"一尘不染","干干净净","明明白白","整洁干净"}, answer = 3, reason = "明明白白形容清晰", wrong = "明明白白" },
    { category = "哪项不含季节？", idioms = {"秋高气爽","春暖花开","一心一意","冰天雪地"}, answer = 3, reason = "一心一意不含季节", wrong = "一心一意" },
    { category = "哪项不是形容成功？", idioms = {"凯旋而归","马到成功","惊慌失措","旗开得胜"}, answer = 3, reason = "惊慌失措形容慌张", wrong = "惊慌失措" },

    -- 答案 = 4 共 25 题
    { category = "哪项不是形容高兴的？", idioms = {"兴高采烈","欢天喜地","心花怒放","怒发冲冠"}, answer = 4, reason = "怒发冲冠形容生气", wrong = "怒发冲冠" },
    { category = "哪项不是描写春天的？", idioms = {"草长莺飞","春暖花开","万物复苏","烈日炎炎"}, answer = 4, reason = "烈日炎炎描写夏天", wrong = "烈日炎炎" },
    { category = "哪项不是AABB结构？", idioms = {"明明白白","开开心心","干干净净","自言自语"}, answer = 4, reason = "自言自语是ABAC结构", wrong = "自言自语" },
    { category = "哪项不含动物？", idioms = {"马到成功","狐假虎威","守株待兔","春暖花开"}, answer = 4, reason = "春暖花开不含动物", wrong = "春暖花开" },
    { category = "哪项不是形容生气？", idioms = {"怒发冲冠","火冒三丈","暴跳如雷","笑逐颜开"}, answer = 4, reason = "笑逐颜开形容开心", wrong = "笑逐颜开" },
    { category = "哪项不是描写秋天？", idioms = {"天高云淡","秋高气爽","硕果累累","冰天雪地"}, answer = 4, reason = "冰天雪地描写冬天", wrong = "冰天雪地" },
    { category = "哪项不含数字？", idioms = {"三心二意","一心一意","七上八下","自由自在"}, answer = 4, reason = "自由自在不含数字", wrong = "自由自在" },
    { category = "哪项不是寓言成语？", idioms = {"井底之蛙","刻舟求剑","守株待兔","春暖花开"}, answer = 4, reason = "春暖花开非寓言", wrong = "春暖花开" },
    { category = "哪项不是形容淡定？", idioms = {"泰然自若","心平气和","从容不迫","惊慌失措"}, answer = 4, reason = "惊慌失措形容慌张", wrong = "惊慌失措" },
    { category = "哪项不是描写夏天？", idioms = {"烈日炎炎","骄阳似火","酷暑难当","春暖花开"}, answer = 4, reason = "春暖花开描写春天", wrong = "春暖花开" },
    { category = "哪项不是形容开心？", idioms = {"心花怒放","兴高采烈","喜气洋洋","火冒三丈"}, answer = 4, reason = "火冒三丈形容生气", wrong = "火冒三丈" },
    { category = "哪项不是描写冬天？", idioms = {"寒风刺骨","冰天雪地","大雪纷飞","阳春三月"}, answer = 4, reason = "阳春三月描写春天", wrong = "阳春三月" },
    { category = "哪项不是ABAC结构？", idioms = {"一心一意","自由自在","自言自语","明明白白"}, answer = 4, reason = "明明白白是AABB结构", wrong = "明明白白" },
    { category = "哪项不含天气含义？", idioms = {"冰天雪地","秋高气爽","烈日炎炎","守株待兔"}, answer = 4, reason = "守株待兔是寓言成语", wrong = "守株待兔" },
    { category = "哪项不是形容慌张？", idioms = {"忐忑不安","手忙脚乱","惊慌失措","从容不迫"}, answer = 4, reason = "从容不迫形容淡定", wrong = "从容不迫" },
    { category = "哪项不是形容专注？", idioms = {"全神贯注","专心致志","一心一意","三心二意"}, answer = 4, reason = "三心二意形容不专心", wrong = "三心二意" },
    { category = "哪项不是描写景色？", idioms = {"秋高气爽","春暖花开","草长莺飞","津津有味"}, answer = 4, reason = "津津有味形容兴趣", wrong = "津津有味" },
    { category = "哪项不是AABB式？", idioms = {"干干净净","明明白白","开开心心","兴高采烈"}, answer = 4, reason = "兴高采烈非AABB结构", wrong = "兴高采烈" },
    { category = "哪项不是寓言成语？", idioms = {"刻舟求剑","狐假虎威","井底之蛙","喜气洋洋"}, answer = 4, reason = "喜气洋洋形容心情", wrong = "喜气洋洋" },
    { category = "哪项不是形容炎热？", idioms = {"酷暑难当","烈日炎炎","骄阳似火","冰天雪地"}, answer = 4, reason = "冰天雪地形容寒冷", wrong = "冰天雪地" },
    { category = "哪项不是形容情绪？", idioms = {"喜气洋洋","怒发冲冠","心花怒放","春暖花开"}, answer = 4, reason = "春暖花开描写季节", wrong = "春暖花开" },
    { category = "哪项不是形容说话？", idioms = {"窃窃私语","滔滔不绝","自言自语","冰天雪地"}, answer = 4, reason = "冰天雪地描写冬天", wrong = "冰天雪地" },
    { category = "哪项不是形容干净？", idioms = {"整洁干净","一尘不染","干干净净","明明白白"}, answer = 4, reason = "明明白白形容清晰", wrong = "明明白白" },
    { category = "哪项不含季节？", idioms = {"冰天雪地","秋高气爽","春暖花开","一心一意"}, answer = 4, reason = "一心一意不含季节", wrong = "一心一意" },
    { category = "哪项不是形容成功？", idioms = {"旗开得胜","凯旋而归","马到成功","惊慌失措"}, answer = 4, reason = "惊慌失措形容慌张", wrong = "惊慌失措" }
}


return {
    idiomData = idiomData,
    findQuestions = findQuestions
}
