
#ifndef LUAT_CONF_BSP
#define LUAT_CONF_BSP

#define LUAT_BSP_VERSION "V0001"

// 启用64位虚拟机
// #define LUAT_CONF_VM_64bit

//#define LUAT_CONF_LUASTATE_NOT_STATIC

#define LUAT_CONF_LAUX_BUFFSIZE 1024

// #define LUA_COMPAT_BITLIB 1

//#define LUAT_CONF_DISABLE_ROTABLE

#define LUAT_USE_FS_VFS 1

#define LUAT_USE_VFS_INLINE_LIB 1

//#define LUAT_MEMORY_OPT_G_FUNCS 1

#define LUAT_USE_LOG_ASYNC_THREAD 0

#define LUAT_USE_LVGL 1
#define USE_GTK 1

//#define LUAT_FORCE_WIN32 1

#define LV_FONT_OPPOSANS_M_8
#define LV_FONT_OPPOSANS_M_10
#define LV_FONT_OPPOSANS_M_12
#define LV_FONT_OPPOSANS_M_14
#define LV_FONT_OPPOSANS_M_16
#define LV_FONT_OPPOSANS_M_18
#define LV_FONT_OPPOSANS_M_20
#define LV_FONT_OPPOSANS_M_22
#define USE_LVGL_SIMSUN_48

#endif
