#ifndef __AIRTALK_H__
#define __AIRTALK_H__

enum
{
	AIRTALK_EVENT_AMR_ENCODE_ONCE = 1,
	AIRTALK_EVENT_AMR_DECODE_ONCE,
	AIRTALK_EVENT_AMR_START,			//audio处理流程开始
	AIRTALK_EVENT_AMR_RECORD_STOP,		//录音停止
	AIRTALK_EVENT_AMR_PLAY_STOP,		//播放停止

	AIRTALK_EVENT_MQTT_MSG,				//MQTT除了上下行数据外其他消息
	AIRTALK_EVENT_MQTT_DOWNLINK_DATA,	//MQTT下行数据，需要解码播放
	AIRTALK_EVENT_MQTT_UPLINK_DATA,		//MQTT上行数据，已经编码过了
	AIRTALK_EVENT_MQTT_UPLINK_END,
	AIRTALK_EVENT_MQTT_FORCE_SYNC,		//重新同步数据
	AIRTALK_EVENT_MQTT_FORCE_STOP,		//停止对讲流程

};
#endif
