/*
 * luat_airtalk.h
 *
 *  Created on: 2025年6月26日
 *      Author: Administrator
 */

#ifndef AIRTALK_INCLUDE_LUAT_AIRTALK_H_
#define AIRTALK_INCLUDE_LUAT_AIRTALK_H_
enum
{
	LUAT_AIRTALK_PROTOCOL_MQTT,

	LUAT_AIRTALK_SPEECH_MODE_PERSON = 0,
	LUAT_AIRTALK_SPEECH_MODE_GROUP_SPEAKER,
	LUAT_AIRTALK_SPEECH_MODE_GROUP_LISTENER,
	LUAT_AIRTALK_SPEECH_MODE_ROOM,

	LUAT_AIRTALK_CB_OFF_LINE = 0,
	LUAT_AIRTALK_CB_ON_LINE_IDLE,
	LUAT_AIRTALK_CB_PLAY_START,
	LUAT_AIRTALK_CB_PLAY_END,
	LUAT_AIRTALK_CB_RECORD_START,
	LUAT_AIRTALK_CB_RECORD_END,
	LUAT_AIRTALK_CB_AUDIO_START,
	LUAT_AIRTALK_CB_AUDIO_END,
	LUAT_AIRTALK_CB_ERROR,

	LUAT_AIRTALL_ERR_LONG_TIME_NO_DATA = 0,
};
void luat_airtalk_callback(uint32_t event, void *param, uint32_t param_len);

#endif /* AIRTALK_INCLUDE_LUAT_AIRTALK_H_ */
