
AIRTALK_TASK_NAME = "airtalk_task"
USER_TASK_NAME = "user"

MSG_CONNECT_ON_IND = 0
MSG_CONNECT_OFF_IND = 1
MSG_AUTH_IND = 2
MSG_SPEECH_ON_IND = 3
MSG_SPEECH_OFF_IND = 4
MSG_SPEECH_CONNECT_TO = 5

MSG_PERSON_SPEECH_TEST_START = 20
MSG_GROUP_SPEECH_TEST_START = 21
MSG_SPEECH_STOP_TEST_END = 22


MSG_READY = 10
MSG_NOT_READY = 11
MSG_KEY_PRESS = 12

SP_T_NO_READY = 0           -- 离线状态无法对讲
SP_T_IDLE = 1               -- 对讲空闲状态
SP_T_CONNECTING = 2         -- 主动发起对讲
SP_T_CONNECTED = 3          -- 对讲中


SUCC = "success"