

includes("c_common")
includes("crypto")
includes("fs")
includes("mempool")
includes("serialization")
includes("tools")
includes("ui")
includes("mbedtls")
includes("peripheral")
includes("shell")
includes("network")

target("luatos_components")
    set_kind("static")
    add_deps("c_common")
    add_deps("crypto")
    add_deps("fs")
    add_deps("mempool")
    add_deps("serialization")
    add_deps("tools")
    add_deps("ui")
    add_deps("mbedtls")
    add_deps("peripheral")
    add_deps("shell")
    add_deps("network")
target_end()
