includes("lcd")
includes("u8g2")
includes("eink")
includes("lvgl")
includes("ufont")
includes("gtfont")
includes("luatfonts")
includes("qrcode")
includes("tjpgd")

--add_deps("u8g2")
target("ui")
    set_kind("static")
    add_deps("lcd")
    add_deps("u8g2")
    add_deps("eink")
    add_deps("lvgl")
    add_deps("ufont")
    add_deps("gtfont")
    add_deps("luatfonts")
    add_deps("qrcode")
    add_deps("tjpgd")

target_end()