/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "drv_gpio.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(drv_gpio_GpioResult, drv_gpio_GpioResult, AUTO)


PB_BIND(drv_gpio_GpioSetupRequest, drv_gpio_GpioSetupRequest, AUTO)


PB_BIND(drv_gpio_GpioSetupResponse, drv_gpio_GpioSetupResponse, AUTO)


PB_BIND(drv_gpio_GpioCloseRequest, drv_gpio_GpioCloseRequest, AUTO)


PB_BIND(drv_gpio_GpioCloseResponse, drv_gpio_GpioCloseResponse, AUTO)


PB_BIND(drv_gpio_GpioWriteRequest, drv_gpio_GpioWriteRequest, AUTO)


PB_BIND(drv_gpio_GpioWriteResponse, drv_gpio_GpioWriteResponse, AUTO)


PB_BIND(drv_gpio_GpioReadRequest, drv_gpio_GpioReadRequest, AUTO)


PB_BIND(drv_gpio_GpioReadResponse, drv_gpio_GpioReadResponse, AUTO)


PB_BIND(drv_gpio_GpioSetPullRequest, drv_gpio_GpioSetPullRequest, AUTO)


PB_BIND(drv_gpio_GpioSetPullResponse, drv_gpio_GpioSetPullResponse, AUTO)


PB_BIND(drv_gpio_GpioSetIrqRequest, drv_gpio_GpioSetIrqRequest, AUTO)


PB_BIND(drv_gpio_GpioSetIrqResponse, drv_gpio_GpioSetIrqResponse, AUTO)


PB_BIND(drv_gpio_GpioIrqEvent, drv_gpio_GpioIrqEvent, AUTO)


PB_BIND(drv_gpio_GpioRpcRequest, drv_gpio_GpioRpcRequest, AUTO)


PB_BIND(drv_gpio_GpioRpcResponse, drv_gpio_GpioRpcResponse, 2)













