/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "drv_mobile.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(drv_mobile_MobileResult, drv_mobile_MobileResult, AUTO)


PB_BIND(drv_mobile_MobileSimIdentityStatusRequest, drv_mobile_MobileSimIdentityStatusRequest, AUTO)


PB_BIND(drv_mobile_MobileSimIdentityStatus, drv_mobile_MobileSimIdentityStatus, AUTO)


PB_BIND(drv_mobile_MobileSimIdentityStatusResponse, drv_mobile_MobileSimIdentityStatusResponse, AUTO)


PB_BIND(drv_mobile_MobileGlobalStatusRequest, drv_mobile_MobileGlobalStatusRequest, AUTO)


PB_BIND(drv_mobile_MobileGlobalStatus, drv_mobile_MobileGlobalStatus, AUTO)


PB_BIND(drv_mobile_MobileGlobalStatusResponse, drv_mobile_MobileGlobalStatusResponse, AUTO)


PB_BIND(drv_mobile_MobileSignalRequest, drv_mobile_MobileSignalRequest, AUTO)


PB_BIND(drv_mobile_MobileGwSignalInfo, drv_mobile_MobileGwSignalInfo, AUTO)


PB_BIND(drv_mobile_MobileLteSignalInfo, drv_mobile_MobileLteSignalInfo, AUTO)


PB_BIND(drv_mobile_MobileSignalInfo, drv_mobile_MobileSignalInfo, AUTO)


PB_BIND(drv_mobile_MobileSignalResponse, drv_mobile_MobileSignalResponse, AUTO)


PB_BIND(drv_mobile_MobileSyncCellInfoRequest, drv_mobile_MobileSyncCellInfoRequest, AUTO)


PB_BIND(drv_mobile_MobileCellScanRequest, drv_mobile_MobileCellScanRequest, AUTO)


PB_BIND(drv_mobile_MobileGsmServiceCellInfo, drv_mobile_MobileGsmServiceCellInfo, AUTO)


PB_BIND(drv_mobile_MobileGsmCellInfo, drv_mobile_MobileGsmCellInfo, AUTO)


PB_BIND(drv_mobile_MobileLteServiceCellInfo, drv_mobile_MobileLteServiceCellInfo, AUTO)


PB_BIND(drv_mobile_MobileLteCellInfo, drv_mobile_MobileLteCellInfo, AUTO)


PB_BIND(drv_mobile_MobileCellInfo, drv_mobile_MobileCellInfo, 2)


PB_BIND(drv_mobile_MobileSyncCellInfoResponse, drv_mobile_MobileSyncCellInfoResponse, 2)


PB_BIND(drv_mobile_MobileCellScanResponse, drv_mobile_MobileCellScanResponse, AUTO)


PB_BIND(drv_mobile_MobileScellExternInfoRequest, drv_mobile_MobileScellExternInfoRequest, AUTO)


PB_BIND(drv_mobile_MobileScellExternInfo, drv_mobile_MobileScellExternInfo, AUTO)


PB_BIND(drv_mobile_MobileScellExternInfoResponse, drv_mobile_MobileScellExternInfoResponse, AUTO)


PB_BIND(drv_mobile_MobileRpcRequest, drv_mobile_MobileRpcRequest, AUTO)


PB_BIND(drv_mobile_MobileRpcResponse, drv_mobile_MobileRpcResponse, 2)


PB_BIND(drv_mobile_MobileCellScanNotify, drv_mobile_MobileCellScanNotify, 2)





