/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "drv_pm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(drv_pm_PmResult, drv_pm_PmResult, AUTO)


PB_BIND(drv_pm_PmRequestRequest, drv_pm_PmRequestRequest, AUTO)


PB_BIND(drv_pm_PmRequestResponse, drv_pm_PmRequestResponse, AUTO)


PB_BIND(drv_pm_PmPowerCtrlRequest, drv_pm_PmPowerCtrlRequest, AUTO)


PB_BIND(drv_pm_PmPowerCtrlResponse, drv_pm_PmPowerCtrlResponse, AUTO)


PB_BIND(drv_pm_PmWakeupPinRequest, drv_pm_PmWakeupPinRequest, AUTO)


PB_BIND(drv_pm_PmWakeupPinResponse, drv_pm_PmWakeupPinResponse, AUTO)


PB_BIND(drv_pm_PmRpcRequest, drv_pm_PmRpcRequest, AUTO)


PB_BIND(drv_pm_PmRpcResponse, drv_pm_PmRpcResponse, AUTO)





