/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "drv_wlan.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(drv_wlan_WlanResult, drv_wlan_WlanResult, AUTO)


PB_BIND(drv_wlan_WlanInitRequest, drv_wlan_WlanInitRequest, AUTO)


PB_BIND(drv_wlan_WlanInitResponse, drv_wlan_WlanInitResponse, AUTO)


PB_BIND(drv_wlan_WlanConnectRequest, drv_wlan_WlanConnectRequest, AUTO)


PB_BIND(drv_wlan_WlanConnectResponse, drv_wlan_WlanConnectResponse, AUTO)


PB_BIND(drv_wlan_WlanDisconnectRequest, drv_wlan_WlanDisconnectRequest, AUTO)


PB_BIND(drv_wlan_WlanDisconnectResponse, drv_wlan_WlanDisconnectResponse, AUTO)


PB_BIND(drv_wlan_WlanApStartRequest, drv_wlan_WlanApStartRequest, AUTO)


PB_BIND(drv_wlan_WlanApStartResponse, drv_wlan_WlanApStartResponse, AUTO)


PB_BIND(drv_wlan_WlanApStopRequest, drv_wlan_WlanApStopRequest, AUTO)


PB_BIND(drv_wlan_WlanApStopResponse, drv_wlan_WlanApStopResponse, AUTO)


PB_BIND(drv_wlan_WlanScanRequest, drv_wlan_WlanScanRequest, AUTO)


PB_BIND(drv_wlan_WlanScanResponse, drv_wlan_WlanScanResponse, AUTO)


PB_BIND(drv_wlan_WlanRpcRequest, drv_wlan_WlanRpcRequest, AUTO)


PB_BIND(drv_wlan_WlanRpcResponse, drv_wlan_WlanRpcResponse, AUTO)





