/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "drv_uart.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(drv_uart_UartResult, drv_uart_UartResult, AUTO)


PB_BIND(drv_uart_UartSetupRequest, drv_uart_UartSetupRequest, AUTO)


PB_BIND(drv_uart_UartSetupResponse, drv_uart_UartSetupResponse, AUTO)


PB_BIND(drv_uart_UartWriteRequest, drv_uart_UartWriteRequest, 2)


PB_BIND(drv_uart_UartWriteResponse, drv_uart_UartWriteResponse, AUTO)


PB_BIND(drv_uart_UartCloseRequest, drv_uart_UartCloseRequest, AUTO)


PB_BIND(drv_uart_UartCloseResponse, drv_uart_UartCloseResponse, AUTO)


PB_BIND(drv_uart_UartRpcRequest, drv_uart_UartRpcRequest, 2)


PB_BIND(drv_uart_UartRpcResponse, drv_uart_UartRpcResponse, AUTO)







