/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "drv_bluetooth.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(drv_bluetooth_BleResult, drv_bluetooth_BleResult, AUTO)


PB_BIND(drv_bluetooth_BleAdvCfg, drv_bluetooth_BleAdvCfg, AUTO)


PB_BIND(drv_bluetooth_BleScanCfg, drv_bluetooth_BleScanCfg, AUTO)


PB_BIND(drv_bluetooth_BleInitRequest, drv_bluetooth_BleInitRequest, AUTO)


PB_BIND(drv_bluetooth_BleDeinitRequest, drv_bluetooth_BleDeinitRequest, AUTO)


PB_BIND(drv_bluetooth_BleSetNameRequest, drv_bluetooth_BleSetNameRequest, AUTO)


PB_BIND(drv_bluetooth_BleSetMaxMtuRequest, drv_bluetooth_BleSetMaxMtuRequest, AUTO)


PB_BIND(drv_bluetooth_BleAdvCreateRequest, drv_bluetooth_BleAdvCreateRequest, AUTO)


PB_BIND(drv_bluetooth_BleAdvSetDataRequest, drv_bluetooth_BleAdvSetDataRequest, AUTO)


PB_BIND(drv_bluetooth_BleAdvSetScanRspRequest, drv_bluetooth_BleAdvSetScanRspRequest, AUTO)


PB_BIND(drv_bluetooth_BleAdvStartRequest, drv_bluetooth_BleAdvStartRequest, AUTO)


PB_BIND(drv_bluetooth_BleAdvStopRequest, drv_bluetooth_BleAdvStopRequest, AUTO)


PB_BIND(drv_bluetooth_BleAdvDeleteRequest, drv_bluetooth_BleAdvDeleteRequest, AUTO)


PB_BIND(drv_bluetooth_BleGattCreateRequest, drv_bluetooth_BleGattCreateRequest, 2)


PB_BIND(drv_bluetooth_BleReadResponseRequest, drv_bluetooth_BleReadResponseRequest, 2)


PB_BIND(drv_bluetooth_BleWriteNotifyRequest, drv_bluetooth_BleWriteNotifyRequest, 2)


PB_BIND(drv_bluetooth_BleScanCreateRequest, drv_bluetooth_BleScanCreateRequest, AUTO)


PB_BIND(drv_bluetooth_BleScanStartRequest, drv_bluetooth_BleScanStartRequest, AUTO)


PB_BIND(drv_bluetooth_BleScanStopRequest, drv_bluetooth_BleScanStopRequest, AUTO)


PB_BIND(drv_bluetooth_BleScanDeleteRequest, drv_bluetooth_BleScanDeleteRequest, AUTO)


PB_BIND(drv_bluetooth_BleInitResponse, drv_bluetooth_BleInitResponse, AUTO)


PB_BIND(drv_bluetooth_BleDeinitResponse, drv_bluetooth_BleDeinitResponse, AUTO)


PB_BIND(drv_bluetooth_BleSetNameResponse, drv_bluetooth_BleSetNameResponse, AUTO)


PB_BIND(drv_bluetooth_BleSetMaxMtuResponse, drv_bluetooth_BleSetMaxMtuResponse, AUTO)


PB_BIND(drv_bluetooth_BleAdvCreateResponse, drv_bluetooth_BleAdvCreateResponse, AUTO)


PB_BIND(drv_bluetooth_BleAdvSetDataResponse, drv_bluetooth_BleAdvSetDataResponse, AUTO)


PB_BIND(drv_bluetooth_BleAdvSetScanRspResponse, drv_bluetooth_BleAdvSetScanRspResponse, AUTO)


PB_BIND(drv_bluetooth_BleAdvStartResponse, drv_bluetooth_BleAdvStartResponse, AUTO)


PB_BIND(drv_bluetooth_BleAdvStopResponse, drv_bluetooth_BleAdvStopResponse, AUTO)


PB_BIND(drv_bluetooth_BleAdvDeleteResponse, drv_bluetooth_BleAdvDeleteResponse, AUTO)


PB_BIND(drv_bluetooth_BleGattCreateResponse, drv_bluetooth_BleGattCreateResponse, AUTO)


PB_BIND(drv_bluetooth_BleReadResponseResponse, drv_bluetooth_BleReadResponseResponse, AUTO)


PB_BIND(drv_bluetooth_BleWriteNotifyResponse, drv_bluetooth_BleWriteNotifyResponse, AUTO)


PB_BIND(drv_bluetooth_BleScanCreateResponse, drv_bluetooth_BleScanCreateResponse, AUTO)


PB_BIND(drv_bluetooth_BleScanStartResponse, drv_bluetooth_BleScanStartResponse, AUTO)


PB_BIND(drv_bluetooth_BleScanStopResponse, drv_bluetooth_BleScanStopResponse, AUTO)


PB_BIND(drv_bluetooth_BleScanDeleteResponse, drv_bluetooth_BleScanDeleteResponse, AUTO)


PB_BIND(drv_bluetooth_BleRpcRequest, drv_bluetooth_BleRpcRequest, 2)


PB_BIND(drv_bluetooth_BleRpcResponse, drv_bluetooth_BleRpcResponse, AUTO)


PB_BIND(drv_bluetooth_BleEventNotify, drv_bluetooth_BleEventNotify, 2)





