#ifndef LUAT_EASYLVGL_SYMBOL_H
#define LUAT_EASYLVGL_SYMBOL_H

#include "rotable2.h"
#include "lvgl9/src/font/lv_symbol_def.h"

#define EASYLVGL_SYMBOL_REG \
    {"EASYLVGL_SYMBOL_AUDIO",        ROREG_STR(LV_SYMBOL_AUDIO           )},\
    {"EASYLVGL_SYMBOL_VIDEO",        ROREG_STR(LV_SYMBOL_VIDEO           )},\
    {"EASYLVGL_SYMBOL_LIST",         ROREG_STR(LV_SYMBOL_LIST            )},\
    {"EASYLVGL_SYMBOL_OK",           ROREG_STR(LV_SYMBOL_OK              )},\
    {"EASYLVGL_SYMBOL_CLOSE",        ROREG_STR(LV_SYMBOL_CLOSE           )},\
    {"EASYLVGL_SYMBOL_POWER",        ROREG_STR(LV_SYMBOL_POWER           )},\
    {"EASYLVGL_SYMBOL_SETTINGS",     ROREG_STR(LV_SYMBOL_SETTINGS        )},\
    {"EASYLVGL_SYMBOL_HOME",         ROREG_STR(LV_SYMBOL_HOME            )},\
    {"EASYLVGL_SYMBOL_DOWNLOAD",     ROREG_STR(LV_SYMBOL_DOWNLOAD        )},\
    {"EASYLVGL_SYMBOL_DRIVE",        ROREG_STR(LV_SYMBOL_DRIVE           )},\
    {"EASYLVGL_SYMBOL_REFRESH",      ROREG_STR(LV_SYMBOL_REFRESH         )},\
    {"EASYLVGL_SYMBOL_MUTE",         ROREG_STR(LV_SYMBOL_MUTE            )},\
    {"EASYLVGL_SYMBOL_VOLUME_MID",   ROREG_STR(LV_SYMBOL_VOLUME_MID      )},\
    {"EASYLVGL_SYMBOL_VOLUME_MAX",   ROREG_STR(LV_SYMBOL_VOLUME_MAX      )},\
    {"EASYLVGL_SYMBOL_IMAGE",        ROREG_STR(LV_SYMBOL_IMAGE           )},\
    {"EASYLVGL_SYMBOL_EDIT",         ROREG_STR(LV_SYMBOL_EDIT            )},\
    {"EASYLVGL_SYMBOL_PREV",         ROREG_STR(LV_SYMBOL_PREV            )},\
    {"EASYLVGL_SYMBOL_PLAY",         ROREG_STR(LV_SYMBOL_PLAY            )},\
    {"EASYLVGL_SYMBOL_PAUSE",        ROREG_STR(LV_SYMBOL_PAUSE           )},\
    {"EASYLVGL_SYMBOL_STOP",         ROREG_STR(LV_SYMBOL_STOP            )},\
    {"EASYLVGL_SYMBOL_NEXT",         ROREG_STR(LV_SYMBOL_NEXT            )},\
    {"EASYLVGL_SYMBOL_EJECT",        ROREG_STR(LV_SYMBOL_EJECT           )},\
    {"EASYLVGL_SYMBOL_LEFT",         ROREG_STR(LV_SYMBOL_LEFT            )},\
    {"EASYLVGL_SYMBOL_RIGHT",        ROREG_STR(LV_SYMBOL_RIGHT           )},\
    {"EASYLVGL_SYMBOL_PLUS",         ROREG_STR(LV_SYMBOL_PLUS            )},\
    {"EASYLVGL_SYMBOL_MINUS",        ROREG_STR(LV_SYMBOL_MINUS           )},\
    {"EASYLVGL_SYMBOL_EYE_OPEN",     ROREG_STR(LV_SYMBOL_EYE_OPEN        )},\
    {"EASYLVGL_SYMBOL_EYE_CLOSE",    ROREG_STR(LV_SYMBOL_EYE_CLOSE       )},\
    {"EASYLVGL_SYMBOL_WARNING",      ROREG_STR(LV_SYMBOL_WARNING         )},\
    {"EASYLVGL_SYMBOL_SHUFFLE",      ROREG_STR(LV_SYMBOL_SHUFFLE         )},\
    {"EASYLVGL_SYMBOL_UP",           ROREG_STR(LV_SYMBOL_UP              )},\
    {"EASYLVGL_SYMBOL_DOWN",         ROREG_STR(LV_SYMBOL_DOWN            )},\
    {"EASYLVGL_SYMBOL_LOOP",         ROREG_STR(LV_SYMBOL_LOOP            )},\
    {"EASYLVGL_SYMBOL_DIRECTORY",    ROREG_STR(LV_SYMBOL_DIRECTORY       )},\
    {"EASYLVGL_SYMBOL_UPLOAD",       ROREG_STR(LV_SYMBOL_UPLOAD          )},\
    {"EASYLVGL_SYMBOL_CALL",         ROREG_STR(LV_SYMBOL_CALL            )},\
    {"EASYLVGL_SYMBOL_CUT",          ROREG_STR(LV_SYMBOL_CUT             )},\
    {"EASYLVGL_SYMBOL_COPY",         ROREG_STR(LV_SYMBOL_COPY            )},\
    {"EASYLVGL_SYMBOL_SAVE",         ROREG_STR(LV_SYMBOL_SAVE            )},\
    {"EASYLVGL_SYMBOL_CHARGE",       ROREG_STR(LV_SYMBOL_CHARGE          )},\
    {"EASYLVGL_SYMBOL_PASTE",        ROREG_STR(LV_SYMBOL_PASTE           )},\
    {"EASYLVGL_SYMBOL_BELL",         ROREG_STR(LV_SYMBOL_BELL            )},\
    {"EASYLVGL_SYMBOL_KEYBOARD",     ROREG_STR(LV_SYMBOL_KEYBOARD        )},\
    {"EASYLVGL_SYMBOL_GPS",          ROREG_STR(LV_SYMBOL_GPS             )},\
    {"EASYLVGL_SYMBOL_FILE",         ROREG_STR(LV_SYMBOL_FILE            )},\
    {"EASYLVGL_SYMBOL_WIFI",         ROREG_STR(LV_SYMBOL_WIFI            )},\
    {"EASYLVGL_SYMBOL_BATTERY_FULL", ROREG_STR(LV_SYMBOL_BATTERY_FULL    )},\
    {"EASYLVGL_SYMBOL_BATTERY_3",    ROREG_STR(LV_SYMBOL_BATTERY_3       )},\
    {"EASYLVGL_SYMBOL_BATTERY_2",    ROREG_STR(LV_SYMBOL_BATTERY_2       )},\
    {"EASYLVGL_SYMBOL_BATTERY_1",    ROREG_STR(LV_SYMBOL_BATTERY_1       )},\
    {"EASYLVGL_SYMBOL_BATTERY_EMPTY",ROREG_STR(LV_SYMBOL_BATTERY_EMPTY   )},\
    {"EASYLVGL_SYMBOL_USB",          ROREG_STR(LV_SYMBOL_USB             )},\
    {"EASYLVGL_SYMBOL_BLUETOOTH",    ROREG_STR(LV_SYMBOL_BLUETOOTH       )},\
    {"EASYLVGL_SYMBOL_TRASH",        ROREG_STR(LV_SYMBOL_TRASH           )},\
    {"EASYLVGL_SYMBOL_BACKSPACE",    ROREG_STR(LV_SYMBOL_BACKSPACE       )},\
    {"EASYLVGL_SYMBOL_SD_CARD",      ROREG_STR(LV_SYMBOL_SD_CARD         )},\
    {"EASYLVGL_SYMBOL_NEW_LINE",     ROREG_STR(LV_SYMBOL_NEW_LINE        )},\
    {"EASYLVGL_SYMBOL_DUMMY",        ROREG_STR(   "\xEF\xA3\xBF"         )},\
    {"EASYLVGL_SYMBOL_BULLET",       ROREG_STR(LV_SYMBOL_BULLET)}

#endif

