Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Split('''
        binding/luat_lib_lwip.c
        binding/luat_lib_lwip_tcp.c
        binding/luat_lib_lwip_udp.c
        binding/luat_lib_lwip_mqtt.c
        ''')

group = DefineGroup('lwip_lua', src, depend = ['RT_USING_LWIP'])

Return('group')
