Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd,  cwd + "/../include", 
                 cwd + "/../packages/vsprintf", 
                 cwd + "/../packages/lfs",
                 cwd + "/../packages/airkiss",
                 cwd + "/../packages/fatfs",
                 cwd + "/../packages/u8g2",
                 ]

group = DefineGroup('rtt', src, depend = [], CPPPATH = CPPPATH)

Return('group')
