
AIRTALK_TASK_NAME = "airtalk_task"
USER_TASK_NAME = "user"
MSG_PERSON_SPEECH_REQ = 0
MSG_SPEECH_STOP_REQ = 1
MSG_PERSON_SPEECH_ACK = 2
MSG_SPEECH_STOP_ACK = 3
MSG_SPEECH_IND = 4
MSG_READY = 10
MSG_NOT_READY = 11
MSG_KEY_PRESS = 12



SP_T_IDLE = 0
SP_T_CONNECTING = 1
SP_T_CONNECTED = 2
SP_T_DISCONNECTING = 3

SUCC = "success"