from building import *

cwd = GetCurrentDir()
src	= []
for p in os.listdir(cwd) :
    if p.endswith(".c"):
        src += [p]

src.remove('luat_fs_fatfs.c')

CPPPATH = [cwd]

group = DefineGroup('luat_vfs', src, depend = [], CPPPATH = CPPPATH)

Return('group')
