target("lvgl")
    set_kind("static")
    --target:set("default", true)
    add_files("**.c")

    add_includedirs(".",{public = true})
    add_includedirs("./binding",{public = true})
    add_includedirs("./gen",{public = true})
    add_includedirs("./src",{public = true})
    add_includedirs("./font",{public = true})
    add_includedirs("../lcd",{public = true})
    add_includedirs("../u8g2",{public = true})
    add_includedirs("../qrcode",{public = true})
target_end()
