# for module compiling
import os
Import('RTT_ROOT')

cwd = str(Dir('#'))
objs = SConscript(os.path.join(cwd, '../../rtt/SConscript'))
objs = objs + SConscript(os.path.join(cwd, '../../../lua/SConscript'))
objs = objs + SConscript(os.path.join(cwd, '../../../luat/SConscript'))
objs = objs + SConscript(os.path.join(cwd, '../../../components/network/lwip/SConscript'))
objs = objs + SConscript(os.path.join(cwd, '../../../components/lcd/SConscript'))

Return('objs')
