from building import *

cwd = GetCurrentDir()

CPPPATH = [cwd]

if GetDepend("PKG_USING_U8G2"):
    group = DefineGroup('eink', ["luat_lib_disp.c", "luat_lib_u8g2.c", "u8g2_font_opposansm.c"], depend = [], CPPPATH = CPPPATH)
else:
    src = Glob('*.c')
    group = DefineGroup('eink', src, depend = ['PKG_USING_LUATOS_SOC_EINK'], CPPPATH = CPPPATH)

Return('group')
