-- gen_luac.lua: generate C array from ems.lua using string.dump
-- Run under luatos-lua.exe as main.lua, or under standard Lua 5.3
-- Supports 32/64 bit VM via LUAT_EMS_LUAC_SUFFIX environment variable.

local function read_file(path)
    local f = io.open(path, "rb")
    if not f then return nil end
    local data = f:read("*a")
    f:close()
    return data
end

local function file_exists(path)
    local f = io.open(path, "rb")
    if f then f:close() return true end
    return false
end

-- Determine input/output paths based on environment
-- When run as luatos-lua.exe main.lua, VFS root is the script directory
local script_dir = "."
if os.getenv and os.getenv("LUATOS_EMS_DIR") then
    script_dir = os.getenv("LUATOS_EMS_DIR")
end

-- Suffix for the output file and array names, e.g. "32" or "64"
local suffix = ""
if os.getenv and os.getenv("LUAT_EMS_LUAC_SUFFIX") then
    suffix = os.getenv("LUAT_EMS_LUAC_SUFFIX")
end

local in_path = script_dir .. "/ems.lua"
local out_path = script_dir .. "/src/luat_ems_server_luac"
if suffix ~= "" then
    out_path = out_path .. "_" .. suffix
end
out_path = out_path .. ".c"

if not file_exists(in_path) then
    print("ERROR: cannot read " .. in_path)
    os.exit(1)
end

local code = read_file(in_path)
local fn, err = load(code, "ems")
if not fn then
    print("ERROR: syntax error: " .. tostring(err))
    os.exit(1)
end

local dump = string.dump(fn, true)

local array_name = "ems_server_luac"
local len_name = "ems_server_luac_len"
if suffix ~= "" then
    array_name = array_name .. "_" .. suffix
    len_name = len_name .. "_" .. suffix
end

-- Write the C source file directly; avoid stdout spam that may get log prefixes.
local out_dir = script_dir .. "/src"
if os.execute then
    -- Best-effort directory creation (ignored if it already exists).
    -- Use the right stderr discard token for the host OS.
    local null_redirect = "2>/dev/null"
    if os.getenv and os.getenv("OS") == "Windows_NT" then
        null_redirect = "2>nul"
    end
    os.execute("mkdir \"" .. out_dir .. "\" " .. null_redirect)
end

local f = io.open(out_path, "w")
if not f then
    print("ERROR: cannot write " .. out_path)
    os.exit(1)
end

f:write("// Auto-generated from ems.lua, DO NOT EDIT\n")
f:write("// Generated by gen_luac.lua\n")
f:write('#include "luat_ems_server.h"\n')
f:write("\n")
f:write("const unsigned char " .. array_name .. "[] = {\n")

local line = {}
for i = 1, #dump do
    line[#line+1] = string.format("0x%02X", string.byte(dump, i))
    if i % 16 == 0 then
        f:write("    " .. table.concat(line, ", ") .. ",\n")
        line = {}
    end
end
if #line > 0 then
    f:write("    " .. table.concat(line, ", ") .. ",\n")
end

f:write("};\n")
f:write("\n")
f:write("const size_t " .. len_name .. " = sizeof(" .. array_name .. ");\n")
f:close()

print("SUCCESS: " .. out_path)
os.exit(0)
