-- gen_luac.lua: generate C array from ems.lua using string.dump
-- Run under luatos-lua.exe as main.lua, or under standard Lua 5.3

local function read_file(path)
    local f = io.open(path, "rb")
    if not f then return nil end
    local data = f:read("*a")
    f:close()
    return data
end

local function file_exists(path)
    local f = io.open(path, "rb")
    if f then f:close() return true end
    return false
end

-- Determine input/output paths based on environment
-- When run as luatos-lua.exe main.lua, VFS root is the script directory
local script_dir = "."
if os.getenv and os.getenv("LUATOS_EMS_DIR") then
    script_dir = os.getenv("LUATOS_EMS_DIR")
end

local in_path = script_dir .. "/ems.lua"
local out_path = script_dir .. "/src/luat_ems_server_luac.c"

if not file_exists(in_path) then
    print("ERROR: cannot read " .. in_path)
    os.exit(1)
end

local code = read_file(in_path)
local fn, err = load(code, "ems")
if not fn then
    print("ERROR: syntax error: " .. tostring(err))
    os.exit(1)
end

local dump = string.dump(fn, true)

print("// Auto-generated from ems.lua, DO NOT EDIT")
print("// Generated by gen_luac.lua")
print('#include "luat_ems_server.h"')
print("")
print("const unsigned char ems_server_luac[] = {")

local line = {}
for i = 1, #dump do
    line[#line+1] = string.format("0x%02X", string.byte(dump, i))
    if i % 16 == 0 then
        print("    " .. table.concat(line, ", ") .. ",")
        line = {}
    end
end
if #line > 0 then
    print("    " .. table.concat(line, ", ") .. ",")
end

print("};")
print("")
print("const size_t ems_server_luac_len = sizeof(ems_server_luac);")
print("SUCCESS")
os.exit(0)
