@echo off
setlocal EnableDelayedExpansion

set "SCRIPT_DIR=%~dp0"

:: Try to find bash.exe in PATH (Git Bash is usually available)
for /f "delims=" %%i in ('where bash.exe 2^>nul') do (
    "%%i" "%SCRIPT_DIR%gen_luac.sh"
    exit /b %errorlevel%
)

:: No bash found, fallback to luatos-lua.exe direct execution
set "LUATOS_EXE=%SCRIPT_DIR%..\..\bsp\pc\build\out\luatos-lua.exe"
set "TMP_DIR=%TEMP%\gen_luac_%RANDOM%"

if not exist "%LUATOS_EXE%" (
    echo WARNING: neither bash.exe nor luatos-lua.exe found
    if exist "%SCRIPT_DIR%src\luat_ems_server_luac.c" (
        echo Pre-generated file exists: src\luat_ems_server_luac.c
        exit /b 0
    ) else (
        echo ERROR: No pre-generated file found at src\luat_ems_server_luac.c
        exit /b 1
    )
)

mkdir "%TMP_DIR%"
copy /Y "%SCRIPT_DIR%ems.lua" "%TMP_DIR%\ems.lua" >/dev/null
copy /Y "%SCRIPT_DIR%gen_luac.lua" "%TMP_DIR%\main.lua" >/dev/null

cd /d "%SCRIPT_DIR%"
"%LUATOS_EXE%" "%TMP_DIR%" > "%TMP_DIR%\output.txt" 2>&1

findstr /C:"SUCCESS" "%TMP_DIR%\output.txt" >/dev/null
if errorlevel 1 (
    echo ERROR: luac generation failed
    type "%TMP_DIR%\output.txt"
    rmdir /S /Q "%TMP_DIR%"
    exit /b 1
)

:: Filter log prefixes: [timestamp][id] content -> content
:: tokens=3* with delims=] skips the two bracketed fields
set "FILTERED=%TMP_DIR%\filtered.txt"
>"%FILTERED%" (
    for /f "usebackq tokens=3* delims=] " %%a in ("%TMP_DIR%\output.txt") do (
        echo %%a %%b
    )
)

:: Extract block between Auto-generated and SUCCESS
set "OUT=%TMP_DIR%\out.txt"
>"%OUT%" (
    set "in_block=0"
    for /f "usebackq delims=" %%L in ("%FILTERED%") do (
        set "line=%%L"
        setlocal EnableDelayedExpansion
        set "trim=!line: =!"
        if "!trim!"=="" endlocal & goto :nextline
        echo !line! | findstr /B "// Auto-generated" >/dev/null
        if not errorlevel 1 (
            endlocal
            set "in_block=1"
            echo // Auto-generated from ems.lua, DO NOT EDIT
            echo // Generated by gen_luac.lua
            goto :nextline
        )
        if "!in_block!"=="1" (
            echo !line! | findstr /C:"SUCCESS" >/dev/null
            if not errorlevel 1 (
                endlocal
                set "in_block=0"
                goto :nextline
            )
            echo !line!
        )
        endlocal
        :nextline
    )
)

if not exist "%SCRIPT_DIR%src" mkdir "%SCRIPT_DIR%src"
copy /Y "%OUT%" "%SCRIPT_DIR%src\luat_ems_server_luac.c" >/dev/null
rmdir /S /Q "%TMP_DIR%"
echo Generated: %SCRIPT_DIR%src\luat_ems_server_luac.c
