/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DRV_UART_DRV_UART_PB_H_INCLUDED
#define PB_DRV_UART_DRV_UART_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 奇偶校验 */
typedef enum _drv_uart_UartParity {
    drv_uart_UartParity_UART_PARITY_NONE = 0,
    drv_uart_UartParity_UART_PARITY_ODD = 1,
    drv_uart_UartParity_UART_PARITY_EVEN = 2
} drv_uart_UartParity;

/* 通用返回码 */
typedef enum _drv_uart_UartResultCode {
    drv_uart_UartResultCode_UART_RES_OK = 0,
    drv_uart_UartResultCode_UART_RES_EINVAL = 1,
    drv_uart_UartResultCode_UART_RES_EBUSY = 2,
    drv_uart_UartResultCode_UART_RES_FAIL = 255
} drv_uart_UartResultCode;

/* Struct definitions */
typedef struct _drv_uart_UartResult {
    bool has_code;
    drv_uart_UartResultCode code;
    bool has_os_errno;
    int32_t os_errno;
} drv_uart_UartResult;

/* 配置串口（对应 luat_uart_setup） */
typedef struct _drv_uart_UartSetupRequest {
    uint32_t id;
    bool has_baud_rate;
    uint32_t baud_rate;
    bool has_data_bits;
    uint32_t data_bits;
    bool has_stop_bits;
    uint32_t stop_bits;
    bool has_parity;
    drv_uart_UartParity parity;
    bool has_bufsz;
    uint32_t bufsz;
} drv_uart_UartSetupRequest;

typedef struct _drv_uart_UartSetupResponse {
    drv_uart_UartResult result;
} drv_uart_UartSetupResponse;

typedef PB_BYTES_ARRAY_T(500) drv_uart_UartWriteRequest_data_t;
/* 写数据（最大 500 字节；大数据走原始分段路径） */
typedef struct _drv_uart_UartWriteRequest {
    uint32_t id;
    drv_uart_UartWriteRequest_data_t data;
} drv_uart_UartWriteRequest;

typedef struct _drv_uart_UartWriteResponse {
    drv_uart_UartResult result;
    bool has_bytes_written;
    int32_t bytes_written;
} drv_uart_UartWriteResponse;

/* 关闭串口（对应 luat_uart_close） */
typedef struct _drv_uart_UartCloseRequest {
    uint32_t id;
} drv_uart_UartCloseRequest;

typedef struct _drv_uart_UartCloseResponse {
    drv_uart_UartResult result;
} drv_uart_UartCloseResponse;

/* 统一 RPC 请求 */
typedef struct _drv_uart_UartRpcRequest {
    uint32_t req_id;
    pb_size_t which_payload;
    union {
        drv_uart_UartSetupRequest setup;
        drv_uart_UartWriteRequest write;
        drv_uart_UartCloseRequest close;
    } payload;
} drv_uart_UartRpcRequest;

/* 统一 RPC 响应 */
typedef struct _drv_uart_UartRpcResponse {
    bool has_req_id;
    uint32_t req_id;
    pb_size_t which_payload;
    union {
        drv_uart_UartSetupResponse setup;
        drv_uart_UartWriteResponse write;
        drv_uart_UartCloseResponse close;
    } payload;
} drv_uart_UartRpcResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _drv_uart_UartParity_MIN drv_uart_UartParity_UART_PARITY_NONE
#define _drv_uart_UartParity_MAX drv_uart_UartParity_UART_PARITY_EVEN
#define _drv_uart_UartParity_ARRAYSIZE ((drv_uart_UartParity)(drv_uart_UartParity_UART_PARITY_EVEN+1))

#define _drv_uart_UartResultCode_MIN drv_uart_UartResultCode_UART_RES_OK
#define _drv_uart_UartResultCode_MAX drv_uart_UartResultCode_UART_RES_FAIL
#define _drv_uart_UartResultCode_ARRAYSIZE ((drv_uart_UartResultCode)(drv_uart_UartResultCode_UART_RES_FAIL+1))

#define drv_uart_UartResult_code_ENUMTYPE drv_uart_UartResultCode

#define drv_uart_UartSetupRequest_parity_ENUMTYPE drv_uart_UartParity









/* Initializer values for message structs */
#define drv_uart_UartResult_init_default         {false, drv_uart_UartResultCode_UART_RES_OK, false, 0}
#define drv_uart_UartSetupRequest_init_default   {0, false, 9600u, false, 8u, false, 1u, false, drv_uart_UartParity_UART_PARITY_NONE, false, 1024u}
#define drv_uart_UartSetupResponse_init_default  {drv_uart_UartResult_init_default}
#define drv_uart_UartWriteRequest_init_default   {0, {0, {0}}}
#define drv_uart_UartWriteResponse_init_default  {drv_uart_UartResult_init_default, false, 0}
#define drv_uart_UartCloseRequest_init_default   {0}
#define drv_uart_UartCloseResponse_init_default  {drv_uart_UartResult_init_default}
#define drv_uart_UartRpcRequest_init_default     {0, 0, {drv_uart_UartSetupRequest_init_default}}
#define drv_uart_UartRpcResponse_init_default    {false, 0u, 0, {drv_uart_UartSetupResponse_init_default}}
#define drv_uart_UartResult_init_zero            {false, _drv_uart_UartResultCode_MIN, false, 0}
#define drv_uart_UartSetupRequest_init_zero      {0, false, 0, false, 0, false, 0, false, _drv_uart_UartParity_MIN, false, 0}
#define drv_uart_UartSetupResponse_init_zero     {drv_uart_UartResult_init_zero}
#define drv_uart_UartWriteRequest_init_zero      {0, {0, {0}}}
#define drv_uart_UartWriteResponse_init_zero     {drv_uart_UartResult_init_zero, false, 0}
#define drv_uart_UartCloseRequest_init_zero      {0}
#define drv_uart_UartCloseResponse_init_zero     {drv_uart_UartResult_init_zero}
#define drv_uart_UartRpcRequest_init_zero        {0, 0, {drv_uart_UartSetupRequest_init_zero}}
#define drv_uart_UartRpcResponse_init_zero       {false, 0, 0, {drv_uart_UartSetupResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define drv_uart_UartResult_code_tag             1
#define drv_uart_UartResult_os_errno_tag         2
#define drv_uart_UartSetupRequest_id_tag         1
#define drv_uart_UartSetupRequest_baud_rate_tag  2
#define drv_uart_UartSetupRequest_data_bits_tag  3
#define drv_uart_UartSetupRequest_stop_bits_tag  4
#define drv_uart_UartSetupRequest_parity_tag     5
#define drv_uart_UartSetupRequest_bufsz_tag      6
#define drv_uart_UartSetupResponse_result_tag    1
#define drv_uart_UartWriteRequest_id_tag         1
#define drv_uart_UartWriteRequest_data_tag       2
#define drv_uart_UartWriteResponse_result_tag    1
#define drv_uart_UartWriteResponse_bytes_written_tag 2
#define drv_uart_UartCloseRequest_id_tag         1
#define drv_uart_UartCloseResponse_result_tag    1
#define drv_uart_UartRpcRequest_req_id_tag       1
#define drv_uart_UartRpcRequest_setup_tag        10
#define drv_uart_UartRpcRequest_write_tag        11
#define drv_uart_UartRpcRequest_close_tag        12
#define drv_uart_UartRpcResponse_req_id_tag      1
#define drv_uart_UartRpcResponse_setup_tag       10
#define drv_uart_UartRpcResponse_write_tag       11
#define drv_uart_UartRpcResponse_close_tag       12

/* Struct field encoding specification for nanopb */
#define drv_uart_UartResult_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    code,              1) \
X(a, STATIC,   OPTIONAL, INT32,    os_errno,          2)
#define drv_uart_UartResult_CALLBACK NULL
#define drv_uart_UartResult_DEFAULT (const pb_byte_t*)"\x10\x00\x00"

#define drv_uart_UartSetupRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, UINT32,   baud_rate,         2) \
X(a, STATIC,   OPTIONAL, UINT32,   data_bits,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   stop_bits,         4) \
X(a, STATIC,   OPTIONAL, UENUM,    parity,            5) \
X(a, STATIC,   OPTIONAL, UINT32,   bufsz,             6)
#define drv_uart_UartSetupRequest_CALLBACK NULL
#define drv_uart_UartSetupRequest_DEFAULT (const pb_byte_t*)"\x10\x80\x4b\x18\x08\x20\x01\x30\x80\x08\x00"

#define drv_uart_UartSetupResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_uart_UartSetupResponse_CALLBACK NULL
#define drv_uart_UartSetupResponse_DEFAULT NULL
#define drv_uart_UartSetupResponse_result_MSGTYPE drv_uart_UartResult

#define drv_uart_UartWriteRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   id,                1) \
X(a, STATIC,   REQUIRED, BYTES,    data,              2)
#define drv_uart_UartWriteRequest_CALLBACK NULL
#define drv_uart_UartWriteRequest_DEFAULT NULL

#define drv_uart_UartWriteResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1) \
X(a, STATIC,   OPTIONAL, INT32,    bytes_written,     2)
#define drv_uart_UartWriteResponse_CALLBACK NULL
#define drv_uart_UartWriteResponse_DEFAULT (const pb_byte_t*)"\x10\x00\x00"
#define drv_uart_UartWriteResponse_result_MSGTYPE drv_uart_UartResult

#define drv_uart_UartCloseRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   id,                1)
#define drv_uart_UartCloseRequest_CALLBACK NULL
#define drv_uart_UartCloseRequest_DEFAULT NULL

#define drv_uart_UartCloseResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_uart_UartCloseResponse_CALLBACK NULL
#define drv_uart_UartCloseResponse_DEFAULT NULL
#define drv_uart_UartCloseResponse_result_MSGTYPE drv_uart_UartResult

#define drv_uart_UartRpcRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   req_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,setup,payload.setup),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,write,payload.write),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,close,payload.close),  12)
#define drv_uart_UartRpcRequest_CALLBACK NULL
#define drv_uart_UartRpcRequest_DEFAULT NULL
#define drv_uart_UartRpcRequest_payload_setup_MSGTYPE drv_uart_UartSetupRequest
#define drv_uart_UartRpcRequest_payload_write_MSGTYPE drv_uart_UartWriteRequest
#define drv_uart_UartRpcRequest_payload_close_MSGTYPE drv_uart_UartCloseRequest

#define drv_uart_UartRpcResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   req_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,setup,payload.setup),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,write,payload.write),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,close,payload.close),  12)
#define drv_uart_UartRpcResponse_CALLBACK NULL
#define drv_uart_UartRpcResponse_DEFAULT (const pb_byte_t*)"\x08\x00\x00"
#define drv_uart_UartRpcResponse_payload_setup_MSGTYPE drv_uart_UartSetupResponse
#define drv_uart_UartRpcResponse_payload_write_MSGTYPE drv_uart_UartWriteResponse
#define drv_uart_UartRpcResponse_payload_close_MSGTYPE drv_uart_UartCloseResponse

extern const pb_msgdesc_t drv_uart_UartResult_msg;
extern const pb_msgdesc_t drv_uart_UartSetupRequest_msg;
extern const pb_msgdesc_t drv_uart_UartSetupResponse_msg;
extern const pb_msgdesc_t drv_uart_UartWriteRequest_msg;
extern const pb_msgdesc_t drv_uart_UartWriteResponse_msg;
extern const pb_msgdesc_t drv_uart_UartCloseRequest_msg;
extern const pb_msgdesc_t drv_uart_UartCloseResponse_msg;
extern const pb_msgdesc_t drv_uart_UartRpcRequest_msg;
extern const pb_msgdesc_t drv_uart_UartRpcResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define drv_uart_UartResult_fields &drv_uart_UartResult_msg
#define drv_uart_UartSetupRequest_fields &drv_uart_UartSetupRequest_msg
#define drv_uart_UartSetupResponse_fields &drv_uart_UartSetupResponse_msg
#define drv_uart_UartWriteRequest_fields &drv_uart_UartWriteRequest_msg
#define drv_uart_UartWriteResponse_fields &drv_uart_UartWriteResponse_msg
#define drv_uart_UartCloseRequest_fields &drv_uart_UartCloseRequest_msg
#define drv_uart_UartCloseResponse_fields &drv_uart_UartCloseResponse_msg
#define drv_uart_UartRpcRequest_fields &drv_uart_UartRpcRequest_msg
#define drv_uart_UartRpcResponse_fields &drv_uart_UartRpcResponse_msg

/* Maximum encoded size of messages (where known) */
#define DRV_UART_DRV_UART_PB_H_MAX_SIZE          drv_uart_UartRpcRequest_size
#define drv_uart_UartCloseRequest_size           6
#define drv_uart_UartCloseResponse_size          16
#define drv_uart_UartResult_size                 14
#define drv_uart_UartRpcRequest_size             518
#define drv_uart_UartRpcResponse_size            35
#define drv_uart_UartSetupRequest_size           32
#define drv_uart_UartSetupResponse_size          16
#define drv_uart_UartWriteRequest_size           509
#define drv_uart_UartWriteResponse_size          27

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
