/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DRV_BLUETOOTH_DRV_BLUETOOTH_PB_H_INCLUDED
#define PB_DRV_BLUETOOTH_DRV_BLUETOOTH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ---- 通用返回码 ---- */
typedef enum _drv_bluetooth_BleResultCode {
    drv_bluetooth_BleResultCode_BLE_RES_OK = 0,
    drv_bluetooth_BleResultCode_BLE_RES_FAIL = 255
} drv_bluetooth_BleResultCode;

/* Struct definitions */
typedef struct _drv_bluetooth_BleResult {
    bool has_code;
    drv_bluetooth_BleResultCode code;
    bool has_os_errno;
    int32_t os_errno;
} drv_bluetooth_BleResult;

/* ---- ADV 参数 (对应 luat_ble_adv_cfg_t) ---- */
typedef struct _drv_bluetooth_BleAdvCfg {
    bool has_channel_map;
    uint32_t channel_map; /* luat_ble_adv_chnl_t */
    bool has_addr_mode;
    uint32_t addr_mode; /* luat_ble_addr_mode_t */
    bool has_intv_min;
    uint32_t intv_min; /* 100 ms (160*0.625ms) */
    bool has_intv_max;
    uint32_t intv_max;
    bool has_adv_prop;
    uint32_t adv_prop; /* luat_ble_adv_prop_t bitmask */
    bool has_adv_type;
    uint32_t adv_type; /* LUAT_BLE_ADV_TYPE_LEGACY */
} drv_bluetooth_BleAdvCfg;

/* ---- Scan 参数 (对应 luat_ble_scan_cfg_t) ---- */
typedef struct _drv_bluetooth_BleScanCfg {
    bool has_scan_type;
    uint32_t scan_type; /* luat_ble_scan_type_t */
    bool has_addr_mode;
    uint32_t addr_mode; /* luat_ble_addr_mode_t */
    bool has_scan_interval;
    uint32_t scan_interval; /* 单位 0.625ms */
    bool has_scan_window;
    uint32_t scan_window;
} drv_bluetooth_BleScanCfg;

/* ---- 各操作请求消息 ---- */
typedef struct _drv_bluetooth_BleInitRequest {
    char dummy_field;
} drv_bluetooth_BleInitRequest;

typedef struct _drv_bluetooth_BleDeinitRequest {
    char dummy_field;
} drv_bluetooth_BleDeinitRequest;

typedef PB_BYTES_ARRAY_T(32) drv_bluetooth_BleSetNameRequest_name_t;
typedef struct _drv_bluetooth_BleSetNameRequest {
    drv_bluetooth_BleSetNameRequest_name_t name;
} drv_bluetooth_BleSetNameRequest;

typedef struct _drv_bluetooth_BleSetMaxMtuRequest {
    uint32_t max_mtu;
} drv_bluetooth_BleSetMaxMtuRequest;

typedef struct _drv_bluetooth_BleAdvCreateRequest {
    bool has_cfg;
    drv_bluetooth_BleAdvCfg cfg;
} drv_bluetooth_BleAdvCreateRequest;

typedef PB_BYTES_ARRAY_T(31) drv_bluetooth_BleAdvSetDataRequest_data_t;
typedef struct _drv_bluetooth_BleAdvSetDataRequest {
    drv_bluetooth_BleAdvSetDataRequest_data_t data;
} drv_bluetooth_BleAdvSetDataRequest;

typedef PB_BYTES_ARRAY_T(31) drv_bluetooth_BleAdvSetScanRspRequest_data_t;
typedef struct _drv_bluetooth_BleAdvSetScanRspRequest {
    drv_bluetooth_BleAdvSetScanRspRequest_data_t data;
} drv_bluetooth_BleAdvSetScanRspRequest;

typedef struct _drv_bluetooth_BleAdvStartRequest {
    char dummy_field;
} drv_bluetooth_BleAdvStartRequest;

typedef struct _drv_bluetooth_BleAdvStopRequest {
    char dummy_field;
} drv_bluetooth_BleAdvStopRequest;

typedef struct _drv_bluetooth_BleAdvDeleteRequest {
    char dummy_field;
} drv_bluetooth_BleAdvDeleteRequest;

typedef PB_BYTES_ARRAY_T(512) drv_bluetooth_BleGattCreateRequest_packed_gatt_t;
/* GATT 创建：packed_gatt 携带 luat_ble_gatt_pack() 序列化输出 */
typedef struct _drv_bluetooth_BleGattCreateRequest {
    drv_bluetooth_BleGattCreateRequest_packed_gatt_t packed_gatt;
} drv_bluetooth_BleGattCreateRequest;

typedef PB_BYTES_ARRAY_T(512) drv_bluetooth_BleReadResponseRequest_data_t;
/* Slave 读操作的应答 */
typedef struct _drv_bluetooth_BleReadResponseRequest {
    uint32_t conn_idx;
    uint32_t service_id;
    uint32_t att_handle;
    drv_bluetooth_BleReadResponseRequest_data_t data;
} drv_bluetooth_BleReadResponseRequest;

typedef PB_BYTES_ARRAY_T(512) drv_bluetooth_BleWriteNotifyRequest_data_t;
/* Slave 写通知 */
typedef struct _drv_bluetooth_BleWriteNotifyRequest {
    uint32_t conn_idx;
    uint32_t service_id;
    uint32_t att_handle;
    drv_bluetooth_BleWriteNotifyRequest_data_t data;
} drv_bluetooth_BleWriteNotifyRequest;

typedef struct _drv_bluetooth_BleScanCreateRequest {
    bool has_cfg;
    drv_bluetooth_BleScanCfg cfg;
} drv_bluetooth_BleScanCreateRequest;

typedef struct _drv_bluetooth_BleScanStartRequest {
    char dummy_field;
} drv_bluetooth_BleScanStartRequest;

typedef struct _drv_bluetooth_BleScanStopRequest {
    char dummy_field;
} drv_bluetooth_BleScanStopRequest;

typedef struct _drv_bluetooth_BleScanDeleteRequest {
    char dummy_field;
} drv_bluetooth_BleScanDeleteRequest;

/* ---- 各操作响应消息 ---- */
typedef struct _drv_bluetooth_BleInitResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleInitResponse;

typedef struct _drv_bluetooth_BleDeinitResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleDeinitResponse;

typedef struct _drv_bluetooth_BleSetNameResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleSetNameResponse;

typedef struct _drv_bluetooth_BleSetMaxMtuResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleSetMaxMtuResponse;

typedef struct _drv_bluetooth_BleAdvCreateResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleAdvCreateResponse;

typedef struct _drv_bluetooth_BleAdvSetDataResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleAdvSetDataResponse;

typedef struct _drv_bluetooth_BleAdvSetScanRspResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleAdvSetScanRspResponse;

typedef struct _drv_bluetooth_BleAdvStartResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleAdvStartResponse;

typedef struct _drv_bluetooth_BleAdvStopResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleAdvStopResponse;

typedef struct _drv_bluetooth_BleAdvDeleteResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleAdvDeleteResponse;

typedef struct _drv_bluetooth_BleGattCreateResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleGattCreateResponse;

typedef struct _drv_bluetooth_BleReadResponseResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleReadResponseResponse;

typedef struct _drv_bluetooth_BleWriteNotifyResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleWriteNotifyResponse;

typedef struct _drv_bluetooth_BleScanCreateResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleScanCreateResponse;

typedef struct _drv_bluetooth_BleScanStartResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleScanStartResponse;

typedef struct _drv_bluetooth_BleScanStopResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleScanStopResponse;

typedef struct _drv_bluetooth_BleScanDeleteResponse {
    drv_bluetooth_BleResult result;
} drv_bluetooth_BleScanDeleteResponse;

/* ---- 统一 RPC 请求 ---- */
typedef struct _drv_bluetooth_BleRpcRequest {
    uint32_t req_id;
    pb_size_t which_payload;
    union {
        drv_bluetooth_BleInitRequest init;
        drv_bluetooth_BleDeinitRequest deinit;
        drv_bluetooth_BleSetNameRequest set_name;
        drv_bluetooth_BleSetMaxMtuRequest set_max_mtu;
        drv_bluetooth_BleAdvCreateRequest adv_create;
        drv_bluetooth_BleAdvSetDataRequest adv_set_data;
        drv_bluetooth_BleAdvSetScanRspRequest adv_set_scan_rsp;
        drv_bluetooth_BleAdvStartRequest adv_start;
        drv_bluetooth_BleAdvStopRequest adv_stop;
        drv_bluetooth_BleAdvDeleteRequest adv_delete;
        drv_bluetooth_BleGattCreateRequest gatt_create;
        drv_bluetooth_BleReadResponseRequest read_response;
        drv_bluetooth_BleWriteNotifyRequest write_notify;
        drv_bluetooth_BleScanCreateRequest scan_create;
        drv_bluetooth_BleScanStartRequest scan_start;
        drv_bluetooth_BleScanStopRequest scan_stop;
        drv_bluetooth_BleScanDeleteRequest scan_delete;
    } payload;
} drv_bluetooth_BleRpcRequest;

/* ---- 统一 RPC 响应 ---- */
typedef struct _drv_bluetooth_BleRpcResponse {
    bool has_req_id;
    uint32_t req_id; /* 与请求匹配；事件上报时为 0 */
    pb_size_t which_payload;
    union {
        drv_bluetooth_BleInitResponse init;
        drv_bluetooth_BleDeinitResponse deinit;
        drv_bluetooth_BleSetNameResponse set_name;
        drv_bluetooth_BleSetMaxMtuResponse set_max_mtu;
        drv_bluetooth_BleAdvCreateResponse adv_create;
        drv_bluetooth_BleAdvSetDataResponse adv_set_data;
        drv_bluetooth_BleAdvSetScanRspResponse adv_set_scan_rsp;
        drv_bluetooth_BleAdvStartResponse adv_start;
        drv_bluetooth_BleAdvStopResponse adv_stop;
        drv_bluetooth_BleAdvDeleteResponse adv_delete;
        drv_bluetooth_BleGattCreateResponse gatt_create;
        drv_bluetooth_BleReadResponseResponse read_response;
        drv_bluetooth_BleWriteNotifyResponse write_notify;
        drv_bluetooth_BleScanCreateResponse scan_create;
        drv_bluetooth_BleScanStartResponse scan_start;
        drv_bluetooth_BleScanStopResponse scan_stop;
        drv_bluetooth_BleScanDeleteResponse scan_delete;
    } payload;
} drv_bluetooth_BleRpcResponse;

typedef PB_BYTES_ARRAY_T(1500) drv_bluetooth_BleEventNotify_packed_data_t;
/* ---- BLE 事件通知 (服务端 → 客户端, 通过 nb_notify 发送) ----
 event_type: luat_ble_event_t 枚举值
 packed_data 格式随 event_type 而定：
   CONN      → luat_ble_conn_ind_t
   DISCONN   → luat_ble_disconn_ind_t
   GATT_DONE → luat_ble_gatt_done_ind_t
   WRITE     → luat_ble_write_req_t + value 字节
   READ      → luat_ble_read_req_t
   READ_VALUE→ luat_ble_read_req_t + value 字节
   SCAN_REPORT → luat_ble_adv_req_t + adv_data 字节
   GATT_ITEM → luat_ble_gatt_pack() 输出
   其他事件  → 无 packed_data */
typedef struct _drv_bluetooth_BleEventNotify {
    uint32_t event_type;
    bool has_packed_data;
    drv_bluetooth_BleEventNotify_packed_data_t packed_data;
} drv_bluetooth_BleEventNotify;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _drv_bluetooth_BleResultCode_MIN drv_bluetooth_BleResultCode_BLE_RES_OK
#define _drv_bluetooth_BleResultCode_MAX drv_bluetooth_BleResultCode_BLE_RES_FAIL
#define _drv_bluetooth_BleResultCode_ARRAYSIZE ((drv_bluetooth_BleResultCode)(drv_bluetooth_BleResultCode_BLE_RES_FAIL+1))

#define drv_bluetooth_BleResult_code_ENUMTYPE drv_bluetooth_BleResultCode









































/* Initializer values for message structs */
#define drv_bluetooth_BleResult_init_default     {false, drv_bluetooth_BleResultCode_BLE_RES_OK, false, 0}
#define drv_bluetooth_BleAdvCfg_init_default     {false, 7u, false, 0u, false, 160u, false, 160u, false, 0u, false, 0u}
#define drv_bluetooth_BleScanCfg_init_default    {false, 0u, false, 0u, false, 16u, false, 16u}
#define drv_bluetooth_BleInitRequest_init_default {0}
#define drv_bluetooth_BleDeinitRequest_init_default {0}
#define drv_bluetooth_BleSetNameRequest_init_default {{0, {0}}}
#define drv_bluetooth_BleSetMaxMtuRequest_init_default {0}
#define drv_bluetooth_BleAdvCreateRequest_init_default {false, drv_bluetooth_BleAdvCfg_init_default}
#define drv_bluetooth_BleAdvSetDataRequest_init_default {{0, {0}}}
#define drv_bluetooth_BleAdvSetScanRspRequest_init_default {{0, {0}}}
#define drv_bluetooth_BleAdvStartRequest_init_default {0}
#define drv_bluetooth_BleAdvStopRequest_init_default {0}
#define drv_bluetooth_BleAdvDeleteRequest_init_default {0}
#define drv_bluetooth_BleGattCreateRequest_init_default {{0, {0}}}
#define drv_bluetooth_BleReadResponseRequest_init_default {0, 0, 0, {0, {0}}}
#define drv_bluetooth_BleWriteNotifyRequest_init_default {0, 0, 0, {0, {0}}}
#define drv_bluetooth_BleScanCreateRequest_init_default {false, drv_bluetooth_BleScanCfg_init_default}
#define drv_bluetooth_BleScanStartRequest_init_default {0}
#define drv_bluetooth_BleScanStopRequest_init_default {0}
#define drv_bluetooth_BleScanDeleteRequest_init_default {0}
#define drv_bluetooth_BleInitResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleDeinitResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleSetNameResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleSetMaxMtuResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleAdvCreateResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleAdvSetDataResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleAdvSetScanRspResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleAdvStartResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleAdvStopResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleAdvDeleteResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleGattCreateResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleReadResponseResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleWriteNotifyResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleScanCreateResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleScanStartResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleScanStopResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleScanDeleteResponse_init_default {drv_bluetooth_BleResult_init_default}
#define drv_bluetooth_BleRpcRequest_init_default {0, 0, {drv_bluetooth_BleInitRequest_init_default}}
#define drv_bluetooth_BleRpcResponse_init_default {false, 0u, 0, {drv_bluetooth_BleInitResponse_init_default}}
#define drv_bluetooth_BleEventNotify_init_default {0, false, {0, {0}}}
#define drv_bluetooth_BleResult_init_zero        {false, _drv_bluetooth_BleResultCode_MIN, false, 0}
#define drv_bluetooth_BleAdvCfg_init_zero        {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define drv_bluetooth_BleScanCfg_init_zero       {false, 0, false, 0, false, 0, false, 0}
#define drv_bluetooth_BleInitRequest_init_zero   {0}
#define drv_bluetooth_BleDeinitRequest_init_zero {0}
#define drv_bluetooth_BleSetNameRequest_init_zero {{0, {0}}}
#define drv_bluetooth_BleSetMaxMtuRequest_init_zero {0}
#define drv_bluetooth_BleAdvCreateRequest_init_zero {false, drv_bluetooth_BleAdvCfg_init_zero}
#define drv_bluetooth_BleAdvSetDataRequest_init_zero {{0, {0}}}
#define drv_bluetooth_BleAdvSetScanRspRequest_init_zero {{0, {0}}}
#define drv_bluetooth_BleAdvStartRequest_init_zero {0}
#define drv_bluetooth_BleAdvStopRequest_init_zero {0}
#define drv_bluetooth_BleAdvDeleteRequest_init_zero {0}
#define drv_bluetooth_BleGattCreateRequest_init_zero {{0, {0}}}
#define drv_bluetooth_BleReadResponseRequest_init_zero {0, 0, 0, {0, {0}}}
#define drv_bluetooth_BleWriteNotifyRequest_init_zero {0, 0, 0, {0, {0}}}
#define drv_bluetooth_BleScanCreateRequest_init_zero {false, drv_bluetooth_BleScanCfg_init_zero}
#define drv_bluetooth_BleScanStartRequest_init_zero {0}
#define drv_bluetooth_BleScanStopRequest_init_zero {0}
#define drv_bluetooth_BleScanDeleteRequest_init_zero {0}
#define drv_bluetooth_BleInitResponse_init_zero  {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleDeinitResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleSetNameResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleSetMaxMtuResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleAdvCreateResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleAdvSetDataResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleAdvSetScanRspResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleAdvStartResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleAdvStopResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleAdvDeleteResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleGattCreateResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleReadResponseResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleWriteNotifyResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleScanCreateResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleScanStartResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleScanStopResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleScanDeleteResponse_init_zero {drv_bluetooth_BleResult_init_zero}
#define drv_bluetooth_BleRpcRequest_init_zero    {0, 0, {drv_bluetooth_BleInitRequest_init_zero}}
#define drv_bluetooth_BleRpcResponse_init_zero   {false, 0, 0, {drv_bluetooth_BleInitResponse_init_zero}}
#define drv_bluetooth_BleEventNotify_init_zero   {0, false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define drv_bluetooth_BleResult_code_tag         1
#define drv_bluetooth_BleResult_os_errno_tag     2
#define drv_bluetooth_BleAdvCfg_channel_map_tag  1
#define drv_bluetooth_BleAdvCfg_addr_mode_tag    2
#define drv_bluetooth_BleAdvCfg_intv_min_tag     3
#define drv_bluetooth_BleAdvCfg_intv_max_tag     4
#define drv_bluetooth_BleAdvCfg_adv_prop_tag     5
#define drv_bluetooth_BleAdvCfg_adv_type_tag     6
#define drv_bluetooth_BleScanCfg_scan_type_tag   1
#define drv_bluetooth_BleScanCfg_addr_mode_tag   2
#define drv_bluetooth_BleScanCfg_scan_interval_tag 3
#define drv_bluetooth_BleScanCfg_scan_window_tag 4
#define drv_bluetooth_BleSetNameRequest_name_tag 1
#define drv_bluetooth_BleSetMaxMtuRequest_max_mtu_tag 1
#define drv_bluetooth_BleAdvCreateRequest_cfg_tag 1
#define drv_bluetooth_BleAdvSetDataRequest_data_tag 1
#define drv_bluetooth_BleAdvSetScanRspRequest_data_tag 1
#define drv_bluetooth_BleGattCreateRequest_packed_gatt_tag 1
#define drv_bluetooth_BleReadResponseRequest_conn_idx_tag 1
#define drv_bluetooth_BleReadResponseRequest_service_id_tag 2
#define drv_bluetooth_BleReadResponseRequest_att_handle_tag 3
#define drv_bluetooth_BleReadResponseRequest_data_tag 4
#define drv_bluetooth_BleWriteNotifyRequest_conn_idx_tag 1
#define drv_bluetooth_BleWriteNotifyRequest_service_id_tag 2
#define drv_bluetooth_BleWriteNotifyRequest_att_handle_tag 3
#define drv_bluetooth_BleWriteNotifyRequest_data_tag 4
#define drv_bluetooth_BleScanCreateRequest_cfg_tag 1
#define drv_bluetooth_BleInitResponse_result_tag 1
#define drv_bluetooth_BleDeinitResponse_result_tag 1
#define drv_bluetooth_BleSetNameResponse_result_tag 1
#define drv_bluetooth_BleSetMaxMtuResponse_result_tag 1
#define drv_bluetooth_BleAdvCreateResponse_result_tag 1
#define drv_bluetooth_BleAdvSetDataResponse_result_tag 1
#define drv_bluetooth_BleAdvSetScanRspResponse_result_tag 1
#define drv_bluetooth_BleAdvStartResponse_result_tag 1
#define drv_bluetooth_BleAdvStopResponse_result_tag 1
#define drv_bluetooth_BleAdvDeleteResponse_result_tag 1
#define drv_bluetooth_BleGattCreateResponse_result_tag 1
#define drv_bluetooth_BleReadResponseResponse_result_tag 1
#define drv_bluetooth_BleWriteNotifyResponse_result_tag 1
#define drv_bluetooth_BleScanCreateResponse_result_tag 1
#define drv_bluetooth_BleScanStartResponse_result_tag 1
#define drv_bluetooth_BleScanStopResponse_result_tag 1
#define drv_bluetooth_BleScanDeleteResponse_result_tag 1
#define drv_bluetooth_BleRpcRequest_req_id_tag   1
#define drv_bluetooth_BleRpcRequest_init_tag     10
#define drv_bluetooth_BleRpcRequest_deinit_tag   11
#define drv_bluetooth_BleRpcRequest_set_name_tag 12
#define drv_bluetooth_BleRpcRequest_set_max_mtu_tag 13
#define drv_bluetooth_BleRpcRequest_adv_create_tag 20
#define drv_bluetooth_BleRpcRequest_adv_set_data_tag 21
#define drv_bluetooth_BleRpcRequest_adv_set_scan_rsp_tag 22
#define drv_bluetooth_BleRpcRequest_adv_start_tag 23
#define drv_bluetooth_BleRpcRequest_adv_stop_tag 24
#define drv_bluetooth_BleRpcRequest_adv_delete_tag 25
#define drv_bluetooth_BleRpcRequest_gatt_create_tag 30
#define drv_bluetooth_BleRpcRequest_read_response_tag 31
#define drv_bluetooth_BleRpcRequest_write_notify_tag 32
#define drv_bluetooth_BleRpcRequest_scan_create_tag 40
#define drv_bluetooth_BleRpcRequest_scan_start_tag 41
#define drv_bluetooth_BleRpcRequest_scan_stop_tag 42
#define drv_bluetooth_BleRpcRequest_scan_delete_tag 43
#define drv_bluetooth_BleRpcResponse_req_id_tag  1
#define drv_bluetooth_BleRpcResponse_init_tag    10
#define drv_bluetooth_BleRpcResponse_deinit_tag  11
#define drv_bluetooth_BleRpcResponse_set_name_tag 12
#define drv_bluetooth_BleRpcResponse_set_max_mtu_tag 13
#define drv_bluetooth_BleRpcResponse_adv_create_tag 20
#define drv_bluetooth_BleRpcResponse_adv_set_data_tag 21
#define drv_bluetooth_BleRpcResponse_adv_set_scan_rsp_tag 22
#define drv_bluetooth_BleRpcResponse_adv_start_tag 23
#define drv_bluetooth_BleRpcResponse_adv_stop_tag 24
#define drv_bluetooth_BleRpcResponse_adv_delete_tag 25
#define drv_bluetooth_BleRpcResponse_gatt_create_tag 30
#define drv_bluetooth_BleRpcResponse_read_response_tag 31
#define drv_bluetooth_BleRpcResponse_write_notify_tag 32
#define drv_bluetooth_BleRpcResponse_scan_create_tag 40
#define drv_bluetooth_BleRpcResponse_scan_start_tag 41
#define drv_bluetooth_BleRpcResponse_scan_stop_tag 42
#define drv_bluetooth_BleRpcResponse_scan_delete_tag 43
#define drv_bluetooth_BleEventNotify_event_type_tag 1
#define drv_bluetooth_BleEventNotify_packed_data_tag 2

/* Struct field encoding specification for nanopb */
#define drv_bluetooth_BleResult_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    code,              1) \
X(a, STATIC,   OPTIONAL, INT32,    os_errno,          2)
#define drv_bluetooth_BleResult_CALLBACK NULL
#define drv_bluetooth_BleResult_DEFAULT (const pb_byte_t*)"\x10\x00\x00"

#define drv_bluetooth_BleAdvCfg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   channel_map,       1) \
X(a, STATIC,   OPTIONAL, UINT32,   addr_mode,         2) \
X(a, STATIC,   OPTIONAL, UINT32,   intv_min,          3) \
X(a, STATIC,   OPTIONAL, UINT32,   intv_max,          4) \
X(a, STATIC,   OPTIONAL, UINT32,   adv_prop,          5) \
X(a, STATIC,   OPTIONAL, UINT32,   adv_type,          6)
#define drv_bluetooth_BleAdvCfg_CALLBACK NULL
#define drv_bluetooth_BleAdvCfg_DEFAULT (const pb_byte_t*)"\x08\x07\x10\x00\x18\xa0\x01\x20\xa0\x01\x28\x00\x30\x00\x00"

#define drv_bluetooth_BleScanCfg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   scan_type,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   addr_mode,         2) \
X(a, STATIC,   OPTIONAL, UINT32,   scan_interval,     3) \
X(a, STATIC,   OPTIONAL, UINT32,   scan_window,       4)
#define drv_bluetooth_BleScanCfg_CALLBACK NULL
#define drv_bluetooth_BleScanCfg_DEFAULT (const pb_byte_t*)"\x08\x00\x10\x00\x18\x10\x20\x10\x00"

#define drv_bluetooth_BleInitRequest_FIELDLIST(X, a) \

#define drv_bluetooth_BleInitRequest_CALLBACK NULL
#define drv_bluetooth_BleInitRequest_DEFAULT NULL

#define drv_bluetooth_BleDeinitRequest_FIELDLIST(X, a) \

#define drv_bluetooth_BleDeinitRequest_CALLBACK NULL
#define drv_bluetooth_BleDeinitRequest_DEFAULT NULL

#define drv_bluetooth_BleSetNameRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    name,              1)
#define drv_bluetooth_BleSetNameRequest_CALLBACK NULL
#define drv_bluetooth_BleSetNameRequest_DEFAULT NULL

#define drv_bluetooth_BleSetMaxMtuRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   max_mtu,           1)
#define drv_bluetooth_BleSetMaxMtuRequest_CALLBACK NULL
#define drv_bluetooth_BleSetMaxMtuRequest_DEFAULT NULL

#define drv_bluetooth_BleAdvCreateRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cfg,               1)
#define drv_bluetooth_BleAdvCreateRequest_CALLBACK NULL
#define drv_bluetooth_BleAdvCreateRequest_DEFAULT NULL
#define drv_bluetooth_BleAdvCreateRequest_cfg_MSGTYPE drv_bluetooth_BleAdvCfg

#define drv_bluetooth_BleAdvSetDataRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    data,              1)
#define drv_bluetooth_BleAdvSetDataRequest_CALLBACK NULL
#define drv_bluetooth_BleAdvSetDataRequest_DEFAULT NULL

#define drv_bluetooth_BleAdvSetScanRspRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    data,              1)
#define drv_bluetooth_BleAdvSetScanRspRequest_CALLBACK NULL
#define drv_bluetooth_BleAdvSetScanRspRequest_DEFAULT NULL

#define drv_bluetooth_BleAdvStartRequest_FIELDLIST(X, a) \

#define drv_bluetooth_BleAdvStartRequest_CALLBACK NULL
#define drv_bluetooth_BleAdvStartRequest_DEFAULT NULL

#define drv_bluetooth_BleAdvStopRequest_FIELDLIST(X, a) \

#define drv_bluetooth_BleAdvStopRequest_CALLBACK NULL
#define drv_bluetooth_BleAdvStopRequest_DEFAULT NULL

#define drv_bluetooth_BleAdvDeleteRequest_FIELDLIST(X, a) \

#define drv_bluetooth_BleAdvDeleteRequest_CALLBACK NULL
#define drv_bluetooth_BleAdvDeleteRequest_DEFAULT NULL

#define drv_bluetooth_BleGattCreateRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    packed_gatt,       1)
#define drv_bluetooth_BleGattCreateRequest_CALLBACK NULL
#define drv_bluetooth_BleGattCreateRequest_DEFAULT NULL

#define drv_bluetooth_BleReadResponseRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   conn_idx,          1) \
X(a, STATIC,   REQUIRED, UINT32,   service_id,        2) \
X(a, STATIC,   REQUIRED, UINT32,   att_handle,        3) \
X(a, STATIC,   REQUIRED, BYTES,    data,              4)
#define drv_bluetooth_BleReadResponseRequest_CALLBACK NULL
#define drv_bluetooth_BleReadResponseRequest_DEFAULT NULL

#define drv_bluetooth_BleWriteNotifyRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   conn_idx,          1) \
X(a, STATIC,   REQUIRED, UINT32,   service_id,        2) \
X(a, STATIC,   REQUIRED, UINT32,   att_handle,        3) \
X(a, STATIC,   REQUIRED, BYTES,    data,              4)
#define drv_bluetooth_BleWriteNotifyRequest_CALLBACK NULL
#define drv_bluetooth_BleWriteNotifyRequest_DEFAULT NULL

#define drv_bluetooth_BleScanCreateRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cfg,               1)
#define drv_bluetooth_BleScanCreateRequest_CALLBACK NULL
#define drv_bluetooth_BleScanCreateRequest_DEFAULT NULL
#define drv_bluetooth_BleScanCreateRequest_cfg_MSGTYPE drv_bluetooth_BleScanCfg

#define drv_bluetooth_BleScanStartRequest_FIELDLIST(X, a) \

#define drv_bluetooth_BleScanStartRequest_CALLBACK NULL
#define drv_bluetooth_BleScanStartRequest_DEFAULT NULL

#define drv_bluetooth_BleScanStopRequest_FIELDLIST(X, a) \

#define drv_bluetooth_BleScanStopRequest_CALLBACK NULL
#define drv_bluetooth_BleScanStopRequest_DEFAULT NULL

#define drv_bluetooth_BleScanDeleteRequest_FIELDLIST(X, a) \

#define drv_bluetooth_BleScanDeleteRequest_CALLBACK NULL
#define drv_bluetooth_BleScanDeleteRequest_DEFAULT NULL

#define drv_bluetooth_BleInitResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleInitResponse_CALLBACK NULL
#define drv_bluetooth_BleInitResponse_DEFAULT NULL
#define drv_bluetooth_BleInitResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleDeinitResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleDeinitResponse_CALLBACK NULL
#define drv_bluetooth_BleDeinitResponse_DEFAULT NULL
#define drv_bluetooth_BleDeinitResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleSetNameResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleSetNameResponse_CALLBACK NULL
#define drv_bluetooth_BleSetNameResponse_DEFAULT NULL
#define drv_bluetooth_BleSetNameResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleSetMaxMtuResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleSetMaxMtuResponse_CALLBACK NULL
#define drv_bluetooth_BleSetMaxMtuResponse_DEFAULT NULL
#define drv_bluetooth_BleSetMaxMtuResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleAdvCreateResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleAdvCreateResponse_CALLBACK NULL
#define drv_bluetooth_BleAdvCreateResponse_DEFAULT NULL
#define drv_bluetooth_BleAdvCreateResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleAdvSetDataResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleAdvSetDataResponse_CALLBACK NULL
#define drv_bluetooth_BleAdvSetDataResponse_DEFAULT NULL
#define drv_bluetooth_BleAdvSetDataResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleAdvSetScanRspResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleAdvSetScanRspResponse_CALLBACK NULL
#define drv_bluetooth_BleAdvSetScanRspResponse_DEFAULT NULL
#define drv_bluetooth_BleAdvSetScanRspResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleAdvStartResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleAdvStartResponse_CALLBACK NULL
#define drv_bluetooth_BleAdvStartResponse_DEFAULT NULL
#define drv_bluetooth_BleAdvStartResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleAdvStopResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleAdvStopResponse_CALLBACK NULL
#define drv_bluetooth_BleAdvStopResponse_DEFAULT NULL
#define drv_bluetooth_BleAdvStopResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleAdvDeleteResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleAdvDeleteResponse_CALLBACK NULL
#define drv_bluetooth_BleAdvDeleteResponse_DEFAULT NULL
#define drv_bluetooth_BleAdvDeleteResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleGattCreateResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleGattCreateResponse_CALLBACK NULL
#define drv_bluetooth_BleGattCreateResponse_DEFAULT NULL
#define drv_bluetooth_BleGattCreateResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleReadResponseResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleReadResponseResponse_CALLBACK NULL
#define drv_bluetooth_BleReadResponseResponse_DEFAULT NULL
#define drv_bluetooth_BleReadResponseResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleWriteNotifyResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleWriteNotifyResponse_CALLBACK NULL
#define drv_bluetooth_BleWriteNotifyResponse_DEFAULT NULL
#define drv_bluetooth_BleWriteNotifyResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleScanCreateResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleScanCreateResponse_CALLBACK NULL
#define drv_bluetooth_BleScanCreateResponse_DEFAULT NULL
#define drv_bluetooth_BleScanCreateResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleScanStartResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleScanStartResponse_CALLBACK NULL
#define drv_bluetooth_BleScanStartResponse_DEFAULT NULL
#define drv_bluetooth_BleScanStartResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleScanStopResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleScanStopResponse_CALLBACK NULL
#define drv_bluetooth_BleScanStopResponse_DEFAULT NULL
#define drv_bluetooth_BleScanStopResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleScanDeleteResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_bluetooth_BleScanDeleteResponse_CALLBACK NULL
#define drv_bluetooth_BleScanDeleteResponse_DEFAULT NULL
#define drv_bluetooth_BleScanDeleteResponse_result_MSGTYPE drv_bluetooth_BleResult

#define drv_bluetooth_BleRpcRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   req_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,init,payload.init),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,deinit,payload.deinit),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_name,payload.set_name),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_max_mtu,payload.set_max_mtu),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_create,payload.adv_create),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_set_data,payload.adv_set_data),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_set_scan_rsp,payload.adv_set_scan_rsp),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_start,payload.adv_start),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_stop,payload.adv_stop),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_delete,payload.adv_delete),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gatt_create,payload.gatt_create),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,read_response,payload.read_response),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,write_notify,payload.write_notify),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scan_create,payload.scan_create),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scan_start,payload.scan_start),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scan_stop,payload.scan_stop),  42) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scan_delete,payload.scan_delete),  43)
#define drv_bluetooth_BleRpcRequest_CALLBACK NULL
#define drv_bluetooth_BleRpcRequest_DEFAULT NULL
#define drv_bluetooth_BleRpcRequest_payload_init_MSGTYPE drv_bluetooth_BleInitRequest
#define drv_bluetooth_BleRpcRequest_payload_deinit_MSGTYPE drv_bluetooth_BleDeinitRequest
#define drv_bluetooth_BleRpcRequest_payload_set_name_MSGTYPE drv_bluetooth_BleSetNameRequest
#define drv_bluetooth_BleRpcRequest_payload_set_max_mtu_MSGTYPE drv_bluetooth_BleSetMaxMtuRequest
#define drv_bluetooth_BleRpcRequest_payload_adv_create_MSGTYPE drv_bluetooth_BleAdvCreateRequest
#define drv_bluetooth_BleRpcRequest_payload_adv_set_data_MSGTYPE drv_bluetooth_BleAdvSetDataRequest
#define drv_bluetooth_BleRpcRequest_payload_adv_set_scan_rsp_MSGTYPE drv_bluetooth_BleAdvSetScanRspRequest
#define drv_bluetooth_BleRpcRequest_payload_adv_start_MSGTYPE drv_bluetooth_BleAdvStartRequest
#define drv_bluetooth_BleRpcRequest_payload_adv_stop_MSGTYPE drv_bluetooth_BleAdvStopRequest
#define drv_bluetooth_BleRpcRequest_payload_adv_delete_MSGTYPE drv_bluetooth_BleAdvDeleteRequest
#define drv_bluetooth_BleRpcRequest_payload_gatt_create_MSGTYPE drv_bluetooth_BleGattCreateRequest
#define drv_bluetooth_BleRpcRequest_payload_read_response_MSGTYPE drv_bluetooth_BleReadResponseRequest
#define drv_bluetooth_BleRpcRequest_payload_write_notify_MSGTYPE drv_bluetooth_BleWriteNotifyRequest
#define drv_bluetooth_BleRpcRequest_payload_scan_create_MSGTYPE drv_bluetooth_BleScanCreateRequest
#define drv_bluetooth_BleRpcRequest_payload_scan_start_MSGTYPE drv_bluetooth_BleScanStartRequest
#define drv_bluetooth_BleRpcRequest_payload_scan_stop_MSGTYPE drv_bluetooth_BleScanStopRequest
#define drv_bluetooth_BleRpcRequest_payload_scan_delete_MSGTYPE drv_bluetooth_BleScanDeleteRequest

#define drv_bluetooth_BleRpcResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   req_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,init,payload.init),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,deinit,payload.deinit),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_name,payload.set_name),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_max_mtu,payload.set_max_mtu),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_create,payload.adv_create),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_set_data,payload.adv_set_data),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_set_scan_rsp,payload.adv_set_scan_rsp),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_start,payload.adv_start),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_stop,payload.adv_stop),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adv_delete,payload.adv_delete),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gatt_create,payload.gatt_create),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,read_response,payload.read_response),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,write_notify,payload.write_notify),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scan_create,payload.scan_create),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scan_start,payload.scan_start),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scan_stop,payload.scan_stop),  42) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scan_delete,payload.scan_delete),  43)
#define drv_bluetooth_BleRpcResponse_CALLBACK NULL
#define drv_bluetooth_BleRpcResponse_DEFAULT (const pb_byte_t*)"\x08\x00\x00"
#define drv_bluetooth_BleRpcResponse_payload_init_MSGTYPE drv_bluetooth_BleInitResponse
#define drv_bluetooth_BleRpcResponse_payload_deinit_MSGTYPE drv_bluetooth_BleDeinitResponse
#define drv_bluetooth_BleRpcResponse_payload_set_name_MSGTYPE drv_bluetooth_BleSetNameResponse
#define drv_bluetooth_BleRpcResponse_payload_set_max_mtu_MSGTYPE drv_bluetooth_BleSetMaxMtuResponse
#define drv_bluetooth_BleRpcResponse_payload_adv_create_MSGTYPE drv_bluetooth_BleAdvCreateResponse
#define drv_bluetooth_BleRpcResponse_payload_adv_set_data_MSGTYPE drv_bluetooth_BleAdvSetDataResponse
#define drv_bluetooth_BleRpcResponse_payload_adv_set_scan_rsp_MSGTYPE drv_bluetooth_BleAdvSetScanRspResponse
#define drv_bluetooth_BleRpcResponse_payload_adv_start_MSGTYPE drv_bluetooth_BleAdvStartResponse
#define drv_bluetooth_BleRpcResponse_payload_adv_stop_MSGTYPE drv_bluetooth_BleAdvStopResponse
#define drv_bluetooth_BleRpcResponse_payload_adv_delete_MSGTYPE drv_bluetooth_BleAdvDeleteResponse
#define drv_bluetooth_BleRpcResponse_payload_gatt_create_MSGTYPE drv_bluetooth_BleGattCreateResponse
#define drv_bluetooth_BleRpcResponse_payload_read_response_MSGTYPE drv_bluetooth_BleReadResponseResponse
#define drv_bluetooth_BleRpcResponse_payload_write_notify_MSGTYPE drv_bluetooth_BleWriteNotifyResponse
#define drv_bluetooth_BleRpcResponse_payload_scan_create_MSGTYPE drv_bluetooth_BleScanCreateResponse
#define drv_bluetooth_BleRpcResponse_payload_scan_start_MSGTYPE drv_bluetooth_BleScanStartResponse
#define drv_bluetooth_BleRpcResponse_payload_scan_stop_MSGTYPE drv_bluetooth_BleScanStopResponse
#define drv_bluetooth_BleRpcResponse_payload_scan_delete_MSGTYPE drv_bluetooth_BleScanDeleteResponse

#define drv_bluetooth_BleEventNotify_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   event_type,        1) \
X(a, STATIC,   OPTIONAL, BYTES,    packed_data,       2)
#define drv_bluetooth_BleEventNotify_CALLBACK NULL
#define drv_bluetooth_BleEventNotify_DEFAULT NULL

extern const pb_msgdesc_t drv_bluetooth_BleResult_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvCfg_msg;
extern const pb_msgdesc_t drv_bluetooth_BleScanCfg_msg;
extern const pb_msgdesc_t drv_bluetooth_BleInitRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleDeinitRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleSetNameRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleSetMaxMtuRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvCreateRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvSetDataRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvSetScanRspRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvStartRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvStopRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvDeleteRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleGattCreateRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleReadResponseRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleWriteNotifyRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleScanCreateRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleScanStartRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleScanStopRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleScanDeleteRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleInitResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleDeinitResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleSetNameResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleSetMaxMtuResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvCreateResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvSetDataResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvSetScanRspResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvStartResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvStopResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleAdvDeleteResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleGattCreateResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleReadResponseResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleWriteNotifyResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleScanCreateResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleScanStartResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleScanStopResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleScanDeleteResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleRpcRequest_msg;
extern const pb_msgdesc_t drv_bluetooth_BleRpcResponse_msg;
extern const pb_msgdesc_t drv_bluetooth_BleEventNotify_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define drv_bluetooth_BleResult_fields &drv_bluetooth_BleResult_msg
#define drv_bluetooth_BleAdvCfg_fields &drv_bluetooth_BleAdvCfg_msg
#define drv_bluetooth_BleScanCfg_fields &drv_bluetooth_BleScanCfg_msg
#define drv_bluetooth_BleInitRequest_fields &drv_bluetooth_BleInitRequest_msg
#define drv_bluetooth_BleDeinitRequest_fields &drv_bluetooth_BleDeinitRequest_msg
#define drv_bluetooth_BleSetNameRequest_fields &drv_bluetooth_BleSetNameRequest_msg
#define drv_bluetooth_BleSetMaxMtuRequest_fields &drv_bluetooth_BleSetMaxMtuRequest_msg
#define drv_bluetooth_BleAdvCreateRequest_fields &drv_bluetooth_BleAdvCreateRequest_msg
#define drv_bluetooth_BleAdvSetDataRequest_fields &drv_bluetooth_BleAdvSetDataRequest_msg
#define drv_bluetooth_BleAdvSetScanRspRequest_fields &drv_bluetooth_BleAdvSetScanRspRequest_msg
#define drv_bluetooth_BleAdvStartRequest_fields &drv_bluetooth_BleAdvStartRequest_msg
#define drv_bluetooth_BleAdvStopRequest_fields &drv_bluetooth_BleAdvStopRequest_msg
#define drv_bluetooth_BleAdvDeleteRequest_fields &drv_bluetooth_BleAdvDeleteRequest_msg
#define drv_bluetooth_BleGattCreateRequest_fields &drv_bluetooth_BleGattCreateRequest_msg
#define drv_bluetooth_BleReadResponseRequest_fields &drv_bluetooth_BleReadResponseRequest_msg
#define drv_bluetooth_BleWriteNotifyRequest_fields &drv_bluetooth_BleWriteNotifyRequest_msg
#define drv_bluetooth_BleScanCreateRequest_fields &drv_bluetooth_BleScanCreateRequest_msg
#define drv_bluetooth_BleScanStartRequest_fields &drv_bluetooth_BleScanStartRequest_msg
#define drv_bluetooth_BleScanStopRequest_fields &drv_bluetooth_BleScanStopRequest_msg
#define drv_bluetooth_BleScanDeleteRequest_fields &drv_bluetooth_BleScanDeleteRequest_msg
#define drv_bluetooth_BleInitResponse_fields &drv_bluetooth_BleInitResponse_msg
#define drv_bluetooth_BleDeinitResponse_fields &drv_bluetooth_BleDeinitResponse_msg
#define drv_bluetooth_BleSetNameResponse_fields &drv_bluetooth_BleSetNameResponse_msg
#define drv_bluetooth_BleSetMaxMtuResponse_fields &drv_bluetooth_BleSetMaxMtuResponse_msg
#define drv_bluetooth_BleAdvCreateResponse_fields &drv_bluetooth_BleAdvCreateResponse_msg
#define drv_bluetooth_BleAdvSetDataResponse_fields &drv_bluetooth_BleAdvSetDataResponse_msg
#define drv_bluetooth_BleAdvSetScanRspResponse_fields &drv_bluetooth_BleAdvSetScanRspResponse_msg
#define drv_bluetooth_BleAdvStartResponse_fields &drv_bluetooth_BleAdvStartResponse_msg
#define drv_bluetooth_BleAdvStopResponse_fields &drv_bluetooth_BleAdvStopResponse_msg
#define drv_bluetooth_BleAdvDeleteResponse_fields &drv_bluetooth_BleAdvDeleteResponse_msg
#define drv_bluetooth_BleGattCreateResponse_fields &drv_bluetooth_BleGattCreateResponse_msg
#define drv_bluetooth_BleReadResponseResponse_fields &drv_bluetooth_BleReadResponseResponse_msg
#define drv_bluetooth_BleWriteNotifyResponse_fields &drv_bluetooth_BleWriteNotifyResponse_msg
#define drv_bluetooth_BleScanCreateResponse_fields &drv_bluetooth_BleScanCreateResponse_msg
#define drv_bluetooth_BleScanStartResponse_fields &drv_bluetooth_BleScanStartResponse_msg
#define drv_bluetooth_BleScanStopResponse_fields &drv_bluetooth_BleScanStopResponse_msg
#define drv_bluetooth_BleScanDeleteResponse_fields &drv_bluetooth_BleScanDeleteResponse_msg
#define drv_bluetooth_BleRpcRequest_fields &drv_bluetooth_BleRpcRequest_msg
#define drv_bluetooth_BleRpcResponse_fields &drv_bluetooth_BleRpcResponse_msg
#define drv_bluetooth_BleEventNotify_fields &drv_bluetooth_BleEventNotify_msg

/* Maximum encoded size of messages (where known) */
#define DRV_BLUETOOTH_DRV_BLUETOOTH_PB_H_MAX_SIZE drv_bluetooth_BleEventNotify_size
#define drv_bluetooth_BleAdvCfg_size             36
#define drv_bluetooth_BleAdvCreateRequest_size   38
#define drv_bluetooth_BleAdvCreateResponse_size  16
#define drv_bluetooth_BleAdvDeleteRequest_size   0
#define drv_bluetooth_BleAdvDeleteResponse_size  16
#define drv_bluetooth_BleAdvSetDataRequest_size  33
#define drv_bluetooth_BleAdvSetDataResponse_size 16
#define drv_bluetooth_BleAdvSetScanRspRequest_size 33
#define drv_bluetooth_BleAdvSetScanRspResponse_size 16
#define drv_bluetooth_BleAdvStartRequest_size    0
#define drv_bluetooth_BleAdvStartResponse_size   16
#define drv_bluetooth_BleAdvStopRequest_size     0
#define drv_bluetooth_BleAdvStopResponse_size    16
#define drv_bluetooth_BleDeinitRequest_size      0
#define drv_bluetooth_BleDeinitResponse_size     16
#define drv_bluetooth_BleEventNotify_size        1509
#define drv_bluetooth_BleGattCreateRequest_size  515
#define drv_bluetooth_BleGattCreateResponse_size 16
#define drv_bluetooth_BleInitRequest_size        0
#define drv_bluetooth_BleInitResponse_size       16
#define drv_bluetooth_BleReadResponseRequest_size 533
#define drv_bluetooth_BleReadResponseResponse_size 16
#define drv_bluetooth_BleResult_size             14
#define drv_bluetooth_BleRpcRequest_size         543
#define drv_bluetooth_BleRpcResponse_size        25
#define drv_bluetooth_BleScanCfg_size            24
#define drv_bluetooth_BleScanCreateRequest_size  26
#define drv_bluetooth_BleScanCreateResponse_size 16
#define drv_bluetooth_BleScanDeleteRequest_size  0
#define drv_bluetooth_BleScanDeleteResponse_size 16
#define drv_bluetooth_BleScanStartRequest_size   0
#define drv_bluetooth_BleScanStartResponse_size  16
#define drv_bluetooth_BleScanStopRequest_size    0
#define drv_bluetooth_BleScanStopResponse_size   16
#define drv_bluetooth_BleSetMaxMtuRequest_size   6
#define drv_bluetooth_BleSetMaxMtuResponse_size  16
#define drv_bluetooth_BleSetNameRequest_size     34
#define drv_bluetooth_BleSetNameResponse_size    16
#define drv_bluetooth_BleWriteNotifyRequest_size 533
#define drv_bluetooth_BleWriteNotifyResponse_size 16

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
