/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DRV_WLAN_DRV_WLAN_PB_H_INCLUDED
#define PB_DRV_WLAN_DRV_WLAN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 通用返回码 */
typedef enum _drv_wlan_WlanResultCode {
    drv_wlan_WlanResultCode_WLAN_RES_OK = 0,
    drv_wlan_WlanResultCode_WLAN_RES_EINVAL = 1,
    drv_wlan_WlanResultCode_WLAN_RES_FAIL = 255
} drv_wlan_WlanResultCode;

/* Struct definitions */
typedef struct _drv_wlan_WlanResult {
    bool has_code;
    drv_wlan_WlanResultCode code;
    bool has_os_errno;
    int32_t os_errno;
} drv_wlan_WlanResult;

/* 初始化 WLAN（对应 luat_wlan_init）
 mode: 1=STA, 2=AP, 3=APSTA（对应 LUAT_WLAN_MODE_*） */
typedef struct _drv_wlan_WlanInitRequest {
    bool has_mode;
    uint32_t mode;
} drv_wlan_WlanInitRequest;

typedef struct _drv_wlan_WlanInitResponse {
    drv_wlan_WlanResult result;
} drv_wlan_WlanInitResponse;

typedef PB_BYTES_ARRAY_T(6) drv_wlan_WlanConnectRequest_bssid_t;
/* STA 连接（对应 luat_wlan_connect） */
typedef struct _drv_wlan_WlanConnectRequest {
    char ssid[36];
    bool has_password;
    char password[64];
    bool has_bssid;
    drv_wlan_WlanConnectRequest_bssid_t bssid;
    bool has_authmode;
    uint32_t authmode;
    bool has_auto_reconnection;
    bool auto_reconnection;
    bool has_auto_reconnection_delay_sec;
    uint32_t auto_reconnection_delay_sec;
} drv_wlan_WlanConnectRequest;

typedef struct _drv_wlan_WlanConnectResponse {
    drv_wlan_WlanResult result;
} drv_wlan_WlanConnectResponse;

/* STA 断开（对应 luat_wlan_disconnect） */
typedef struct _drv_wlan_WlanDisconnectRequest {
    char dummy_field;
} drv_wlan_WlanDisconnectRequest;

typedef struct _drv_wlan_WlanDisconnectResponse {
    drv_wlan_WlanResult result;
} drv_wlan_WlanDisconnectResponse;

typedef PB_BYTES_ARRAY_T(4) drv_wlan_WlanApStartRequest_gateway_t;
typedef PB_BYTES_ARRAY_T(4) drv_wlan_WlanApStartRequest_netmask_t;
/* AP 启动（对应 luat_wlan_ap_start） */
typedef struct _drv_wlan_WlanApStartRequest {
    char ssid[36];
    bool has_password;
    char password[64];
    bool has_channel;
    uint32_t channel;
    bool has_encrypt;
    uint32_t encrypt;
    bool has_hidden;
    bool hidden;
    bool has_max_conn;
    uint32_t max_conn;
    bool has_gateway;
    drv_wlan_WlanApStartRequest_gateway_t gateway;
    bool has_netmask;
    drv_wlan_WlanApStartRequest_netmask_t netmask;
} drv_wlan_WlanApStartRequest;

typedef struct _drv_wlan_WlanApStartResponse {
    drv_wlan_WlanResult result;
} drv_wlan_WlanApStartResponse;

/* AP 停止（对应 luat_wlan_ap_stop） */
typedef struct _drv_wlan_WlanApStopRequest {
    char dummy_field;
} drv_wlan_WlanApStopRequest;

typedef struct _drv_wlan_WlanApStopResponse {
    drv_wlan_WlanResult result;
} drv_wlan_WlanApStopResponse;

/* 发起扫描（对应 luat_wlan_scan） */
typedef struct _drv_wlan_WlanScanRequest {
    char dummy_field;
} drv_wlan_WlanScanRequest;

typedef struct _drv_wlan_WlanScanResponse {
    drv_wlan_WlanResult result;
} drv_wlan_WlanScanResponse;

/* 扫描结果 NOTIFY（Slave → Host 异步通知, rpc_id=0x0301） */
typedef PB_BYTES_ARRAY_T(2048) drv_wlan_WlanScanResultNotify_data_t;
typedef struct _drv_wlan_WlanScanResultNotify {
    uint32_t count;
    drv_wlan_WlanScanResultNotify_data_t data;
} drv_wlan_WlanScanResultNotify;

/* STA 事件 NOTIFY（Slave → Host 异步通知, rpc_id=0x0302） */
typedef PB_BYTES_ARRAY_T(6) drv_wlan_WlanStaIncNotify_bssid_t;
typedef struct _drv_wlan_WlanStaIncNotify {
    char event[16];
    bool has_ssid;
    char ssid[36];
    bool has_bssid;
    drv_wlan_WlanStaIncNotify_bssid_t bssid;
    bool has_reason;
    uint32_t reason;
} drv_wlan_WlanStaIncNotify;

/* IP 就绪 NOTIFY（Slave → Host 异步通知, rpc_id=0x0303） */
typedef struct _drv_wlan_WlanIpReadyNotify {
    bool has_ip;
    char ip[16];
    bool has_adapter;
    uint32_t adapter;
} drv_wlan_WlanIpReadyNotify;

/* AP 热点事件 NOTIFY（Slave → Host 异步通知, rpc_id=0x0304） */
typedef PB_BYTES_ARRAY_T(6) drv_wlan_WlanApIncNotify_mac_t;
typedef struct _drv_wlan_WlanApIncNotify {
    char event[16];
    bool has_mac;
    drv_wlan_WlanApIncNotify_mac_t mac;
} drv_wlan_WlanApIncNotify;

/* 统一 RPC 请求 */
typedef struct _drv_wlan_WlanRpcRequest {
    uint32_t req_id;
    pb_size_t which_payload;
    union {
        drv_wlan_WlanInitRequest init;
        drv_wlan_WlanConnectRequest connect;
        drv_wlan_WlanDisconnectRequest disconnect;
        drv_wlan_WlanApStartRequest ap_start;
        drv_wlan_WlanApStopRequest ap_stop;
        drv_wlan_WlanScanRequest scan;
    } payload;
} drv_wlan_WlanRpcRequest;

/* 统一 RPC 响应 */
typedef struct _drv_wlan_WlanRpcResponse {
    bool has_req_id;
    uint32_t req_id;
    pb_size_t which_payload;
    union {
        drv_wlan_WlanInitResponse init;
        drv_wlan_WlanConnectResponse connect;
        drv_wlan_WlanDisconnectResponse disconnect;
        drv_wlan_WlanApStartResponse ap_start;
        drv_wlan_WlanApStopResponse ap_stop;
        drv_wlan_WlanScanResponse scan;
    } payload;
} drv_wlan_WlanRpcResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _drv_wlan_WlanResultCode_MIN drv_wlan_WlanResultCode_WLAN_RES_OK
#define _drv_wlan_WlanResultCode_MAX drv_wlan_WlanResultCode_WLAN_RES_FAIL
#define _drv_wlan_WlanResultCode_ARRAYSIZE ((drv_wlan_WlanResultCode)(drv_wlan_WlanResultCode_WLAN_RES_FAIL+1))

#define drv_wlan_WlanResult_code_ENUMTYPE drv_wlan_WlanResultCode
















/* Initializer values for message structs */
#define drv_wlan_WlanResult_init_default         {false, drv_wlan_WlanResultCode_WLAN_RES_OK, false, 0}
#define drv_wlan_WlanInitRequest_init_default    {false, 1u}
#define drv_wlan_WlanInitResponse_init_default   {drv_wlan_WlanResult_init_default}
#define drv_wlan_WlanConnectRequest_init_default {"", false, "", false, {0, {0}}, false, 0u, false, false, false, 0u}
#define drv_wlan_WlanConnectResponse_init_default {drv_wlan_WlanResult_init_default}
#define drv_wlan_WlanDisconnectRequest_init_default {0}
#define drv_wlan_WlanDisconnectResponse_init_default {drv_wlan_WlanResult_init_default}
#define drv_wlan_WlanApStartRequest_init_default {"", false, "", false, 6u, false, 0u, false, false, false, 4u, false, {0, {0}}, false, {0, {0}}}
#define drv_wlan_WlanApStartResponse_init_default {drv_wlan_WlanResult_init_default}
#define drv_wlan_WlanApStopRequest_init_default  {0}
#define drv_wlan_WlanApStopResponse_init_default {drv_wlan_WlanResult_init_default}
#define drv_wlan_WlanScanRequest_init_default    {0}
#define drv_wlan_WlanScanResponse_init_default   {drv_wlan_WlanResult_init_default}
#define drv_wlan_WlanRpcRequest_init_default     {0, 0, {drv_wlan_WlanInitRequest_init_default}}
#define drv_wlan_WlanRpcResponse_init_default    {false, 0u, 0, {drv_wlan_WlanInitResponse_init_default}}
#define drv_wlan_WlanResult_init_zero            {false, _drv_wlan_WlanResultCode_MIN, false, 0}
#define drv_wlan_WlanInitRequest_init_zero       {false, 0}
#define drv_wlan_WlanInitResponse_init_zero      {drv_wlan_WlanResult_init_zero}
#define drv_wlan_WlanConnectRequest_init_zero    {"", false, "", false, {0, {0}}, false, 0, false, 0, false, 0}
#define drv_wlan_WlanConnectResponse_init_zero   {drv_wlan_WlanResult_init_zero}
#define drv_wlan_WlanDisconnectRequest_init_zero {0}
#define drv_wlan_WlanDisconnectResponse_init_zero {drv_wlan_WlanResult_init_zero}
#define drv_wlan_WlanApStartRequest_init_zero    {"", false, "", false, 0, false, 0, false, 0, false, 0, false, {0, {0}}, false, {0, {0}}}
#define drv_wlan_WlanApStartResponse_init_zero   {drv_wlan_WlanResult_init_zero}
#define drv_wlan_WlanApStopRequest_init_zero     {0}
#define drv_wlan_WlanApStopResponse_init_zero    {drv_wlan_WlanResult_init_zero}
#define drv_wlan_WlanScanRequest_init_zero       {0}
#define drv_wlan_WlanScanResponse_init_zero      {drv_wlan_WlanResult_init_zero}
#define drv_wlan_WlanScanResultNotify_init_default {0, {0, {0}}}
#define drv_wlan_WlanScanResultNotify_init_zero    {0, {0, {0}}}
#define drv_wlan_WlanStaIncNotify_init_default     {"", false, "", false, {0, {0}}, false, 0}
#define drv_wlan_WlanStaIncNotify_init_zero        {"", false, "", false, {0, {0}}, false, 0}
#define drv_wlan_WlanIpReadyNotify_init_default    {false, "", false, 0}
#define drv_wlan_WlanIpReadyNotify_init_zero       {false, "", false, 0}
#define drv_wlan_WlanApIncNotify_init_default      {"", false, {0, {0}}}
#define drv_wlan_WlanApIncNotify_init_zero         {"", false, {0, {0}}}
#define drv_wlan_WlanRpcRequest_init_zero        {0, 0, {drv_wlan_WlanInitRequest_init_zero}}
#define drv_wlan_WlanRpcResponse_init_zero       {false, 0, 0, {drv_wlan_WlanInitResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define drv_wlan_WlanResult_code_tag             1
#define drv_wlan_WlanResult_os_errno_tag         2
#define drv_wlan_WlanInitRequest_mode_tag        1
#define drv_wlan_WlanInitResponse_result_tag     1
#define drv_wlan_WlanConnectRequest_ssid_tag     1
#define drv_wlan_WlanConnectRequest_password_tag 2
#define drv_wlan_WlanConnectRequest_bssid_tag    3
#define drv_wlan_WlanConnectRequest_authmode_tag 4
#define drv_wlan_WlanConnectRequest_auto_reconnection_tag 5
#define drv_wlan_WlanConnectRequest_auto_reconnection_delay_sec_tag 6
#define drv_wlan_WlanConnectResponse_result_tag  1
#define drv_wlan_WlanScanResultNotify_count_tag  1
#define drv_wlan_WlanScanResultNotify_data_tag   2
#define drv_wlan_WlanStaIncNotify_event_tag      1
#define drv_wlan_WlanStaIncNotify_ssid_tag       2
#define drv_wlan_WlanStaIncNotify_bssid_tag      3
#define drv_wlan_WlanStaIncNotify_reason_tag     4
#define drv_wlan_WlanIpReadyNotify_ip_tag        1
#define drv_wlan_WlanIpReadyNotify_adapter_tag   2
#define drv_wlan_WlanApIncNotify_event_tag       1
#define drv_wlan_WlanApIncNotify_mac_tag         2
#define drv_wlan_WlanDisconnectResponse_result_tag 1
#define drv_wlan_WlanApStartRequest_ssid_tag     1
#define drv_wlan_WlanApStartRequest_password_tag 2
#define drv_wlan_WlanApStartRequest_channel_tag  3
#define drv_wlan_WlanApStartRequest_encrypt_tag  4
#define drv_wlan_WlanApStartRequest_hidden_tag   5
#define drv_wlan_WlanApStartRequest_max_conn_tag 6
#define drv_wlan_WlanApStartRequest_gateway_tag  7
#define drv_wlan_WlanApStartRequest_netmask_tag  8
#define drv_wlan_WlanApStartResponse_result_tag  1
#define drv_wlan_WlanApStopResponse_result_tag   1
#define drv_wlan_WlanScanResponse_result_tag     1
#define drv_wlan_WlanRpcRequest_req_id_tag       1
#define drv_wlan_WlanRpcRequest_init_tag         10
#define drv_wlan_WlanRpcRequest_connect_tag      11
#define drv_wlan_WlanRpcRequest_disconnect_tag   12
#define drv_wlan_WlanRpcRequest_ap_start_tag     13
#define drv_wlan_WlanRpcRequest_ap_stop_tag      14
#define drv_wlan_WlanRpcRequest_scan_tag         15
#define drv_wlan_WlanRpcResponse_req_id_tag      1
#define drv_wlan_WlanRpcResponse_init_tag        10
#define drv_wlan_WlanRpcResponse_connect_tag     11
#define drv_wlan_WlanRpcResponse_disconnect_tag  12
#define drv_wlan_WlanRpcResponse_ap_start_tag    13
#define drv_wlan_WlanRpcResponse_ap_stop_tag     14
#define drv_wlan_WlanRpcResponse_scan_tag        15

/* Struct field encoding specification for nanopb */
#define drv_wlan_WlanResult_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    code,              1) \
X(a, STATIC,   OPTIONAL, INT32,    os_errno,          2)
#define drv_wlan_WlanResult_CALLBACK NULL
#define drv_wlan_WlanResult_DEFAULT (const pb_byte_t*)"\x10\x00\x00"

#define drv_wlan_WlanInitRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   mode,              1)
#define drv_wlan_WlanInitRequest_CALLBACK NULL
#define drv_wlan_WlanInitRequest_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

#define drv_wlan_WlanInitResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_wlan_WlanInitResponse_CALLBACK NULL
#define drv_wlan_WlanInitResponse_DEFAULT NULL
#define drv_wlan_WlanInitResponse_result_MSGTYPE drv_wlan_WlanResult

#define drv_wlan_WlanConnectRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   ssid,              1) \
X(a, STATIC,   OPTIONAL, STRING,   password,          2) \
X(a, STATIC,   OPTIONAL, BYTES,    bssid,             3) \
X(a, STATIC,   OPTIONAL, UINT32,   authmode,          4) \
X(a, STATIC,   OPTIONAL, BOOL,     auto_reconnection,   5) \
X(a, STATIC,   OPTIONAL, UINT32,   auto_reconnection_delay_sec,   6)
#define drv_wlan_WlanConnectRequest_CALLBACK NULL
#define drv_wlan_WlanConnectRequest_DEFAULT (const pb_byte_t*)"\x20\x00\x28\x00\x30\x00\x00"

#define drv_wlan_WlanConnectResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_wlan_WlanConnectResponse_CALLBACK NULL
#define drv_wlan_WlanConnectResponse_DEFAULT NULL
#define drv_wlan_WlanConnectResponse_result_MSGTYPE drv_wlan_WlanResult

#define drv_wlan_WlanDisconnectRequest_FIELDLIST(X, a) \

#define drv_wlan_WlanDisconnectRequest_CALLBACK NULL
#define drv_wlan_WlanDisconnectRequest_DEFAULT NULL

#define drv_wlan_WlanDisconnectResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_wlan_WlanDisconnectResponse_CALLBACK NULL
#define drv_wlan_WlanDisconnectResponse_DEFAULT NULL
#define drv_wlan_WlanDisconnectResponse_result_MSGTYPE drv_wlan_WlanResult

#define drv_wlan_WlanApStartRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   ssid,              1) \
X(a, STATIC,   OPTIONAL, STRING,   password,          2) \
X(a, STATIC,   OPTIONAL, UINT32,   channel,           3) \
X(a, STATIC,   OPTIONAL, UINT32,   encrypt,           4) \
X(a, STATIC,   OPTIONAL, BOOL,     hidden,            5) \
X(a, STATIC,   OPTIONAL, UINT32,   max_conn,          6) \
X(a, STATIC,   OPTIONAL, BYTES,    gateway,           7) \
X(a, STATIC,   OPTIONAL, BYTES,    netmask,           8)
#define drv_wlan_WlanApStartRequest_CALLBACK NULL
#define drv_wlan_WlanApStartRequest_DEFAULT (const pb_byte_t*)"\x18\x06\x20\x00\x28\x00\x30\x04\x00"

#define drv_wlan_WlanApStartResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_wlan_WlanApStartResponse_CALLBACK NULL
#define drv_wlan_WlanApStartResponse_DEFAULT NULL
#define drv_wlan_WlanApStartResponse_result_MSGTYPE drv_wlan_WlanResult

#define drv_wlan_WlanApStopRequest_FIELDLIST(X, a) \

#define drv_wlan_WlanApStopRequest_CALLBACK NULL
#define drv_wlan_WlanApStopRequest_DEFAULT NULL

#define drv_wlan_WlanApStopResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_wlan_WlanApStopResponse_CALLBACK NULL
#define drv_wlan_WlanApStopResponse_DEFAULT NULL
#define drv_wlan_WlanApStopResponse_result_MSGTYPE drv_wlan_WlanResult

#define drv_wlan_WlanScanRequest_FIELDLIST(X, a) \

#define drv_wlan_WlanScanRequest_CALLBACK NULL
#define drv_wlan_WlanScanRequest_DEFAULT NULL

#define drv_wlan_WlanScanResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_wlan_WlanScanResponse_CALLBACK NULL
#define drv_wlan_WlanScanResponse_DEFAULT NULL
#define drv_wlan_WlanScanResponse_result_MSGTYPE drv_wlan_WlanResult

#define drv_wlan_WlanScanResultNotify_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   count,             1) \
X(a, STATIC,   REQUIRED, BYTES,    data,              2)
#define drv_wlan_WlanScanResultNotify_CALLBACK NULL
#define drv_wlan_WlanScanResultNotify_DEFAULT NULL

#define drv_wlan_WlanStaIncNotify_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   event,             1) \
X(a, STATIC,   OPTIONAL, STRING,   ssid,              2) \
X(a, STATIC,   OPTIONAL, BYTES,    bssid,             3) \
X(a, STATIC,   OPTIONAL, UINT32,   reason,            4)
#define drv_wlan_WlanStaIncNotify_CALLBACK NULL
#define drv_wlan_WlanStaIncNotify_DEFAULT (const pb_byte_t*)"\x0a\x00\x00"

#define drv_wlan_WlanIpReadyNotify_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   ip,                1) \
X(a, STATIC,   OPTIONAL, UINT32,   adapter,           2)
#define drv_wlan_WlanIpReadyNotify_CALLBACK NULL
#define drv_wlan_WlanIpReadyNotify_DEFAULT NULL

#define drv_wlan_WlanApIncNotify_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   event,             1) \
X(a, STATIC,   OPTIONAL, BYTES,    mac,               2)
#define drv_wlan_WlanApIncNotify_CALLBACK NULL
#define drv_wlan_WlanApIncNotify_DEFAULT (const pb_byte_t*)"\x0a\x00\x00"

#define drv_wlan_WlanRpcRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   req_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,init,payload.init),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,connect,payload.connect),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,disconnect,payload.disconnect),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ap_start,payload.ap_start),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ap_stop,payload.ap_stop),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scan,payload.scan),  15)
#define drv_wlan_WlanRpcRequest_CALLBACK NULL
#define drv_wlan_WlanRpcRequest_DEFAULT NULL
#define drv_wlan_WlanRpcRequest_payload_init_MSGTYPE drv_wlan_WlanInitRequest
#define drv_wlan_WlanRpcRequest_payload_connect_MSGTYPE drv_wlan_WlanConnectRequest
#define drv_wlan_WlanRpcRequest_payload_disconnect_MSGTYPE drv_wlan_WlanDisconnectRequest
#define drv_wlan_WlanRpcRequest_payload_ap_start_MSGTYPE drv_wlan_WlanApStartRequest
#define drv_wlan_WlanRpcRequest_payload_ap_stop_MSGTYPE drv_wlan_WlanApStopRequest
#define drv_wlan_WlanRpcRequest_payload_scan_MSGTYPE drv_wlan_WlanScanRequest

#define drv_wlan_WlanRpcResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   req_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,init,payload.init),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,connect,payload.connect),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,disconnect,payload.disconnect),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ap_start,payload.ap_start),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ap_stop,payload.ap_stop),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scan,payload.scan),  15)
#define drv_wlan_WlanRpcResponse_CALLBACK NULL
#define drv_wlan_WlanRpcResponse_DEFAULT (const pb_byte_t*)"\x08\x00\x00"
#define drv_wlan_WlanRpcResponse_payload_init_MSGTYPE drv_wlan_WlanInitResponse
#define drv_wlan_WlanRpcResponse_payload_connect_MSGTYPE drv_wlan_WlanConnectResponse
#define drv_wlan_WlanRpcResponse_payload_disconnect_MSGTYPE drv_wlan_WlanDisconnectResponse
#define drv_wlan_WlanRpcResponse_payload_ap_start_MSGTYPE drv_wlan_WlanApStartResponse
#define drv_wlan_WlanRpcResponse_payload_ap_stop_MSGTYPE drv_wlan_WlanApStopResponse
#define drv_wlan_WlanRpcResponse_payload_scan_MSGTYPE drv_wlan_WlanScanResponse

extern const pb_msgdesc_t drv_wlan_WlanResult_msg;
extern const pb_msgdesc_t drv_wlan_WlanInitRequest_msg;
extern const pb_msgdesc_t drv_wlan_WlanInitResponse_msg;
extern const pb_msgdesc_t drv_wlan_WlanConnectRequest_msg;
extern const pb_msgdesc_t drv_wlan_WlanConnectResponse_msg;
extern const pb_msgdesc_t drv_wlan_WlanDisconnectRequest_msg;
extern const pb_msgdesc_t drv_wlan_WlanDisconnectResponse_msg;
extern const pb_msgdesc_t drv_wlan_WlanApStartRequest_msg;
extern const pb_msgdesc_t drv_wlan_WlanApStartResponse_msg;
extern const pb_msgdesc_t drv_wlan_WlanApStopRequest_msg;
extern const pb_msgdesc_t drv_wlan_WlanApStopResponse_msg;
extern const pb_msgdesc_t drv_wlan_WlanScanRequest_msg;
extern const pb_msgdesc_t drv_wlan_WlanScanResponse_msg;
extern const pb_msgdesc_t drv_wlan_WlanScanResultNotify_msg;
extern const pb_msgdesc_t drv_wlan_WlanStaIncNotify_msg;
extern const pb_msgdesc_t drv_wlan_WlanIpReadyNotify_msg;
extern const pb_msgdesc_t drv_wlan_WlanApIncNotify_msg;
extern const pb_msgdesc_t drv_wlan_WlanRpcRequest_msg;
extern const pb_msgdesc_t drv_wlan_WlanRpcResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define drv_wlan_WlanResult_fields &drv_wlan_WlanResult_msg
#define drv_wlan_WlanInitRequest_fields &drv_wlan_WlanInitRequest_msg
#define drv_wlan_WlanInitResponse_fields &drv_wlan_WlanInitResponse_msg
#define drv_wlan_WlanConnectRequest_fields &drv_wlan_WlanConnectRequest_msg
#define drv_wlan_WlanConnectResponse_fields &drv_wlan_WlanConnectResponse_msg
#define drv_wlan_WlanDisconnectRequest_fields &drv_wlan_WlanDisconnectRequest_msg
#define drv_wlan_WlanDisconnectResponse_fields &drv_wlan_WlanDisconnectResponse_msg
#define drv_wlan_WlanApStartRequest_fields &drv_wlan_WlanApStartRequest_msg
#define drv_wlan_WlanApStartResponse_fields &drv_wlan_WlanApStartResponse_msg
#define drv_wlan_WlanApStopRequest_fields &drv_wlan_WlanApStopRequest_msg
#define drv_wlan_WlanApStopResponse_fields &drv_wlan_WlanApStopResponse_msg
#define drv_wlan_WlanScanRequest_fields &drv_wlan_WlanScanRequest_msg
#define drv_wlan_WlanScanResponse_fields &drv_wlan_WlanScanResponse_msg
#define drv_wlan_WlanScanResultNotify_fields &drv_wlan_WlanScanResultNotify_msg
#define drv_wlan_WlanStaIncNotify_fields &drv_wlan_WlanStaIncNotify_msg
#define drv_wlan_WlanIpReadyNotify_fields &drv_wlan_WlanIpReadyNotify_msg
#define drv_wlan_WlanApIncNotify_fields &drv_wlan_WlanApIncNotify_msg
#define drv_wlan_WlanRpcRequest_fields &drv_wlan_WlanRpcRequest_msg
#define drv_wlan_WlanRpcResponse_fields &drv_wlan_WlanRpcResponse_msg

/* Maximum encoded size of messages (where known) */
#define DRV_WLAN_DRV_WLAN_PB_H_MAX_SIZE          drv_wlan_WlanScanResultNotify_size
#define drv_wlan_WlanApStartRequest_size         134
#define drv_wlan_WlanApStartResponse_size        16
#define drv_wlan_WlanApStopRequest_size          0
#define drv_wlan_WlanApStopResponse_size         16
#define drv_wlan_WlanConnectRequest_size         124
#define drv_wlan_WlanConnectResponse_size        16
#define drv_wlan_WlanDisconnectRequest_size      0
#define drv_wlan_WlanDisconnectResponse_size     16
#define drv_wlan_WlanInitRequest_size            6
#define drv_wlan_WlanInitResponse_size           16
#define drv_wlan_WlanResult_size                 14
#define drv_wlan_WlanRpcRequest_size             143
#define drv_wlan_WlanRpcResponse_size            24
#define drv_wlan_WlanScanRequest_size            0
#define drv_wlan_WlanScanResponse_size           16
#define drv_wlan_WlanScanResultNotify_size       2060
#define drv_wlan_WlanStaIncNotify_size           70
#define drv_wlan_WlanIpReadyNotify_size          24
#define drv_wlan_WlanApIncNotify_size            26

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
