/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DRV_PM_DRV_PM_PB_H_INCLUDED
#define PB_DRV_PM_DRV_PM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 通用返回码 */
typedef enum _drv_pm_PmResultCode {
    drv_pm_PmResultCode_PM_RES_OK = 0,
    drv_pm_PmResultCode_PM_RES_EINVAL = 1,
    drv_pm_PmResultCode_PM_RES_FAIL = 255
} drv_pm_PmResultCode;

/* Struct definitions */
typedef struct _drv_pm_PmResult {
    bool has_code;
    drv_pm_PmResultCode code;
    bool has_os_errno;
    int32_t os_errno;
} drv_pm_PmResult;

/* 睡眠模式请求（对应 luat_pm_request）
 mode: LUAT_PM_SLEEP_MODE_NONE/LIGHT/DEEP/STANDBY */
typedef struct _drv_pm_PmRequestRequest {
    uint32_t mode;
} drv_pm_PmRequestRequest;

typedef struct _drv_pm_PmRequestResponse {
    drv_pm_PmResult result;
} drv_pm_PmRequestResponse;

/* 外设电源控制（对应 luat_pm_power_ctrl） */
typedef struct _drv_pm_PmPowerCtrlRequest {
    uint32_t id;
    uint32_t val;
} drv_pm_PmPowerCtrlRequest;

typedef struct _drv_pm_PmPowerCtrlResponse {
    drv_pm_PmResult result;
} drv_pm_PmPowerCtrlResponse;

/* 配置唤醒脚（对应 luat_pm_wakeup_pin） */
typedef struct _drv_pm_PmWakeupPinRequest {
    uint32_t pin;
    uint32_t val;
} drv_pm_PmWakeupPinRequest;

typedef struct _drv_pm_PmWakeupPinResponse {
    drv_pm_PmResult result;
} drv_pm_PmWakeupPinResponse;

/* 统一 RPC 请求 */
typedef struct _drv_pm_PmRpcRequest {
    uint32_t req_id;
    pb_size_t which_payload;
    union {
        drv_pm_PmRequestRequest pm_request;
        drv_pm_PmPowerCtrlRequest power_ctrl;
        drv_pm_PmWakeupPinRequest wakeup_pin;
    } payload;
} drv_pm_PmRpcRequest;

/* 统一 RPC 响应 */
typedef struct _drv_pm_PmRpcResponse {
    bool has_req_id;
    uint32_t req_id;
    pb_size_t which_payload;
    union {
        drv_pm_PmRequestResponse pm_request;
        drv_pm_PmPowerCtrlResponse power_ctrl;
        drv_pm_PmWakeupPinResponse wakeup_pin;
    } payload;
} drv_pm_PmRpcResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _drv_pm_PmResultCode_MIN drv_pm_PmResultCode_PM_RES_OK
#define _drv_pm_PmResultCode_MAX drv_pm_PmResultCode_PM_RES_FAIL
#define _drv_pm_PmResultCode_ARRAYSIZE ((drv_pm_PmResultCode)(drv_pm_PmResultCode_PM_RES_FAIL+1))

#define drv_pm_PmResult_code_ENUMTYPE drv_pm_PmResultCode










/* Initializer values for message structs */
#define drv_pm_PmResult_init_default             {false, drv_pm_PmResultCode_PM_RES_OK, false, 0}
#define drv_pm_PmRequestRequest_init_default     {0}
#define drv_pm_PmRequestResponse_init_default    {drv_pm_PmResult_init_default}
#define drv_pm_PmPowerCtrlRequest_init_default   {0, 0}
#define drv_pm_PmPowerCtrlResponse_init_default  {drv_pm_PmResult_init_default}
#define drv_pm_PmWakeupPinRequest_init_default   {0, 0}
#define drv_pm_PmWakeupPinResponse_init_default  {drv_pm_PmResult_init_default}
#define drv_pm_PmRpcRequest_init_default         {0, 0, {drv_pm_PmRequestRequest_init_default}}
#define drv_pm_PmRpcResponse_init_default        {false, 0u, 0, {drv_pm_PmRequestResponse_init_default}}
#define drv_pm_PmResult_init_zero                {false, _drv_pm_PmResultCode_MIN, false, 0}
#define drv_pm_PmRequestRequest_init_zero        {0}
#define drv_pm_PmRequestResponse_init_zero       {drv_pm_PmResult_init_zero}
#define drv_pm_PmPowerCtrlRequest_init_zero      {0, 0}
#define drv_pm_PmPowerCtrlResponse_init_zero     {drv_pm_PmResult_init_zero}
#define drv_pm_PmWakeupPinRequest_init_zero      {0, 0}
#define drv_pm_PmWakeupPinResponse_init_zero     {drv_pm_PmResult_init_zero}
#define drv_pm_PmRpcRequest_init_zero            {0, 0, {drv_pm_PmRequestRequest_init_zero}}
#define drv_pm_PmRpcResponse_init_zero           {false, 0, 0, {drv_pm_PmRequestResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define drv_pm_PmResult_code_tag                 1
#define drv_pm_PmResult_os_errno_tag             2
#define drv_pm_PmRequestRequest_mode_tag         1
#define drv_pm_PmRequestResponse_result_tag      1
#define drv_pm_PmPowerCtrlRequest_id_tag         1
#define drv_pm_PmPowerCtrlRequest_val_tag        2
#define drv_pm_PmPowerCtrlResponse_result_tag    1
#define drv_pm_PmWakeupPinRequest_pin_tag        1
#define drv_pm_PmWakeupPinRequest_val_tag        2
#define drv_pm_PmWakeupPinResponse_result_tag    1
#define drv_pm_PmRpcRequest_req_id_tag           1
#define drv_pm_PmRpcRequest_pm_request_tag       10
#define drv_pm_PmRpcRequest_power_ctrl_tag       11
#define drv_pm_PmRpcRequest_wakeup_pin_tag       12
#define drv_pm_PmRpcResponse_req_id_tag          1
#define drv_pm_PmRpcResponse_pm_request_tag      10
#define drv_pm_PmRpcResponse_power_ctrl_tag      11
#define drv_pm_PmRpcResponse_wakeup_pin_tag      12

/* Struct field encoding specification for nanopb */
#define drv_pm_PmResult_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    code,              1) \
X(a, STATIC,   OPTIONAL, INT32,    os_errno,          2)
#define drv_pm_PmResult_CALLBACK NULL
#define drv_pm_PmResult_DEFAULT (const pb_byte_t*)"\x10\x00\x00"

#define drv_pm_PmRequestRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   mode,              1)
#define drv_pm_PmRequestRequest_CALLBACK NULL
#define drv_pm_PmRequestRequest_DEFAULT NULL

#define drv_pm_PmRequestResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_pm_PmRequestResponse_CALLBACK NULL
#define drv_pm_PmRequestResponse_DEFAULT NULL
#define drv_pm_PmRequestResponse_result_MSGTYPE drv_pm_PmResult

#define drv_pm_PmPowerCtrlRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   id,                1) \
X(a, STATIC,   REQUIRED, UINT32,   val,               2)
#define drv_pm_PmPowerCtrlRequest_CALLBACK NULL
#define drv_pm_PmPowerCtrlRequest_DEFAULT NULL

#define drv_pm_PmPowerCtrlResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_pm_PmPowerCtrlResponse_CALLBACK NULL
#define drv_pm_PmPowerCtrlResponse_DEFAULT NULL
#define drv_pm_PmPowerCtrlResponse_result_MSGTYPE drv_pm_PmResult

#define drv_pm_PmWakeupPinRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   pin,               1) \
X(a, STATIC,   REQUIRED, UINT32,   val,               2)
#define drv_pm_PmWakeupPinRequest_CALLBACK NULL
#define drv_pm_PmWakeupPinRequest_DEFAULT NULL

#define drv_pm_PmWakeupPinResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_pm_PmWakeupPinResponse_CALLBACK NULL
#define drv_pm_PmWakeupPinResponse_DEFAULT NULL
#define drv_pm_PmWakeupPinResponse_result_MSGTYPE drv_pm_PmResult

#define drv_pm_PmRpcRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   req_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pm_request,payload.pm_request),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,power_ctrl,payload.power_ctrl),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,wakeup_pin,payload.wakeup_pin),  12)
#define drv_pm_PmRpcRequest_CALLBACK NULL
#define drv_pm_PmRpcRequest_DEFAULT NULL
#define drv_pm_PmRpcRequest_payload_pm_request_MSGTYPE drv_pm_PmRequestRequest
#define drv_pm_PmRpcRequest_payload_power_ctrl_MSGTYPE drv_pm_PmPowerCtrlRequest
#define drv_pm_PmRpcRequest_payload_wakeup_pin_MSGTYPE drv_pm_PmWakeupPinRequest

#define drv_pm_PmRpcResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   req_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pm_request,payload.pm_request),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,power_ctrl,payload.power_ctrl),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,wakeup_pin,payload.wakeup_pin),  12)
#define drv_pm_PmRpcResponse_CALLBACK NULL
#define drv_pm_PmRpcResponse_DEFAULT (const pb_byte_t*)"\x08\x00\x00"
#define drv_pm_PmRpcResponse_payload_pm_request_MSGTYPE drv_pm_PmRequestResponse
#define drv_pm_PmRpcResponse_payload_power_ctrl_MSGTYPE drv_pm_PmPowerCtrlResponse
#define drv_pm_PmRpcResponse_payload_wakeup_pin_MSGTYPE drv_pm_PmWakeupPinResponse

extern const pb_msgdesc_t drv_pm_PmResult_msg;
extern const pb_msgdesc_t drv_pm_PmRequestRequest_msg;
extern const pb_msgdesc_t drv_pm_PmRequestResponse_msg;
extern const pb_msgdesc_t drv_pm_PmPowerCtrlRequest_msg;
extern const pb_msgdesc_t drv_pm_PmPowerCtrlResponse_msg;
extern const pb_msgdesc_t drv_pm_PmWakeupPinRequest_msg;
extern const pb_msgdesc_t drv_pm_PmWakeupPinResponse_msg;
extern const pb_msgdesc_t drv_pm_PmRpcRequest_msg;
extern const pb_msgdesc_t drv_pm_PmRpcResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define drv_pm_PmResult_fields &drv_pm_PmResult_msg
#define drv_pm_PmRequestRequest_fields &drv_pm_PmRequestRequest_msg
#define drv_pm_PmRequestResponse_fields &drv_pm_PmRequestResponse_msg
#define drv_pm_PmPowerCtrlRequest_fields &drv_pm_PmPowerCtrlRequest_msg
#define drv_pm_PmPowerCtrlResponse_fields &drv_pm_PmPowerCtrlResponse_msg
#define drv_pm_PmWakeupPinRequest_fields &drv_pm_PmWakeupPinRequest_msg
#define drv_pm_PmWakeupPinResponse_fields &drv_pm_PmWakeupPinResponse_msg
#define drv_pm_PmRpcRequest_fields &drv_pm_PmRpcRequest_msg
#define drv_pm_PmRpcResponse_fields &drv_pm_PmRpcResponse_msg

/* Maximum encoded size of messages (where known) */
#define DRV_PM_DRV_PM_PB_H_MAX_SIZE              drv_pm_PmRpcResponse_size
#define drv_pm_PmPowerCtrlRequest_size           12
#define drv_pm_PmPowerCtrlResponse_size          16
#define drv_pm_PmRequestRequest_size             6
#define drv_pm_PmRequestResponse_size            16
#define drv_pm_PmResult_size                     14
#define drv_pm_PmRpcRequest_size                 20
#define drv_pm_PmRpcResponse_size                24
#define drv_pm_PmWakeupPinRequest_size           12
#define drv_pm_PmWakeupPinResponse_size          16

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
