/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DRV_GPIO_DRV_GPIO_PB_H_INCLUDED
#define PB_DRV_GPIO_DRV_GPIO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _drv_gpio_GpioMode {
    drv_gpio_GpioMode_GPIO_MODE_UNSPECIFIED = 0,
    drv_gpio_GpioMode_GPIO_MODE_OUTPUT = 1,
    drv_gpio_GpioMode_GPIO_MODE_INPUT = 2,
    drv_gpio_GpioMode_GPIO_MODE_IRQ = 3
} drv_gpio_GpioMode;

typedef enum _drv_gpio_GpioPull {
    drv_gpio_GpioPull_GPIO_PULL_UNSPECIFIED = 0,
    drv_gpio_GpioPull_GPIO_PULL_DEFAULT = 1,
    drv_gpio_GpioPull_GPIO_PULL_UP = 2,
    drv_gpio_GpioPull_GPIO_PULL_DOWN = 3
} drv_gpio_GpioPull;

typedef enum _drv_gpio_GpioLevel {
    drv_gpio_GpioLevel_GPIO_LEVEL_UNSPECIFIED = 0,
    drv_gpio_GpioLevel_GPIO_LEVEL_LOW = 1,
    drv_gpio_GpioLevel_GPIO_LEVEL_HIGH = 2
} drv_gpio_GpioLevel;

typedef enum _drv_gpio_GpioIrqType {
    drv_gpio_GpioIrqType_GPIO_IRQ_UNSPECIFIED = 0,
    drv_gpio_GpioIrqType_GPIO_IRQ_RISING = 1,
    drv_gpio_GpioIrqType_GPIO_IRQ_FALLING = 2,
    drv_gpio_GpioIrqType_GPIO_IRQ_BOTH = 3,
    drv_gpio_GpioIrqType_GPIO_IRQ_HIGH = 4,
    drv_gpio_GpioIrqType_GPIO_IRQ_LOW = 5
} drv_gpio_GpioIrqType;

typedef enum _drv_gpio_GpioResultCode {
    drv_gpio_GpioResultCode_GPIO_RES_OK = 0,
    drv_gpio_GpioResultCode_GPIO_RES_EINVAL = 1,
    drv_gpio_GpioResultCode_GPIO_RES_EBUSY = 2,
    drv_gpio_GpioResultCode_GPIO_RES_ENOTSUP = 3,
    drv_gpio_GpioResultCode_GPIO_RES_EIO = 4,
    drv_gpio_GpioResultCode_GPIO_RES_EPERM = 5,
    drv_gpio_GpioResultCode_GPIO_RES_FAIL = 255
} drv_gpio_GpioResultCode;

/* Struct definitions */
typedef struct _drv_gpio_GpioResult {
    bool has_code;
    drv_gpio_GpioResultCode code;
    bool has_os_errno;
    int32_t os_errno;
    bool has_msg;
    char msg[32];
} drv_gpio_GpioResult;

typedef struct _drv_gpio_GpioSetupRequest {
    uint32_t pin;
    bool has_mode;
    drv_gpio_GpioMode mode;
    bool has_pull;
    drv_gpio_GpioPull pull;
    bool has_init_level;
    drv_gpio_GpioLevel init_level;
    bool has_irq_type;
    drv_gpio_GpioIrqType irq_type;
    bool has_irq_enable;
    bool irq_enable;
    bool has_debounce_ms;
    uint32_t debounce_ms;
} drv_gpio_GpioSetupRequest;

typedef struct _drv_gpio_GpioSetupResponse {
    drv_gpio_GpioResult result;
} drv_gpio_GpioSetupResponse;

typedef struct _drv_gpio_GpioCloseRequest {
    uint32_t pin;
} drv_gpio_GpioCloseRequest;

typedef struct _drv_gpio_GpioCloseResponse {
    drv_gpio_GpioResult result;
} drv_gpio_GpioCloseResponse;

typedef struct _drv_gpio_GpioWriteRequest {
    uint32_t pin;
    drv_gpio_GpioLevel level;
} drv_gpio_GpioWriteRequest;

typedef struct _drv_gpio_GpioWriteResponse {
    drv_gpio_GpioResult result;
} drv_gpio_GpioWriteResponse;

typedef struct _drv_gpio_GpioReadRequest {
    uint32_t pin;
} drv_gpio_GpioReadRequest;

typedef struct _drv_gpio_GpioReadResponse {
    drv_gpio_GpioResult result;
    bool has_level;
    drv_gpio_GpioLevel level;
} drv_gpio_GpioReadResponse;

typedef struct _drv_gpio_GpioSetPullRequest {
    uint32_t pin;
    drv_gpio_GpioPull pull;
} drv_gpio_GpioSetPullRequest;

typedef struct _drv_gpio_GpioSetPullResponse {
    drv_gpio_GpioResult result;
} drv_gpio_GpioSetPullResponse;

typedef struct _drv_gpio_GpioSetIrqRequest {
    uint32_t pin;
    bool has_irq_type;
    drv_gpio_GpioIrqType irq_type;
    bool has_enable;
    bool enable;
    bool has_debounce_ms;
    uint32_t debounce_ms;
} drv_gpio_GpioSetIrqRequest;

typedef struct _drv_gpio_GpioSetIrqResponse {
    drv_gpio_GpioResult result;
} drv_gpio_GpioSetIrqResponse;

typedef struct _drv_gpio_GpioIrqEvent {
    uint32_t pin;
    bool has_irq_type;
    drv_gpio_GpioIrqType irq_type;
    bool has_level;
    drv_gpio_GpioLevel level;
    bool has_tick_ms;
    uint64_t tick_ms;
} drv_gpio_GpioIrqEvent;

typedef struct _drv_gpio_GpioRpcRequest {
    uint32_t req_id;
    pb_size_t which_payload;
    union {
        drv_gpio_GpioSetupRequest setup;
        drv_gpio_GpioCloseRequest close;
        drv_gpio_GpioWriteRequest write;
        drv_gpio_GpioReadRequest read;
        drv_gpio_GpioSetPullRequest set_pull;
        drv_gpio_GpioSetIrqRequest set_irq;
        drv_gpio_GpioIrqEvent irq_event;
    } payload;
} drv_gpio_GpioRpcRequest;

typedef struct _drv_gpio_GpioRpcResponse {
    bool has_req_id;
    uint32_t req_id;
    pb_size_t which_payload;
    union {
        drv_gpio_GpioSetupResponse setup;
        drv_gpio_GpioCloseResponse close;
        drv_gpio_GpioWriteResponse write;
        drv_gpio_GpioReadResponse read;
        drv_gpio_GpioSetPullResponse set_pull;
        drv_gpio_GpioSetIrqResponse set_irq;
        drv_gpio_GpioIrqEvent irq_event;
    } payload;
} drv_gpio_GpioRpcResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _drv_gpio_GpioMode_MIN drv_gpio_GpioMode_GPIO_MODE_UNSPECIFIED
#define _drv_gpio_GpioMode_MAX drv_gpio_GpioMode_GPIO_MODE_IRQ
#define _drv_gpio_GpioMode_ARRAYSIZE ((drv_gpio_GpioMode)(drv_gpio_GpioMode_GPIO_MODE_IRQ+1))

#define _drv_gpio_GpioPull_MIN drv_gpio_GpioPull_GPIO_PULL_UNSPECIFIED
#define _drv_gpio_GpioPull_MAX drv_gpio_GpioPull_GPIO_PULL_DOWN
#define _drv_gpio_GpioPull_ARRAYSIZE ((drv_gpio_GpioPull)(drv_gpio_GpioPull_GPIO_PULL_DOWN+1))

#define _drv_gpio_GpioLevel_MIN drv_gpio_GpioLevel_GPIO_LEVEL_UNSPECIFIED
#define _drv_gpio_GpioLevel_MAX drv_gpio_GpioLevel_GPIO_LEVEL_HIGH
#define _drv_gpio_GpioLevel_ARRAYSIZE ((drv_gpio_GpioLevel)(drv_gpio_GpioLevel_GPIO_LEVEL_HIGH+1))

#define _drv_gpio_GpioIrqType_MIN drv_gpio_GpioIrqType_GPIO_IRQ_UNSPECIFIED
#define _drv_gpio_GpioIrqType_MAX drv_gpio_GpioIrqType_GPIO_IRQ_LOW
#define _drv_gpio_GpioIrqType_ARRAYSIZE ((drv_gpio_GpioIrqType)(drv_gpio_GpioIrqType_GPIO_IRQ_LOW+1))

#define _drv_gpio_GpioResultCode_MIN drv_gpio_GpioResultCode_GPIO_RES_OK
#define _drv_gpio_GpioResultCode_MAX drv_gpio_GpioResultCode_GPIO_RES_FAIL
#define _drv_gpio_GpioResultCode_ARRAYSIZE ((drv_gpio_GpioResultCode)(drv_gpio_GpioResultCode_GPIO_RES_FAIL+1))

#define drv_gpio_GpioResult_code_ENUMTYPE drv_gpio_GpioResultCode

#define drv_gpio_GpioSetupRequest_mode_ENUMTYPE drv_gpio_GpioMode
#define drv_gpio_GpioSetupRequest_pull_ENUMTYPE drv_gpio_GpioPull
#define drv_gpio_GpioSetupRequest_init_level_ENUMTYPE drv_gpio_GpioLevel
#define drv_gpio_GpioSetupRequest_irq_type_ENUMTYPE drv_gpio_GpioIrqType




#define drv_gpio_GpioWriteRequest_level_ENUMTYPE drv_gpio_GpioLevel



#define drv_gpio_GpioReadResponse_level_ENUMTYPE drv_gpio_GpioLevel

#define drv_gpio_GpioSetPullRequest_pull_ENUMTYPE drv_gpio_GpioPull


#define drv_gpio_GpioSetIrqRequest_irq_type_ENUMTYPE drv_gpio_GpioIrqType


#define drv_gpio_GpioIrqEvent_irq_type_ENUMTYPE drv_gpio_GpioIrqType
#define drv_gpio_GpioIrqEvent_level_ENUMTYPE drv_gpio_GpioLevel




/* Initializer values for message structs */
#define drv_gpio_GpioResult_init_default         {false, drv_gpio_GpioResultCode_GPIO_RES_OK, false, 0, false, ""}
#define drv_gpio_GpioSetupRequest_init_default   {0, false, drv_gpio_GpioMode_GPIO_MODE_INPUT, false, drv_gpio_GpioPull_GPIO_PULL_DEFAULT, false, drv_gpio_GpioLevel_GPIO_LEVEL_LOW, false, drv_gpio_GpioIrqType_GPIO_IRQ_UNSPECIFIED, false, false, false, 0u}
#define drv_gpio_GpioSetupResponse_init_default  {drv_gpio_GpioResult_init_default}
#define drv_gpio_GpioCloseRequest_init_default   {0}
#define drv_gpio_GpioCloseResponse_init_default  {drv_gpio_GpioResult_init_default}
#define drv_gpio_GpioWriteRequest_init_default   {0, _drv_gpio_GpioLevel_MIN}
#define drv_gpio_GpioWriteResponse_init_default  {drv_gpio_GpioResult_init_default}
#define drv_gpio_GpioReadRequest_init_default    {0}
#define drv_gpio_GpioReadResponse_init_default   {drv_gpio_GpioResult_init_default, false, drv_gpio_GpioLevel_GPIO_LEVEL_UNSPECIFIED}
#define drv_gpio_GpioSetPullRequest_init_default {0, _drv_gpio_GpioPull_MIN}
#define drv_gpio_GpioSetPullResponse_init_default {drv_gpio_GpioResult_init_default}
#define drv_gpio_GpioSetIrqRequest_init_default  {0, false, drv_gpio_GpioIrqType_GPIO_IRQ_UNSPECIFIED, false, true, false, 0u}
#define drv_gpio_GpioSetIrqResponse_init_default {drv_gpio_GpioResult_init_default}
#define drv_gpio_GpioIrqEvent_init_default       {0, false, drv_gpio_GpioIrqType_GPIO_IRQ_UNSPECIFIED, false, drv_gpio_GpioLevel_GPIO_LEVEL_UNSPECIFIED, false, 0ull}
#define drv_gpio_GpioRpcRequest_init_default     {0, 0, {drv_gpio_GpioSetupRequest_init_default}}
#define drv_gpio_GpioRpcResponse_init_default    {false, 0u, 0, {drv_gpio_GpioSetupResponse_init_default}}
#define drv_gpio_GpioResult_init_zero            {false, _drv_gpio_GpioResultCode_MIN, false, 0, false, ""}
#define drv_gpio_GpioSetupRequest_init_zero      {0, false, _drv_gpio_GpioMode_MIN, false, _drv_gpio_GpioPull_MIN, false, _drv_gpio_GpioLevel_MIN, false, _drv_gpio_GpioIrqType_MIN, false, 0, false, 0}
#define drv_gpio_GpioSetupResponse_init_zero     {drv_gpio_GpioResult_init_zero}
#define drv_gpio_GpioCloseRequest_init_zero      {0}
#define drv_gpio_GpioCloseResponse_init_zero     {drv_gpio_GpioResult_init_zero}
#define drv_gpio_GpioWriteRequest_init_zero      {0, _drv_gpio_GpioLevel_MIN}
#define drv_gpio_GpioWriteResponse_init_zero     {drv_gpio_GpioResult_init_zero}
#define drv_gpio_GpioReadRequest_init_zero       {0}
#define drv_gpio_GpioReadResponse_init_zero      {drv_gpio_GpioResult_init_zero, false, _drv_gpio_GpioLevel_MIN}
#define drv_gpio_GpioSetPullRequest_init_zero    {0, _drv_gpio_GpioPull_MIN}
#define drv_gpio_GpioSetPullResponse_init_zero   {drv_gpio_GpioResult_init_zero}
#define drv_gpio_GpioSetIrqRequest_init_zero     {0, false, _drv_gpio_GpioIrqType_MIN, false, 0, false, 0}
#define drv_gpio_GpioSetIrqResponse_init_zero    {drv_gpio_GpioResult_init_zero}
#define drv_gpio_GpioIrqEvent_init_zero          {0, false, _drv_gpio_GpioIrqType_MIN, false, _drv_gpio_GpioLevel_MIN, false, 0}
#define drv_gpio_GpioRpcRequest_init_zero        {0, 0, {drv_gpio_GpioSetupRequest_init_zero}}
#define drv_gpio_GpioRpcResponse_init_zero       {false, 0, 0, {drv_gpio_GpioSetupResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define drv_gpio_GpioResult_code_tag             1
#define drv_gpio_GpioResult_os_errno_tag         2
#define drv_gpio_GpioResult_msg_tag              3
#define drv_gpio_GpioSetupRequest_pin_tag        1
#define drv_gpio_GpioSetupRequest_mode_tag       2
#define drv_gpio_GpioSetupRequest_pull_tag       3
#define drv_gpio_GpioSetupRequest_init_level_tag 4
#define drv_gpio_GpioSetupRequest_irq_type_tag   5
#define drv_gpio_GpioSetupRequest_irq_enable_tag 6
#define drv_gpio_GpioSetupRequest_debounce_ms_tag 7
#define drv_gpio_GpioSetupResponse_result_tag    1
#define drv_gpio_GpioCloseRequest_pin_tag        1
#define drv_gpio_GpioCloseResponse_result_tag    1
#define drv_gpio_GpioWriteRequest_pin_tag        1
#define drv_gpio_GpioWriteRequest_level_tag      2
#define drv_gpio_GpioWriteResponse_result_tag    1
#define drv_gpio_GpioReadRequest_pin_tag         1
#define drv_gpio_GpioReadResponse_result_tag     1
#define drv_gpio_GpioReadResponse_level_tag      2
#define drv_gpio_GpioSetPullRequest_pin_tag      1
#define drv_gpio_GpioSetPullRequest_pull_tag     2
#define drv_gpio_GpioSetPullResponse_result_tag  1
#define drv_gpio_GpioSetIrqRequest_pin_tag       1
#define drv_gpio_GpioSetIrqRequest_irq_type_tag  2
#define drv_gpio_GpioSetIrqRequest_enable_tag    3
#define drv_gpio_GpioSetIrqRequest_debounce_ms_tag 4
#define drv_gpio_GpioSetIrqResponse_result_tag   1
#define drv_gpio_GpioIrqEvent_pin_tag            1
#define drv_gpio_GpioIrqEvent_irq_type_tag       2
#define drv_gpio_GpioIrqEvent_level_tag          3
#define drv_gpio_GpioIrqEvent_tick_ms_tag        4
#define drv_gpio_GpioRpcRequest_req_id_tag       1
#define drv_gpio_GpioRpcRequest_setup_tag        10
#define drv_gpio_GpioRpcRequest_close_tag        11
#define drv_gpio_GpioRpcRequest_write_tag        12
#define drv_gpio_GpioRpcRequest_read_tag         13
#define drv_gpio_GpioRpcRequest_set_pull_tag     14
#define drv_gpio_GpioRpcRequest_set_irq_tag      15
#define drv_gpio_GpioRpcRequest_irq_event_tag    100
#define drv_gpio_GpioRpcResponse_req_id_tag      1
#define drv_gpio_GpioRpcResponse_setup_tag       10
#define drv_gpio_GpioRpcResponse_close_tag       11
#define drv_gpio_GpioRpcResponse_write_tag       12
#define drv_gpio_GpioRpcResponse_read_tag        13
#define drv_gpio_GpioRpcResponse_set_pull_tag    14
#define drv_gpio_GpioRpcResponse_set_irq_tag     15
#define drv_gpio_GpioRpcResponse_irq_event_tag   100

/* Struct field encoding specification for nanopb */
#define drv_gpio_GpioResult_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    code,              1) \
X(a, STATIC,   OPTIONAL, INT32,    os_errno,          2) \
X(a, STATIC,   OPTIONAL, STRING,   msg,               3)
#define drv_gpio_GpioResult_CALLBACK NULL
#define drv_gpio_GpioResult_DEFAULT (const pb_byte_t*)"\x10\x00\x00"

#define drv_gpio_GpioSetupRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   pin,               1) \
X(a, STATIC,   OPTIONAL, UENUM,    mode,              2) \
X(a, STATIC,   OPTIONAL, UENUM,    pull,              3) \
X(a, STATIC,   OPTIONAL, UENUM,    init_level,        4) \
X(a, STATIC,   OPTIONAL, UENUM,    irq_type,          5) \
X(a, STATIC,   OPTIONAL, BOOL,     irq_enable,        6) \
X(a, STATIC,   OPTIONAL, UINT32,   debounce_ms,       7)
#define drv_gpio_GpioSetupRequest_CALLBACK NULL
#define drv_gpio_GpioSetupRequest_DEFAULT (const pb_byte_t*)"\x10\x02\x18\x01\x20\x01\x30\x00\x38\x00\x00"

#define drv_gpio_GpioSetupResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_gpio_GpioSetupResponse_CALLBACK NULL
#define drv_gpio_GpioSetupResponse_DEFAULT NULL
#define drv_gpio_GpioSetupResponse_result_MSGTYPE drv_gpio_GpioResult

#define drv_gpio_GpioCloseRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   pin,               1)
#define drv_gpio_GpioCloseRequest_CALLBACK NULL
#define drv_gpio_GpioCloseRequest_DEFAULT NULL

#define drv_gpio_GpioCloseResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_gpio_GpioCloseResponse_CALLBACK NULL
#define drv_gpio_GpioCloseResponse_DEFAULT NULL
#define drv_gpio_GpioCloseResponse_result_MSGTYPE drv_gpio_GpioResult

#define drv_gpio_GpioWriteRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   pin,               1) \
X(a, STATIC,   REQUIRED, UENUM,    level,             2)
#define drv_gpio_GpioWriteRequest_CALLBACK NULL
#define drv_gpio_GpioWriteRequest_DEFAULT NULL

#define drv_gpio_GpioWriteResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_gpio_GpioWriteResponse_CALLBACK NULL
#define drv_gpio_GpioWriteResponse_DEFAULT NULL
#define drv_gpio_GpioWriteResponse_result_MSGTYPE drv_gpio_GpioResult

#define drv_gpio_GpioReadRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   pin,               1)
#define drv_gpio_GpioReadRequest_CALLBACK NULL
#define drv_gpio_GpioReadRequest_DEFAULT NULL

#define drv_gpio_GpioReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1) \
X(a, STATIC,   OPTIONAL, UENUM,    level,             2)
#define drv_gpio_GpioReadResponse_CALLBACK NULL
#define drv_gpio_GpioReadResponse_DEFAULT NULL
#define drv_gpio_GpioReadResponse_result_MSGTYPE drv_gpio_GpioResult

#define drv_gpio_GpioSetPullRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   pin,               1) \
X(a, STATIC,   REQUIRED, UENUM,    pull,              2)
#define drv_gpio_GpioSetPullRequest_CALLBACK NULL
#define drv_gpio_GpioSetPullRequest_DEFAULT NULL

#define drv_gpio_GpioSetPullResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_gpio_GpioSetPullResponse_CALLBACK NULL
#define drv_gpio_GpioSetPullResponse_DEFAULT NULL
#define drv_gpio_GpioSetPullResponse_result_MSGTYPE drv_gpio_GpioResult

#define drv_gpio_GpioSetIrqRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   pin,               1) \
X(a, STATIC,   OPTIONAL, UENUM,    irq_type,          2) \
X(a, STATIC,   OPTIONAL, BOOL,     enable,            3) \
X(a, STATIC,   OPTIONAL, UINT32,   debounce_ms,       4)
#define drv_gpio_GpioSetIrqRequest_CALLBACK NULL
#define drv_gpio_GpioSetIrqRequest_DEFAULT (const pb_byte_t*)"\x18\x01\x20\x00\x00"

#define drv_gpio_GpioSetIrqResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  result,            1)
#define drv_gpio_GpioSetIrqResponse_CALLBACK NULL
#define drv_gpio_GpioSetIrqResponse_DEFAULT NULL
#define drv_gpio_GpioSetIrqResponse_result_MSGTYPE drv_gpio_GpioResult

#define drv_gpio_GpioIrqEvent_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   pin,               1) \
X(a, STATIC,   OPTIONAL, UENUM,    irq_type,          2) \
X(a, STATIC,   OPTIONAL, UENUM,    level,             3) \
X(a, STATIC,   OPTIONAL, UINT64,   tick_ms,           4)
#define drv_gpio_GpioIrqEvent_CALLBACK NULL
#define drv_gpio_GpioIrqEvent_DEFAULT (const pb_byte_t*)"\x20\x00\x00"

#define drv_gpio_GpioRpcRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   req_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,setup,payload.setup),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,close,payload.close),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,write,payload.write),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,read,payload.read),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_pull,payload.set_pull),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_irq,payload.set_irq),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,irq_event,payload.irq_event), 100)
#define drv_gpio_GpioRpcRequest_CALLBACK NULL
#define drv_gpio_GpioRpcRequest_DEFAULT NULL
#define drv_gpio_GpioRpcRequest_payload_setup_MSGTYPE drv_gpio_GpioSetupRequest
#define drv_gpio_GpioRpcRequest_payload_close_MSGTYPE drv_gpio_GpioCloseRequest
#define drv_gpio_GpioRpcRequest_payload_write_MSGTYPE drv_gpio_GpioWriteRequest
#define drv_gpio_GpioRpcRequest_payload_read_MSGTYPE drv_gpio_GpioReadRequest
#define drv_gpio_GpioRpcRequest_payload_set_pull_MSGTYPE drv_gpio_GpioSetPullRequest
#define drv_gpio_GpioRpcRequest_payload_set_irq_MSGTYPE drv_gpio_GpioSetIrqRequest
#define drv_gpio_GpioRpcRequest_payload_irq_event_MSGTYPE drv_gpio_GpioIrqEvent

#define drv_gpio_GpioRpcResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   req_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,setup,payload.setup),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,close,payload.close),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,write,payload.write),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,read,payload.read),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_pull,payload.set_pull),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_irq,payload.set_irq),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,irq_event,payload.irq_event), 100)
#define drv_gpio_GpioRpcResponse_CALLBACK NULL
#define drv_gpio_GpioRpcResponse_DEFAULT (const pb_byte_t*)"\x08\x00\x00"
#define drv_gpio_GpioRpcResponse_payload_setup_MSGTYPE drv_gpio_GpioSetupResponse
#define drv_gpio_GpioRpcResponse_payload_close_MSGTYPE drv_gpio_GpioCloseResponse
#define drv_gpio_GpioRpcResponse_payload_write_MSGTYPE drv_gpio_GpioWriteResponse
#define drv_gpio_GpioRpcResponse_payload_read_MSGTYPE drv_gpio_GpioReadResponse
#define drv_gpio_GpioRpcResponse_payload_set_pull_MSGTYPE drv_gpio_GpioSetPullResponse
#define drv_gpio_GpioRpcResponse_payload_set_irq_MSGTYPE drv_gpio_GpioSetIrqResponse
#define drv_gpio_GpioRpcResponse_payload_irq_event_MSGTYPE drv_gpio_GpioIrqEvent

extern const pb_msgdesc_t drv_gpio_GpioResult_msg;
extern const pb_msgdesc_t drv_gpio_GpioSetupRequest_msg;
extern const pb_msgdesc_t drv_gpio_GpioSetupResponse_msg;
extern const pb_msgdesc_t drv_gpio_GpioCloseRequest_msg;
extern const pb_msgdesc_t drv_gpio_GpioCloseResponse_msg;
extern const pb_msgdesc_t drv_gpio_GpioWriteRequest_msg;
extern const pb_msgdesc_t drv_gpio_GpioWriteResponse_msg;
extern const pb_msgdesc_t drv_gpio_GpioReadRequest_msg;
extern const pb_msgdesc_t drv_gpio_GpioReadResponse_msg;
extern const pb_msgdesc_t drv_gpio_GpioSetPullRequest_msg;
extern const pb_msgdesc_t drv_gpio_GpioSetPullResponse_msg;
extern const pb_msgdesc_t drv_gpio_GpioSetIrqRequest_msg;
extern const pb_msgdesc_t drv_gpio_GpioSetIrqResponse_msg;
extern const pb_msgdesc_t drv_gpio_GpioIrqEvent_msg;
extern const pb_msgdesc_t drv_gpio_GpioRpcRequest_msg;
extern const pb_msgdesc_t drv_gpio_GpioRpcResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define drv_gpio_GpioResult_fields &drv_gpio_GpioResult_msg
#define drv_gpio_GpioSetupRequest_fields &drv_gpio_GpioSetupRequest_msg
#define drv_gpio_GpioSetupResponse_fields &drv_gpio_GpioSetupResponse_msg
#define drv_gpio_GpioCloseRequest_fields &drv_gpio_GpioCloseRequest_msg
#define drv_gpio_GpioCloseResponse_fields &drv_gpio_GpioCloseResponse_msg
#define drv_gpio_GpioWriteRequest_fields &drv_gpio_GpioWriteRequest_msg
#define drv_gpio_GpioWriteResponse_fields &drv_gpio_GpioWriteResponse_msg
#define drv_gpio_GpioReadRequest_fields &drv_gpio_GpioReadRequest_msg
#define drv_gpio_GpioReadResponse_fields &drv_gpio_GpioReadResponse_msg
#define drv_gpio_GpioSetPullRequest_fields &drv_gpio_GpioSetPullRequest_msg
#define drv_gpio_GpioSetPullResponse_fields &drv_gpio_GpioSetPullResponse_msg
#define drv_gpio_GpioSetIrqRequest_fields &drv_gpio_GpioSetIrqRequest_msg
#define drv_gpio_GpioSetIrqResponse_fields &drv_gpio_GpioSetIrqResponse_msg
#define drv_gpio_GpioIrqEvent_fields &drv_gpio_GpioIrqEvent_msg
#define drv_gpio_GpioRpcRequest_fields &drv_gpio_GpioRpcRequest_msg
#define drv_gpio_GpioRpcResponse_fields &drv_gpio_GpioRpcResponse_msg

/* Maximum encoded size of messages (where known) */
#define DRV_GPIO_DRV_GPIO_PB_H_MAX_SIZE          drv_gpio_GpioRpcResponse_size
#define drv_gpio_GpioCloseRequest_size           6
#define drv_gpio_GpioCloseResponse_size          49
#define drv_gpio_GpioIrqEvent_size               21
#define drv_gpio_GpioReadRequest_size            6
#define drv_gpio_GpioReadResponse_size           51
#define drv_gpio_GpioResult_size                 47
#define drv_gpio_GpioRpcRequest_size             30
#define drv_gpio_GpioRpcResponse_size            59
#define drv_gpio_GpioSetIrqRequest_size          16
#define drv_gpio_GpioSetIrqResponse_size         49
#define drv_gpio_GpioSetPullRequest_size         8
#define drv_gpio_GpioSetPullResponse_size        49
#define drv_gpio_GpioSetupRequest_size           22
#define drv_gpio_GpioSetupResponse_size          49
#define drv_gpio_GpioWriteRequest_size           8
#define drv_gpio_GpioWriteResponse_size          49

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
