/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DRV_SDATA_PB_H_INCLUDED
#define PB_DRV_SDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1400) SdataNotify_data_t;
/* SdataNotify: fire-and-forget raw data send from master to slave (RPC ID 0x0500) */
typedef struct _SdataNotify {
    SdataNotify_data_t data;
} SdataNotify;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SdataNotify_init_default                 {{0, {0}}}
#define SdataNotify_init_zero                    {{0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define SdataNotify_data_tag                     1

/* Struct field encoding specification for nanopb */
#define SdataNotify_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    data,              1)
#define SdataNotify_CALLBACK NULL
#define SdataNotify_DEFAULT NULL

extern const pb_msgdesc_t SdataNotify_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SdataNotify_fields &SdataNotify_msg

/* Maximum encoded size of messages (where known) */
#define DRV_SDATA_PB_H_MAX_SIZE                  SdataNotify_size
#define SdataNotify_size                         1403

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
