#ifndef _IOMUX_PINCFG_H_
#define _IOMUX_PINCFG_H_

// Auto generated. Don't edit it manually!

static const halIomuxConfig_t gHalIomuxConfig[] = {
    {&hwp_iomux->pad_adi_scl_cfg_reg, 0}, // PINFUNC_ADI_SCL
    {&hwp_iomux->pad_adi_sda_cfg_reg, 0}, // PINFUNC_ADI_SDA
    {&hwp_iomux->pad_adi_sync_cfg_reg, 0}, // PINFUNC_ADI_SYNC
    {&hwp_iomux->pad_ap_jtag_tck_cfg_reg, 0}, // PINFUNC_AP_JTAG_TCK
    {&hwp_iomux->pad_ap_jtag_tdi_cfg_reg, 0}, // PINFUNC_AP_JTAG_TDI
    {&hwp_iomux->pad_ap_jtag_tdo_cfg_reg, 0}, // PINFUNC_AP_JTAG_TDO
    {&hwp_iomux->pad_ap_jtag_tms_cfg_reg, 0}, // PINFUNC_AP_JTAG_TMS
    {&hwp_iomux->pad_ap_jtag_trst_cfg_reg, 0}, // PINFUNC_AP_JTAG_TRST
    {&hwp_iomux->pad_aud_ad_d0_cfg_reg, 0}, // PINFUNC_AUD_AD_D0
    {&hwp_iomux->pad_aud_ad_sync_cfg_reg, 0}, // PINFUNC_AUD_AD_SYNC
    {&hwp_iomux->pad_aud_da_d0_cfg_reg, 0}, // PINFUNC_AUD_DA_D0
    {&hwp_iomux->pad_aud_da_d1_cfg_reg, 0}, // PINFUNC_AUD_DA_D1
    {&hwp_iomux->pad_aud_da_sync_cfg_reg, 0}, // PINFUNC_AUD_DA_SYNC
    {&hwp_iomux->pad_aud_sclk_cfg_reg, 0}, // PINFUNC_AUD_SCLK
    {&hwp_iomux->pad_camera_pwdn_cfg_reg, 0}, // PINFUNC_CAMERA_PWDN
    {&hwp_iomux->pad_camera_ref_clk_cfg_reg, 0}, // PINFUNC_CAMERA_REF_CLK
    {&hwp_iomux->pad_camera_rst_l_cfg_reg, 0}, // PINFUNC_CAMERA_RST_L
    {&hwp_iomux->pad_gpio_0_cfg_reg, 7}, // PINFUNC_DEBUG_CLK
    {&hwp_iomux->pad_debug_host_clk_cfg_reg, 0}, // PINFUNC_DEBUG_HOST_CLK
    {&hwp_iomux->pad_debug_host_rx_cfg_reg, 0}, // PINFUNC_DEBUG_HOST_RX
    {&hwp_iomux->pad_debug_host_tx_cfg_reg, 0}, // PINFUNC_DEBUG_HOST_TX
    {&hwp_iomux->pad_rfdig_gpio_2_cfg_reg, 5}, // PINFUNC_DFE_RX_ENABLE_M_I
    {&hwp_iomux->pad_rfdig_gpio_2_cfg_reg, 7}, // PINFUNC_DFE_RX_ENABLE_S_O
    {&hwp_iomux->pad_rfdig_gpio_3_cfg_reg, 5}, // PINFUNC_DIGRF_CP_26M_M_O
    {&hwp_iomux->pad_rfdig_gpio_3_cfg_reg, 7}, // PINFUNC_DIGRF_CP_26M_S_I
    {&hwp_iomux->pad_rfdig_gpio_7_cfg_reg, 5}, // PINFUNC_DIGRF_RX_DATA_M_O
    {&hwp_iomux->pad_rfdig_gpio_7_cfg_reg, 7}, // PINFUNC_DIGRF_RX_DATA_S_I
    {&hwp_iomux->pad_rfdig_gpio_6_cfg_reg, 5}, // PINFUNC_DIGRF_RX_EN_M_O
    {&hwp_iomux->pad_rfdig_gpio_6_cfg_reg, 7}, // PINFUNC_DIGRF_RX_EN_S_I
    {&hwp_iomux->pad_gpio_8_cfg_reg, 5}, // PINFUNC_DIGRF_STROBE_M_I
    {&hwp_iomux->pad_gpio_8_cfg_reg, 7}, // PINFUNC_DIGRF_STROBE_S_O
    {&hwp_iomux->pad_rfdig_gpio_5_cfg_reg, 5}, // PINFUNC_DIGRF_TX_DATA_M_I
    {&hwp_iomux->pad_rfdig_gpio_5_cfg_reg, 7}, // PINFUNC_DIGRF_TX_DATA_S_O
    {&hwp_iomux->pad_rfdig_gpio_4_cfg_reg, 5}, // PINFUNC_DIGRF_TX_EN_M_I
    {&hwp_iomux->pad_rfdig_gpio_4_cfg_reg, 7}, // PINFUNC_DIGRF_TX_EN_S_O
    {&hwp_iomux->pad_gpio_0_cfg_reg, 0}, // PINFUNC_GPIO_0
    {&hwp_iomux->pad_gpio_1_cfg_reg, 0}, // PINFUNC_GPIO_1
    {&hwp_iomux->pad_gpio_2_cfg_reg, 0}, // PINFUNC_GPIO_2
    {&hwp_iomux->pad_gpio_3_cfg_reg, 0}, // PINFUNC_GPIO_3
    {&hwp_iomux->pad_gpio_4_cfg_reg, 0}, // PINFUNC_GPIO_4
    {&hwp_iomux->pad_gpio_5_cfg_reg, 0}, // PINFUNC_GPIO_5
    {NULL, 0}, // PINFUNC_GPIO_6
    {&hwp_iomux->pad_gpio_7_cfg_reg, 0}, // PINFUNC_GPIO_7
    {&hwp_iomux->pad_gpio_8_cfg_reg, 0}, // PINFUNC_GPIO_8
    {&hwp_iomux->pad_gpio_9_cfg_reg, 0}, // PINFUNC_GPIO_9
    {&hwp_iomux->pad_gpio_10_cfg_reg, 0}, // PINFUNC_GPIO_10
    {&hwp_iomux->pad_gpio_11_cfg_reg, 0}, // PINFUNC_GPIO_11
    {&hwp_iomux->pad_gpio_12_cfg_reg, 0}, // PINFUNC_GPIO_12
    {&hwp_iomux->pad_gpio_13_cfg_reg, 0}, // PINFUNC_GPIO_13
    {&hwp_iomux->pad_gpio_14_cfg_reg, 0}, // PINFUNC_GPIO_14
    {&hwp_iomux->pad_gpio_15_cfg_reg, 0}, // PINFUNC_GPIO_15
    {&hwp_iomux->pad_i2c_m1_scl_cfg_reg, 4}, // PINFUNC_GPIO_16
    {&hwp_iomux->pad_i2c_m1_sda_cfg_reg, 4}, // PINFUNC_GPIO_17
    {&hwp_iomux->pad_camera_rst_l_cfg_reg, 4}, // PINFUNC_GPIO_18
    {&hwp_iomux->pad_gpio_19_cfg_reg, 0}, // PINFUNC_GPIO_19
    {&hwp_iomux->pad_camera_ref_clk_cfg_reg, 4}, // PINFUNC_GPIO_20
    {&hwp_iomux->pad_gpio_21_cfg_reg, 0}, // PINFUNC_GPIO_21
    {&hwp_iomux->pad_gpio_22_cfg_reg, 0}, // PINFUNC_GPIO_22
    {&hwp_iomux->pad_gpio_23_cfg_reg, 0}, // PINFUNC_GPIO_23
    {&hwp_iomux->pad_sdmmc1_cmd_cfg_reg, 1}, // PINFUNC_GPIO_24
    {&hwp_iomux->pad_sdmmc1_data_0_cfg_reg, 1}, // PINFUNC_GPIO_25
    {&hwp_iomux->pad_sdmmc1_data_1_cfg_reg, 1}, // PINFUNC_GPIO_26
    {&hwp_iomux->pad_sdmmc1_data_2_cfg_reg, 1}, // PINFUNC_GPIO_27
    {&hwp_iomux->pad_sdmmc1_data_3_cfg_reg, 1}, // PINFUNC_GPIO_28
    {&hwp_iomux->pad_sim_2_clk_cfg_reg, 2}, // PINFUNC_GPIO_29
    {&hwp_iomux->pad_sim_2_dio_cfg_reg, 2}, // PINFUNC_GPIO_30
    {&hwp_iomux->pad_sim_2_rst_cfg_reg, 2}, // PINFUNC_GPIO_31
    {&hwp_iomux->pad_gpio_8_cfg_reg, 6}, // PINFUNC_GPO_0
    {&hwp_iomux->pad_gpio_9_cfg_reg, 6}, // PINFUNC_GPO_1
    {&hwp_iomux->pad_gpio_10_cfg_reg, 6}, // PINFUNC_GPO_2
    {&hwp_iomux->pad_gpio_11_cfg_reg, 6}, // PINFUNC_GPO_3
    {&hwp_iomux->pad_gpio_12_cfg_reg, 6}, // PINFUNC_GPO_4
    {&hwp_iomux->pad_sim_2_clk_cfg_reg, 1}, // PINFUNC_GPO_5
    {&hwp_iomux->pad_sim_2_dio_cfg_reg, 1}, // PINFUNC_GPO_6
    {&hwp_iomux->pad_sim_2_rst_cfg_reg, 1}, // PINFUNC_GPO_7
    {&hwp_iomux->pad_i2c_m1_scl_cfg_reg, 0}, // PINFUNC_I2C_M1_SCL
    {&hwp_iomux->pad_i2c_m1_sda_cfg_reg, 0}, // PINFUNC_I2C_M1_SDA
    {&hwp_iomux->pad_gpio_14_cfg_reg, 1}, // PINFUNC_I2C_M2_SCL
    {&hwp_iomux->pad_gpio_15_cfg_reg, 1}, // PINFUNC_I2C_M2_SDA
    {&hwp_iomux->pad_lcd_rstb_cfg_reg, 3}, // PINFUNC_I2C_M3_SCL
    {&hwp_iomux->pad_spi_lcd_sdc_cfg_reg, 3}, // PINFUNC_I2C_M3_SDA
    {&hwp_iomux->pad_aud_da_sync_cfg_reg, 1}, // PINFUNC_I2S1_BCK
    {&hwp_iomux->pad_aud_da_d1_cfg_reg, 1}, // PINFUNC_I2S1_LRCK
    {&hwp_iomux->pad_aud_da_d0_cfg_reg, 1}, // PINFUNC_I2S1_SDAT_I
    {&hwp_iomux->pad_aud_ad_sync_cfg_reg, 1}, // PINFUNC_I2S1_SDAT_O
    {&hwp_iomux->pad_gpio_0_cfg_reg, 3}, // PINFUNC_I2S2_BCK
    {&hwp_iomux->pad_gpio_1_cfg_reg, 3}, // PINFUNC_I2S2_LRCK
    {&hwp_iomux->pad_gpio_2_cfg_reg, 3}, // PINFUNC_I2S2_SDAT_I
    {&hwp_iomux->pad_gpio_3_cfg_reg, 3}, // PINFUNC_I2S2_SDAT_O
    {&hwp_iomux->pad_keyin_0_cfg_reg, 0}, // PINFUNC_KEYIN_0
    {&hwp_iomux->pad_keyin_1_cfg_reg, 0}, // PINFUNC_KEYIN_1
    {&hwp_iomux->pad_keyin_2_cfg_reg, 0}, // PINFUNC_KEYIN_2
    {&hwp_iomux->pad_keyin_3_cfg_reg, 0}, // PINFUNC_KEYIN_3
    {&hwp_iomux->pad_keyin_4_cfg_reg, 0}, // PINFUNC_KEYIN_4
    {&hwp_iomux->pad_keyin_5_cfg_reg, 0}, // PINFUNC_KEYIN_5
    {&hwp_iomux->pad_keyout_0_cfg_reg, 0}, // PINFUNC_KEYOUT_0
    {&hwp_iomux->pad_keyout_1_cfg_reg, 0}, // PINFUNC_KEYOUT_1
    {&hwp_iomux->pad_keyout_2_cfg_reg, 0}, // PINFUNC_KEYOUT_2
    {&hwp_iomux->pad_keyout_3_cfg_reg, 0}, // PINFUNC_KEYOUT_3
    {&hwp_iomux->pad_keyout_4_cfg_reg, 0}, // PINFUNC_KEYOUT_4
    {&hwp_iomux->pad_keyout_5_cfg_reg, 0}, // PINFUNC_KEYOUT_5
    {&hwp_iomux->pad_lcd_fmark_cfg_reg, 0}, // PINFUNC_LCD_FMARK
    {&hwp_iomux->pad_lcd_rstb_cfg_reg, 0}, // PINFUNC_LCD_RSTB
    {&hwp_iomux->pad_rfdig_gpio_0_cfg_reg, 2}, // PINFUNC_LTE_GPO_0
    {&hwp_iomux->pad_rfdig_gpio_1_cfg_reg, 2}, // PINFUNC_LTE_GPO_1
    {&hwp_iomux->pad_rfdig_gpio_2_cfg_reg, 2}, // PINFUNC_LTE_GPO_2
    {&hwp_iomux->pad_rfdig_gpio_3_cfg_reg, 2}, // PINFUNC_LTE_GPO_3
    {&hwp_iomux->pad_rfdig_gpio_4_cfg_reg, 2}, // PINFUNC_LTE_GPO_4
    {&hwp_iomux->pad_rfdig_gpio_5_cfg_reg, 2}, // PINFUNC_LTE_GPO_5
    {&hwp_iomux->pad_gpio_8_cfg_reg, 3}, // PINFUNC_LTE_GPO_6
    {&hwp_iomux->pad_rfdig_gpio_6_cfg_reg, 2}, // PINFUNC_LTE_GPO_7
    {&hwp_iomux->pad_rfdig_gpio_7_cfg_reg, 2}, // PINFUNC_LTE_GPO_8
    {&hwp_iomux->pad_gpio_9_cfg_reg, 3}, // PINFUNC_LTE_GPO_9
    {&hwp_iomux->pad_gpio_10_cfg_reg, 2}, // PINFUNC_LTE_SPI_CS
    {&hwp_iomux->pad_gpio_11_cfg_reg, 2}, // PINFUNC_LTE_SPI_SCLK
    {&hwp_iomux->pad_gpio_12_cfg_reg, 2}, // PINFUNC_LTE_SPI_SDIO
    {&hwp_iomux->pad_gpio_9_cfg_reg, 4}, // PINFUNC_LTE_SPI_SDO
    {&hwp_iomux->pad_nand_flash_sel_cfg_reg, 0}, // PINFUNC_NAND_FLASH_SEL
    {&hwp_iomux->pad_gpio_4_cfg_reg, 3}, // PINFUNC_PWL_OUT_0
    {&hwp_iomux->pad_gpio_7_cfg_reg, 3}, // PINFUNC_PWL_OUT_1
    {&hwp_iomux->pad_gpio_13_cfg_reg, 1}, // PINFUNC_PWM_LPG_OUT
    {&hwp_iomux->pad_gpio_5_cfg_reg, 2}, // PINFUNC_PWT_OUT
    {&hwp_iomux->pad_rfdig_gpio_0_cfg_reg, 0}, // PINFUNC_RFDIG_GPIO_0
    {&hwp_iomux->pad_rfdig_gpio_1_cfg_reg, 0}, // PINFUNC_RFDIG_GPIO_1
    {&hwp_iomux->pad_rfdig_gpio_2_cfg_reg, 0}, // PINFUNC_RFDIG_GPIO_2
    {&hwp_iomux->pad_rfdig_gpio_3_cfg_reg, 0}, // PINFUNC_RFDIG_GPIO_3
    {&hwp_iomux->pad_rfdig_gpio_4_cfg_reg, 0}, // PINFUNC_RFDIG_GPIO_4
    {&hwp_iomux->pad_rfdig_gpio_5_cfg_reg, 0}, // PINFUNC_RFDIG_GPIO_5
    {&hwp_iomux->pad_rfdig_gpio_6_cfg_reg, 0}, // PINFUNC_RFDIG_GPIO_6
    {&hwp_iomux->pad_rfdig_gpio_7_cfg_reg, 0}, // PINFUNC_RFDIG_GPIO_7
    {&hwp_iomux->pad_gpio_8_cfg_reg, 2}, // PINFUNC_RFDIG_GPIO_8
    {&hwp_iomux->pad_gpio_9_cfg_reg, 2}, // PINFUNC_RFDIG_GPIO_9
    {&hwp_iomux->pad_ap_jtag_tck_cfg_reg, 4}, // PINFUNC_RFDIG_JTAG_TCK
    {&hwp_iomux->pad_ap_jtag_tdi_cfg_reg, 4}, // PINFUNC_RFDIG_JTAG_TDI
    {&hwp_iomux->pad_ap_jtag_tdo_cfg_reg, 4}, // PINFUNC_RFDIG_JTAG_TDO
    {&hwp_iomux->pad_ap_jtag_tms_cfg_reg, 4}, // PINFUNC_RFDIG_JTAG_TMS
    {&hwp_iomux->pad_ap_jtag_trst_cfg_reg, 4}, // PINFUNC_RFDIG_JTAG_TRST
    {&hwp_iomux->pad_rfdig_gpio_0_cfg_reg, 1}, // PINFUNC_RFFE_SCLK
    {&hwp_iomux->pad_rfdig_gpio_1_cfg_reg, 1}, // PINFUNC_RFFE_SDATA
    {&hwp_iomux->pad_sdmmc1_clk_cfg_reg, 0}, // PINFUNC_SDMMC1_CLK
    {&hwp_iomux->pad_sdmmc1_cmd_cfg_reg, 0}, // PINFUNC_SDMMC1_CMD
    {&hwp_iomux->pad_sdmmc1_data_0_cfg_reg, 0}, // PINFUNC_SDMMC1_DATA_0
    {&hwp_iomux->pad_sdmmc1_data_1_cfg_reg, 0}, // PINFUNC_SDMMC1_DATA_1
    {&hwp_iomux->pad_sdmmc1_data_2_cfg_reg, 0}, // PINFUNC_SDMMC1_DATA_2
    {&hwp_iomux->pad_sdmmc1_data_3_cfg_reg, 0}, // PINFUNC_SDMMC1_DATA_3
    {&hwp_iomux->pad_gpio_7_cfg_reg, 1}, // PINFUNC_SDMMC2_CLK
    {&hwp_iomux->pad_ap_jtag_tck_cfg_reg, 1}, // PINFUNC_SDMMC2_CMD
    {&hwp_iomux->pad_ap_jtag_trst_cfg_reg, 1}, // PINFUNC_SDMMC2_DATA_0
    {&hwp_iomux->pad_ap_jtag_tms_cfg_reg, 1}, // PINFUNC_SDMMC2_DATA_1
    {&hwp_iomux->pad_ap_jtag_tdi_cfg_reg, 1}, // PINFUNC_SDMMC2_DATA_2
    {&hwp_iomux->pad_ap_jtag_tdo_cfg_reg, 1}, // PINFUNC_SDMMC2_DATA_3
    {&hwp_iomux->pad_secure_boot_mode_cfg_reg, 0}, // PINFUNC_SECURE_BOOT_MODE
    {&hwp_iomux->pad_sim_1_clk_cfg_reg, 0}, // PINFUNC_SIM_1_CLK
    {&hwp_iomux->pad_sim_1_dio_cfg_reg, 0}, // PINFUNC_SIM_1_DIO
    {&hwp_iomux->pad_sim_1_rst_cfg_reg, 0}, // PINFUNC_SIM_1_RST
    {&hwp_iomux->pad_sim_2_clk_cfg_reg, 0}, // PINFUNC_SIM_2_CLK
    {&hwp_iomux->pad_sim_2_dio_cfg_reg, 0}, // PINFUNC_SIM_2_DIO
    {&hwp_iomux->pad_sim_2_rst_cfg_reg, 0}, // PINFUNC_SIM_2_RST
    {&hwp_iomux->pad_gpio_9_cfg_reg, 1}, // PINFUNC_SPI_1_CLK
    {&hwp_iomux->pad_gpio_10_cfg_reg, 1}, // PINFUNC_SPI_1_CS_0
    {&hwp_iomux->pad_gpio_8_cfg_reg, 1}, // PINFUNC_SPI_1_CS_1
    {&hwp_iomux->pad_gpio_12_cfg_reg, 1}, // PINFUNC_SPI_1_DI_1
    {&hwp_iomux->pad_gpio_11_cfg_reg, 1}, // PINFUNC_SPI_1_DIO_0
    {&hwp_iomux->pad_gpio_0_cfg_reg, 2}, // PINFUNC_SPI_2_CLK
    {&hwp_iomux->pad_gpio_1_cfg_reg, 2}, // PINFUNC_SPI_2_CS_0
    {&hwp_iomux->pad_gpio_4_cfg_reg, 2}, // PINFUNC_SPI_2_CS_1
    {&hwp_iomux->pad_gpio_3_cfg_reg, 2}, // PINFUNC_SPI_2_DI_1
    {&hwp_iomux->pad_gpio_2_cfg_reg, 2}, // PINFUNC_SPI_2_DIO_0
    {&hwp_iomux->pad_spi_camera_sck_cfg_reg, 0}, // PINFUNC_SPI_CAMERA_SCK
    {&hwp_iomux->pad_spi_camera_si_0_cfg_reg, 0}, // PINFUNC_SPI_CAMERA_SI_0
    {&hwp_iomux->pad_spi_camera_si_1_cfg_reg, 0}, // PINFUNC_SPI_CAMERA_SI_1
    {&hwp_iomux->pad_spi_camera_si_1_cfg_reg, 2}, // PINFUNC_SPI_CAMERA_SSN
    {&hwp_iomux->pad_gpio_0_cfg_reg, 1}, // PINFUNC_SPI_FLASH1_CLK
    {&hwp_iomux->pad_gpio_1_cfg_reg, 1}, // PINFUNC_SPI_FLASH1_CS
    {&hwp_iomux->pad_gpio_2_cfg_reg, 1}, // PINFUNC_SPI_FLASH1_SIO_0
    {&hwp_iomux->pad_gpio_3_cfg_reg, 1}, // PINFUNC_SPI_FLASH1_SIO_1
    {&hwp_iomux->pad_gpio_4_cfg_reg, 1}, // PINFUNC_SPI_FLASH1_SIO_2
    {&hwp_iomux->pad_gpio_5_cfg_reg, 1}, // PINFUNC_SPI_FLASH1_SIO_3
    {&hwp_iomux->pad_spi_flash_clk_cfg_reg, 0}, // PINFUNC_SPI_FLASH_CLK
    {&hwp_iomux->pad_spi_flash_cs_cfg_reg, 0}, // PINFUNC_SPI_FLASH_CS
    {&hwp_iomux->pad_spi_flash_sel_cfg_reg, 0}, // PINFUNC_SPI_FLASH_SEL
    {&hwp_iomux->pad_spi_flash_sio_0_cfg_reg, 0}, // PINFUNC_SPI_FLASH_SIO_0
    {&hwp_iomux->pad_spi_flash_sio_1_cfg_reg, 0}, // PINFUNC_SPI_FLASH_SIO_1
    {&hwp_iomux->pad_spi_flash_sio_2_cfg_reg, 0}, // PINFUNC_SPI_FLASH_SIO_2
    {&hwp_iomux->pad_spi_flash_sio_3_cfg_reg, 0}, // PINFUNC_SPI_FLASH_SIO_3
    {&hwp_iomux->pad_spi_lcd_clk_cfg_reg, 0}, // PINFUNC_SPI_LCD_CLK
    {&hwp_iomux->pad_spi_lcd_cs_cfg_reg, 0}, // PINFUNC_SPI_LCD_CS
    {&hwp_iomux->pad_spi_lcd_sdc_cfg_reg, 0}, // PINFUNC_SPI_LCD_SDC
    {&hwp_iomux->pad_spi_lcd_select_cfg_reg, 0}, // PINFUNC_SPI_LCD_SELECT
    {&hwp_iomux->pad_spi_lcd_sio_cfg_reg, 0}, // PINFUNC_SPI_LCD_SIO
    {&hwp_iomux->pad_spi_camera_sck_cfg_reg, 3}, // PINFUNC_SPI_LVDS_CLK
    {&hwp_iomux->pad_spi_camera_si_1_cfg_reg, 3}, // PINFUNC_SPI_LVDS_CS
    {&hwp_iomux->pad_camera_ref_clk_cfg_reg, 3}, // PINFUNC_SPI_LVDS_DI
    {&hwp_iomux->pad_spi_camera_si_0_cfg_reg, 3}, // PINFUNC_SPI_LVDS_DO
    {&hwp_iomux->pad_gpio_18_cfg_reg, 1}, // PINFUNC_UART_1_CTS
    {&hwp_iomux->pad_gpio_19_cfg_reg, 1}, // PINFUNC_UART_1_RTS
    {NULL, 0}, // PINFUNC_UART_1_RXD
    {NULL, 0}, // PINFUNC_UART_1_TXD
    {&hwp_iomux->pad_gpio_20_cfg_reg, 1}, // PINFUNC_UART_2_RXD
    {&hwp_iomux->pad_gpio_21_cfg_reg, 1}, // PINFUNC_UART_2_TXD
    {&hwp_iomux->pad_keyout_4_cfg_reg, 4}, // PINFUNC_UART_3_RXD
    {&hwp_iomux->pad_keyout_5_cfg_reg, 4}, // PINFUNC_UART_3_TXD
    {&hwp_iomux->pad_gpio_0_cfg_reg, 5}, // PINFUNC_UART_RXD_RF
    {&hwp_iomux->pad_gpio_1_cfg_reg, 5}, // PINFUNC_UART_TXD_RF
    {&hwp_iomux->pad_gpio_3_cfg_reg, 5}, // PINFUNC_WCN_HST_RXD
    {&hwp_iomux->pad_gpio_2_cfg_reg, 5}, // PINFUNC_WCN_HST_TXD
    {&hwp_iomux->pad_gpio_0_cfg_reg, 4}, // PINFUNC_WCN_JTAG_TCK
    {&hwp_iomux->pad_gpio_3_cfg_reg, 4}, // PINFUNC_WCN_JTAG_TDI
    {&hwp_iomux->pad_gpio_4_cfg_reg, 4}, // PINFUNC_WCN_JTAG_TDO
    {&hwp_iomux->pad_gpio_2_cfg_reg, 4}, // PINFUNC_WCN_JTAG_TMS
    {&hwp_iomux->pad_gpio_1_cfg_reg, 4}, // PINFUNC_WCN_JTAG_TRST
    {&hwp_iomux->pad_gpio_7_cfg_reg, 5}, // PINFUNC_WCN_UART_RXD
    {&hwp_iomux->pad_gpio_5_cfg_reg, 5}, // PINFUNC_WCN_UART_TXD
    {&hwp_iomux->pad_ap_jtag_tck_cfg_reg, 3}, // PINFUNC_ZSP_JTAG_TCK
    {&hwp_iomux->pad_ap_jtag_tdi_cfg_reg, 3}, // PINFUNC_ZSP_JTAG_TDI
    {&hwp_iomux->pad_ap_jtag_tdo_cfg_reg, 3}, // PINFUNC_ZSP_JTAG_TDO
    {&hwp_iomux->pad_ap_jtag_tms_cfg_reg, 3}, // PINFUNC_ZSP_JTAG_TMS
    {&hwp_iomux->pad_ap_jtag_trst_cfg_reg, 3}, // PINFUNC_ZSP_JTAG_TRST
    {&hwp_iomux->pad_gpio_22_cfg_reg, 5}, // PINFUNC_ZSP_UART_TXD
};

#endif

