

includes("camera")
includes("io_queue")
includes("lora")
includes("mlx90640")
includes("onchip")
includes("sfd")
includes("sfud")
includes("soft_keyboard")
includes("statem")
includes("usbapp")

target("peripheral")
    set_kind("camera")
    add_deps("io_queue")
    add_deps("lora")
    add_deps("mlx90640")
    add_deps("onchip")
    add_deps("sfd")
    add_deps("sfud")
    add_deps("soft_keyboard")
    add_deps("statem")
    add_deps("usbapp")
target_end()
